import { describe, expect, it } from '../../../testing/node-test';
import { normalizeExecutionAdapterReferenceId, normalizeExecutionDependencyId, normalizeExecutionInputId, normalizeExecutionOutputId, normalizeExecutionPlanId, normalizeExecutionSafetyGateId, normalizeExecutionStepId } from '../execution-plan-identity';
import { normalizeExecutionPlanStatus, normalizeExecutionStepKind, normalizeExecutionStepStatus } from '../execution-plan-status';
import { normalizeExecutionDependencyKind, normalizeExecutionDependencyStatus } from '../execution-plan-dependency';
import { normalizeExecutionInputKind, normalizeExecutionInputOutputStatus, normalizeExecutionOutputKind } from '../execution-plan-input-output';
import { normalizeExecutionAdapterReferenceKind, normalizeExecutionAdapterReferenceStatus } from '../execution-plan-adapter-reference';
import { normalizeExecutionSafetyGateKind, normalizeExecutionSafetyGateStatus } from '../execution-plan-safety-gate';
import { normalizeExecutionComputeEstimateCategory } from '../execution-plan-resource-estimate';
import { normalizeExecutionDiagnostic, normalizeExecutionBlocker } from '../execution-plan-diagnostics';
import { normalizeExecutionPlanRecord } from '../execution-plan-normalization';

describe('execution plan contracts',()=>{
 it('normalizes ids',()=>{ expect(normalizeExecutionPlanId('plan.alpha')).toBe('plan.alpha'); expect(normalizeExecutionStepId('step.a')).toBe('step.a'); expect(normalizeExecutionDependencyId('dep.a')).toBe('dep.a'); expect(normalizeExecutionInputId('input.a')).toBe('input.a'); expect(normalizeExecutionOutputId('output.a')).toBe('output.a'); expect(normalizeExecutionAdapterReferenceId('adapter.a')).toBe('adapter.a'); expect(normalizeExecutionSafetyGateId('gate.a')).toBe('gate.a');});
 it('rejects unsafe ids and sanitizes errors',()=>{ for(const v of ['',' ',' ../x ','https://x','token-abc']) expect(()=>normalizeExecutionPlanId(v)).toThrow(/safe non-empty identifier/); expect(()=>normalizeExecutionPlanId('https://bad')).toThrowError(new Error('ExecutionPlanId must be a safe non-empty identifier.')); });
 it('normalizes statuses and kinds',()=>{ expect(normalizeExecutionPlanStatus('draft')).toBe('draft'); expect(()=>normalizeExecutionPlanStatus('running')).toThrow(); expect(normalizeExecutionStepStatus('planned')).toBe('planned'); expect(normalizeExecutionStepKind('generate-image')).toBe('generate-image'); expect(normalizeExecutionDependencyKind('input-required')).toBe('input-required'); expect(normalizeExecutionDependencyStatus('missing')).toBe('missing'); expect(normalizeExecutionInputKind('asset-reference')).toBe('asset-reference'); expect(normalizeExecutionOutputKind('artifact')).toBe('artifact'); expect(normalizeExecutionInputOutputStatus('planned')).toBe('planned'); expect(normalizeExecutionAdapterReferenceKind('provider-adapter')).toBe('provider-adapter'); expect(normalizeExecutionAdapterReferenceStatus('needs-setup')).toBe('needs-setup'); expect(normalizeExecutionSafetyGateKind('user-review-required')).toBe('user-review-required'); expect(normalizeExecutionSafetyGateStatus('planned')).toBe('planned'); expect(normalizeExecutionComputeEstimateCategory('low')).toBe('low'); });
 it('validates diagnostics and blockers',()=>{ expect(normalizeExecutionDiagnostic({code:'execution-plan-step-missing',severity:'error',message:'Step is missing'}).code).toBe('execution-plan-step-missing'); expect(()=>normalizeExecutionDiagnostic({code:'x',severity:'error',message:'secret token'})).toThrow(); expect(()=>normalizeExecutionBlocker({code:'bad/path',message:'blocked'})).toThrow(); });
 it('validates record safety constraints',()=>{ const base:any={id:'plan.alpha',workspaceId:'ws-1',sourceCompositionPlanId:'cp-1',sourceRuntimeReadinessBindingId:'rb-1',sourceReadinessStatus:'ready-for-review',status:'draft',steps:[],dependencies:[],inputs:[],outputs:[],adapterReferences:[],safetyGates:[],blockers:[],diagnostics:[],resourceEstimates:[],provenance:[],createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'}; expect(normalizeExecutionPlanRecord(base).workspaceId).toBe('ws-1'); expect(()=>normalizeExecutionPlanRecord({...base,workspaceId:' '})).toThrow(); expect(()=>normalizeExecutionPlanRecord({...base,sourceRuntimeReadinessBindingId:''})).toThrow(); expect(()=>normalizeExecutionPlanRecord({...base,sourceCompositionPlanId:''})).toThrow(); expect(()=>normalizeExecutionPlanRecord({...base,commandLine:'rm -rf /'})).toThrow(); });
});
