import type { EffectiveAssetProjectionRepositoryPort } from "../../../../application/ports/effective-asset-projections";
import type { WorkspaceEffectiveAssetProjectionReadModelService } from "../../../../application/services/asset/workspace-effective-asset-projection-read-model.service";
import type { CreateAuthoredAssetEffectiveProjectionUseCase, CreateOverrideEffectiveProjectionUseCase, PreviewDraftEffectiveAssetProjectionUseCase, RefreshAuthoredAssetEffectiveProjectionUseCase, RefreshOverrideEffectiveProjectionUseCase } from "../../../../application/use-cases/effective-asset-projections";
import type { IpcMainHandlePort } from "../ipcMainHandlePort";
const C={createAuthored:"effective-asset-projections:create-authored",refreshAuthored:"effective-asset-projections:refresh-authored",previewDraft:"effective-asset-projections:preview-draft",createOverride:"effective-asset-projections:create-override",refreshOverride:"effective-asset-projections:refresh-override",list:"effective-asset-projections:list",read:"effective-asset-projections:read",readByRef:"effective-asset-projections:read-by-effective-reference",listBlocked:"effective-asset-projections:list-blocked"} as const;
const S=(v:unknown)=>typeof v==="string"?v.trim():""; const txt=(v:unknown)=>S(v).length>0;
export interface RegisterEffectiveAssetProjectionIpcDependencies {ipcMain:IpcMainHandlePort; createAuthored?:CreateAuthoredAssetEffectiveProjectionUseCase; refreshAuthored?:RefreshAuthoredAssetEffectiveProjectionUseCase; previewDraft?:PreviewDraftEffectiveAssetProjectionUseCase; createOverride?:CreateOverrideEffectiveProjectionUseCase; refreshOverride?:RefreshOverrideEffectiveProjectionUseCase; readModel?:WorkspaceEffectiveAssetProjectionReadModelService; projectionRepository?:EffectiveAssetProjectionRepositoryPort;}
const fail=(op:string,code:string,m:string)=>({ok:false,error:{operation:op,code,message:m}}); const ok=(op:string,value:unknown)=>({ok:true,operation:op,value});
export function registerEffectiveAssetProjectionIpc(d:RegisterEffectiveAssetProjectionIpcDependencies):void { const cmd=(ch:string,op:string,wf:string,uc:any)=>d.ipcMain.handle(ch,async(_e,r:any)=>{const w=S(r?.payload?.[wf]); if(!txt(w)) return fail(op,"validation",`${wf} is required.`); if(!uc) return fail(op,"unavailable","Operation unavailable."); try{const x=await uc.execute(r.payload); return x.kind==="failure"?fail(op,x.failure.code,"Operation failed."):ok(op,x.value);}catch{return fail(op,"internal","Operation failed.");}});
cmd(C.createAuthored,C.createAuthored,"targetWorkspaceId",d.createAuthored); cmd(C.previewDraft,C.previewDraft,"targetWorkspaceId",d.previewDraft); cmd(C.createOverride,C.createOverride,"targetWorkspaceId",d.createOverride); cmd(C.refreshAuthored,C.refreshAuthored,"targetWorkspaceId",d.refreshAuthored); cmd(C.refreshOverride,C.refreshOverride,"targetWorkspaceId",d.refreshOverride);
d.ipcMain.handle(C.list,async(_e,r:any)=>{const w=S(r?.payload?.targetWorkspaceId); if(!txt(w)||!d.readModel) return fail(C.list,txt(w)?"unavailable":"validation",txt(w)?"Read unavailable.":"targetWorkspaceId is required."); return ok(C.list,await d.readModel.listByWorkspace({targetWorkspaceId:w as never,...r.payload}));});
d.ipcMain.handle(C.read,async(_e,r:any)=>{const w=S(r?.payload?.targetWorkspaceId),p=S(r?.payload?.projectionId); if(!txt(w)||!txt(p)||!d.readModel) return fail(C.read,(!txt(w)||!txt(p))?"validation":"unavailable",(!txt(w)||!txt(p))?"targetWorkspaceId and projectionId are required.":"Read unavailable."); const v=await d.readModel.readByProjectionId(w as never,p); return v?ok(C.read,v):fail(C.read,"not-found","Projection not found.");});
d.ipcMain.handle(C.readByRef,async(_e,r:any)=>{const w=S(r?.payload?.targetWorkspaceId); const ref=r?.payload?.effectiveAssetReference; if(!txt(w)||typeof ref!=="object"||ref===null||!txt((ref as any).kind)||!txt((ref as any).id)||!d.readModel) return fail(C.readByRef,(!txt(w)||!ref)?"validation":"unavailable","Invalid request or unavailable."); const v=await d.readModel.readByEffectiveAssetReference(w as never,{kind:S((ref as any).kind) as never,id:S((ref as any).id),version:txt((ref as any).version)?S((ref as any).version):undefined}); return v?ok(C.readByRef,v):fail(C.readByRef,"not-found","Projection not found.");});
d.ipcMain.handle(C.listBlocked,async(_e,r:any)=>{const w=S(r?.payload?.targetWorkspaceId); if(!txt(w)||!d.projectionRepository) return fail(C.listBlocked,txt(w)?"unavailable":"validation",txt(w)?"Read unavailable.":"targetWorkspaceId is required."); const records=await d.projectionRepository.listBlockedConflictedOrStaleEffectiveAssetProjectionRecords(w as never); return ok(C.listBlocked,{summaries:records});});
}
