import { createWorkspaceId } from '../workspace'; import { normalizeExecutionRunId, normalizeExecutionResultId } from '../execution-runs';
import { MAX_ASSISTANT_RESPONSE_LENGTH, MAX_USER_MESSAGE_LENGTH } from './conversation-message'; import { normalizeAssistantResponseId, normalizeConversationMessageId, normalizeConversationSessionId, normalizeConversationTurnId } from './conversation-identity'; import { normalizeAssistantResponseStatus, normalizeConversationContentKind, normalizeConversationMessageRole, normalizeConversationSessionStatus, normalizeConversationTurnStatus } from './conversation-status';
const ISO=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/; const UNSAFE=/(?:[A-Za-z0-9+\/=]{200,}|\x00|\x01|\x02|\x03|\x04|\x05|\x06|\x07|\x08|\x0B|\x0C|\x0E|\x0F)/;
const ts=(v:string,f:string)=>{const t=v.trim(); if(!ISO.test(t)) throw new Error(`${f} is invalid.`); return t;}; const plain=(v:string,m:number,f:string,allowEmpty=false)=>{if(typeof v!=='string') throw new Error(`${f} is invalid.`); const t=v.replace(/\r\n/g,'\n'); if(!allowEmpty&&!t.trim()) throw new Error(`${f} is invalid.`); if(t.length>m||UNSAFE.test(t)) throw new Error(`${f} is invalid.`); return t;};
export const normalizeUserVisibleMessageText=(v:string)=>plain(v,MAX_USER_MESSAGE_LENGTH,'Conversation message text'); export const normalizeAssistantVisibleResponseText=(v:string)=>plain(v,MAX_ASSISTANT_RESPONSE_LENGTH,'Assistant response text');
export const normalizeConversationMessageRecord=(m:any)=>({...m,id:normalizeConversationMessageId(m.id),workspaceId:createWorkspaceId(m.workspaceId),conversationSessionId:normalizeConversationSessionId(m.conversationSessionId),conversationTurnId:normalizeConversationTurnId(m.conversationTurnId),role:normalizeConversationMessageRole(m.role),contentKind:normalizeConversationContentKind(m.contentKind),text:normalizeUserVisibleMessageText(m.text),createdAt:ts(m.createdAt,'createdAt')});
export const normalizeAssistantResponseRecord=(r:any)=>({...r,id:normalizeAssistantResponseId(r.id),workspaceId:createWorkspaceId(r.workspaceId),conversationSessionId:normalizeConversationSessionId(r.conversationSessionId),conversationTurnId:normalizeConversationTurnId(r.conversationTurnId),executionRunId:normalizeExecutionRunId(r.executionRunId),executionResultId:normalizeExecutionResultId(r.executionResultId),role:normalizeConversationMessageRole(r.role),contentKind:normalizeConversationContentKind(r.contentKind),text:normalizeAssistantVisibleResponseText(r.text),status:normalizeAssistantResponseStatus(r.status),createdAt:ts(r.createdAt,'createdAt')});
export const normalizeConversationSessionRecord=(s:any)=>({...s,id:normalizeConversationSessionId(s.id),workspaceId:createWorkspaceId(s.workspaceId),sourceExecutionPlanId:s.sourceExecutionPlanId,status:normalizeConversationSessionStatus(s.status),systemLabel:plain(s.systemLabel,240,'systemLabel'),updatedAt:ts(s.updatedAt,'updatedAt')});
export const normalizeConversationTurnRecord=(t:any)=>({...t,id:normalizeConversationTurnId(t.id),workspaceId:createWorkspaceId(t.workspaceId),conversationSessionId:normalizeConversationSessionId(t.conversationSessionId),userMessageId:normalizeConversationMessageId(t.userMessageId),status:normalizeConversationTurnStatus(t.status),updatedAt:ts(t.updatedAt,'updatedAt')});
