import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";
import { normalizeAssetId } from "../../../../contracts/asset";
import { createAssetCompositionNodeId, createAssetCompositionPlanId, createAssetCompositionRelationshipId } from "../../../../contracts/asset-composition";
import { createEffectiveAssetProjectionId } from "../../../../contracts/effective-asset-projections";
import { createWorkspaceId } from "../../../../contracts/workspace";
import { createLocalAssetCompositionPlanRepositoryAdapter, LocalAssetCompositionPlanRecordStoreError } from "..";

const wsA=createWorkspaceId("workspace.a"); const wsB=createWorkspaceId("workspace.b");
const makePlan=(ws:string,id:string,projection:string,status:any="draft")=>({planId:createAssetCompositionPlanId(id),targetWorkspaceId:ws,name:`Plan ${id}`,status,selectedProjections:[{targetWorkspaceId:ws,projectionId:createEffectiveAssetProjectionId(projection),effectiveAssetReference:{kind:"asset-definition-version",id:normalizeAssetId(`asset.${id}`),version:"1.0.0"},displayLabel:"Selected"}],nodes:[{nodeId:createAssetCompositionNodeId(`node.${id}`),targetWorkspaceId:ws,selectedProjection:{targetWorkspaceId:ws,projectionId:createEffectiveAssetProjectionId(projection)},role:"primary",status:"compatible",requiredCapabilities:[],providedCapabilities:[],diagnostics:[],blockers:[],label:"Node",createdAt:"2026-05-20T00:00:00.000Z",updatedAt:"2026-05-20T00:00:00.000Z"}],relationships:[{relationshipId:createAssetCompositionRelationshipId(`rel.${id}`),targetWorkspaceId:ws,sourceNodeId:createAssetCompositionNodeId(`node.${id}`),targetNodeId:createAssetCompositionNodeId(`node.${id}`),kind:"depends-on",compatibilityStatus:"compatible",diagnostics:[],blockers:[],createdAt:"2026-05-20T00:00:00.000Z",updatedAt:"2026-05-20T00:00:00.000Z"}],compatibilityDiagnostics:[],blockers:[],planningSummary:{totalNodes:1,compatibleNodeCount:1,blockedNodeCount:0,conflictedNodeCount:0,missingDependencyCount:0,staleProjectionCount:0,unsupportedCount:0,totalRelationships:1,compatibleRelationshipCount:1,blockedRelationshipCount:0,planningReadiness:"ready"},provenance:[{eventId:`evt.${id}`,targetWorkspaceId:ws,timestamp:"2026-05-20T00:00:00.000Z",kind:"created",summary:"s"}],createdAt:"2026-05-20T00:00:00.000Z",updatedAt: id.endsWith('2') ? "2026-05-20T01:00:00.000Z" : "2026-05-20T00:00:00.000Z"});

describe("local asset composition plan persistence",()=>{
 it("saves reads filters and isolates records by workspace", async()=>{const rootDir=await mkdtemp(join(tmpdir(),"acp-")); const repo=createLocalAssetCompositionPlanRepositoryAdapter({rootDir}); const a=makePlan(wsA,"plan.1","projection.a"); const b=makePlan(wsB,"plan.1","projection.b","blocked"); await repo.saveAssetCompositionPlanRecord(a as any); await repo.saveAssetCompositionPlanRecord(b as any); assert.equal((await repo.readAssetCompositionPlanRecord(wsA,a.planId))?.planId,a.planId); assert.equal((await repo.readAssetCompositionPlanRecord(wsB,a.planId)),undefined); assert.equal((await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA})).records.length,1); assert.equal((await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsB,status:"blocked"})).records.length,1);});
 it("supports deterministic list ordering and scoped upsert key", async()=>{const rootDir=await mkdtemp(join(tmpdir(),"acp-")); const repo=createLocalAssetCompositionPlanRepositoryAdapter({rootDir}); await repo.saveAssetCompositionPlanRecord(makePlan(wsA,"plan.1","projection.a") as any); await repo.saveAssetCompositionPlanRecord(makePlan(wsA,"plan.2","projection.a") as any); const records=(await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA})).records; assert.equal(records[0]?.planId,createAssetCompositionPlanId("plan.2")); assert.equal(records.length,2);});
 it("archives and filters by selected projection and effective asset reference", async()=>{const rootDir=await mkdtemp(join(tmpdir(),"acp-")); const repo=createLocalAssetCompositionPlanRepositoryAdapter({rootDir}); const a=makePlan(wsA,"plan.1","projection.a"); await repo.saveAssetCompositionPlanRecord(a as any); await repo.archiveAssetCompositionPlanRecord(wsA,a.planId,"2026-05-20T02:00:00.000Z"); assert.equal((await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA,archived:true})).records.length,1); assert.equal((await repo.listAssetCompositionPlanRecordsBySelectedProjectionId(wsA,createEffectiveAssetProjectionId("projection.a"))).length,1); assert.equal((await repo.listAssetCompositionPlanRecordsByEffectiveAssetReference(wsA,{kind:"asset-definition-version",id:normalizeAssetId("asset.plan.1"),version:"1.0.0"})).length,1);});
 it("fails safely on manifest schema mismatch", async()=>{const rootDir=await mkdtemp(join(tmpdir(),"acp-")); const repo=createLocalAssetCompositionPlanRepositoryAdapter({rootDir}); await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA}); const p=join(rootDir,"asset-composition","asset-composition-manifest.json"); const manifest=JSON.parse(await readFile(p,"utf8")); manifest.schemaVersion=99; await writeFile(p,JSON.stringify(manifest)); await assert.rejects(()=>repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA}), LocalAssetCompositionPlanRecordStoreError);});
});
