import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";
import { normalizeAssetId } from "../../../../contracts/asset";
import { createAssetCompositionNodeId, createAssetCompositionPlanId, createAssetCompositionRelationshipId, type AssetCompositionPlan } from "../../../../contracts/asset-composition";
import { createEffectiveAssetProjectionId } from "../../../../contracts/effective-asset-projections";
import { createWorkspaceId } from "../../../../contracts/workspace";
import { createLocalAssetCompositionPlanRepositoryAdapter, LocalAssetCompositionPlanRecordStoreError } from "..";

const wsA=createWorkspaceId("workspace.a"); const wsB=createWorkspaceId("workspace.b");
const makePlan=(ws:string,id:string,status:AssetCompositionPlan["status"]="draft"):AssetCompositionPlan=>({planId:createAssetCompositionPlanId(id),targetWorkspaceId:ws,name:`Plan ${id}`,status,selectedProjections:[{targetWorkspaceId:ws,projectionId:createEffectiveAssetProjectionId("projection.a"),effectiveAssetReference:{kind:"asset-definition-version",id:normalizeAssetId(`asset.${id}`),version:"1.0.0"},displayLabel:"Selected",selectedAt:"2026-05-20T00:00:00.000Z"}],nodes:[{nodeId:createAssetCompositionNodeId(`node.${id}`),targetWorkspaceId:ws,selectedProjection:{targetWorkspaceId:ws,projectionId:createEffectiveAssetProjectionId("projection.a")},role:"processor",status:"planned",requiredCapabilities:[],providedCapabilities:[],diagnostics:[],blockers:[],label:"Node",createdAt:"2026-05-20T00:00:00.000Z",updatedAt:"2026-05-20T00:00:00.000Z"}],relationships:[{relationshipId:createAssetCompositionRelationshipId(`rel.${id}`),targetWorkspaceId:ws,sourceNodeId:createAssetCompositionNodeId(`node.${id}`),targetNodeId:createAssetCompositionNodeId(`node.${id}`),kind:"depends-on",compatibilityStatus:"compatible",diagnostics:[],blockers:[],label:"Link",summary:"summary",createdAt:"2026-05-20T00:00:00.000Z",updatedAt:"2026-05-20T00:00:00.000Z"}],compatibilityDiagnostics:[],blockers:[],planningSummary:{totalNodes:1,compatibleNodeCount:1,blockedNodeCount:0,conflictedNodeCount:0,missingDependencyCount:0,staleProjectionCount:0,unsupportedCount:0,totalRelationships:1,compatibleRelationshipCount:1,blockedRelationshipCount:0,planningReadiness:"ready",safeMetadata:{stage:"planning"}},provenance:[{kind:"plan-created",targetWorkspaceId:ws,operationAt:"2026-05-20T00:00:00.000Z",planId:createAssetCompositionPlanId(id)}],createdAt:"2026-05-20T00:00:00.000Z",updatedAt:"2026-05-20T00:00:00.000Z"});

describe("local asset composition plan persistence",()=>{
 it("saves reads and isolates by workspace", async()=>{const rootDir=await mkdtemp(join(tmpdir(),"acp-")); const repo=createLocalAssetCompositionPlanRepositoryAdapter({rootDir}); await repo.saveAssetCompositionPlanRecord(makePlan(wsA,"plan.1")); await repo.saveAssetCompositionPlanRecord(makePlan(wsB,"plan.1","blocked")); assert.equal((await repo.readAssetCompositionPlanRecord(wsA,createAssetCompositionPlanId("plan.1")))?.targetWorkspaceId,wsA); assert.equal((await repo.readAssetCompositionPlanRecord(wsB,createAssetCompositionPlanId("plan.1")))?.targetWorkspaceId,wsB);});
 it("same plan id in two workspaces does not overwrite", async()=>{const rootDir=await mkdtemp(join(tmpdir(),"acp-")); const repo=createLocalAssetCompositionPlanRepositoryAdapter({rootDir}); await repo.saveAssetCompositionPlanRecord(makePlan(wsA,"plan.same")); await repo.saveAssetCompositionPlanRecord(makePlan(wsB,"plan.same","valid")); assert.equal((await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA})).records.length,1); assert.equal((await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsB,status:"valid"})).records.length,1);});
 it("supports valid status and projection/effective/node/relationship/compatibility filters", async()=>{const rootDir=await mkdtemp(join(tmpdir(),"acp-")); const repo=createLocalAssetCompositionPlanRepositoryAdapter({rootDir}); const p=makePlan(wsA,"plan.f","conflicted"); await repo.saveAssetCompositionPlanRecord(p); assert.equal((await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA,selectedProjectionId:createEffectiveAssetProjectionId("projection.a")})).records.length,1); assert.equal((await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA,effectiveAssetReference:{kind:"asset-definition-version",id:normalizeAssetId("asset.plan.f"),version:"1.0.0"}})).records.length,1); assert.equal((await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA,nodeRole:"processor"})).records.length,1); assert.equal((await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA,relationshipKind:"depends-on",compatibilityStatus:"compatible"})).records.length,1); assert.equal((await repo.listValidDraftBlockedConflictedStaleOrArchivedAssetCompositionPlanRecords(wsA)).length,1);});
 it("rejects unsafe injected fields", async()=>{const rootDir=await mkdtemp(join(tmpdir(),"acp-")); const repo=createLocalAssetCompositionPlanRepositoryAdapter({rootDir}); const bad={...makePlan(wsA,"plan.bad"),name:"prompt secret"}; await assert.rejects(()=>repo.saveAssetCompositionPlanRecord(bad));});
 it("fails safely on manifest schema mismatch", async()=>{const rootDir=await mkdtemp(join(tmpdir(),"acp-")); const repo=createLocalAssetCompositionPlanRepositoryAdapter({rootDir}); await repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA}); const p=join(rootDir,"asset-composition","asset-composition-manifest.json"); const manifest=JSON.parse(await readFile(p,"utf8")); manifest.schemaVersion=99; await writeFile(p,JSON.stringify(manifest)); await assert.rejects(()=>repo.listAssetCompositionPlanRecords({targetWorkspaceId:wsA}), LocalAssetCompositionPlanRecordStoreError);});
});
