import { normalizeAssetId, normalizeAssetReferenceKind } from "../../../../contracts/asset";
import { normalizeAssetCompositionPlanStatus } from "../../../../contracts/asset-composition";
import { createWorkspaceId } from "../../../../contracts/workspace";
import type { WorkspaceAssetCompositionReadModelService } from "../../../../application/services/asset/workspace-asset-composition-read-model.service";
import type { AddProjectionToCompositionPlanUseCase, ArchiveAssetCompositionPlanUseCase, ConnectCompositionNodesUseCase, CreateAssetCompositionPlanUseCase, DisconnectCompositionNodesUseCase, ListAssetCompositionPlansUseCase, ReadAssetCompositionPlanUseCase, RemoveProjectionFromCompositionPlanUseCase, UpdateAssetCompositionPlanUseCase, ValidateAssetCompositionPlanUseCase } from "../../../../application/use-cases/asset-composition";
type Req={params?:Record<string,unknown>;query?:Record<string,unknown>;body?:Record<string,unknown>}; type Res={status:(code:number)=>Res;json:(payload:unknown)=>void}; interface App { get:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; post:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; patch:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; delete:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; }
const S=(v:unknown)=>typeof v==="string"?v.trim():""; const txt=(v:unknown)=>S(v).length>0; const reqWs=(req:Req)=>S(req.params?.workspaceId);
const map=(code:string)=>code==="validation"?400:code==="not-found"?404:code==="conflict"||code==="blocked"?409:code==="unsupported"?501:code==="unavailable"?503:500;
const fail=(res:Res,op:string,code:string,status:number,m:string)=>res.status(status).json({ok:false,error:{operation:op,code,message:m}}); const ok=(res:Res,op:string,value:unknown)=>res.status(200).json({ok:true,operation:op,value});
const mismatch=(a:string,b:unknown)=>txt(b)&&S(b)!==a;
export interface RegisterAssetCompositionApiRoutesDependencies { app:App; createPlan?:CreateAssetCompositionPlanUseCase; updatePlan?:UpdateAssetCompositionPlanUseCase; readPlan?:ReadAssetCompositionPlanUseCase; listPlans?:ListAssetCompositionPlansUseCase; archivePlan?:ArchiveAssetCompositionPlanUseCase; addProjection?:AddProjectionToCompositionPlanUseCase; removeProjection?:RemoveProjectionFromCompositionPlanUseCase; connectNodes?:ConnectCompositionNodesUseCase; disconnectNodes?:DisconnectCompositionNodesUseCase; validatePlan?:ValidateAssetCompositionPlanUseCase; readModel?:WorkspaceAssetCompositionReadModelService; }
export function registerAssetCompositionApiRoutes(d:RegisterAssetCompositionApiRoutesDependencies):void {
const cmd=(method:"post"|"patch",path:string,op:string,uc:any,build:(req:Req,w:string)=>Record<string,unknown>,check?:(req:Req,w:string)=>boolean)=>d.app[method](path,async(req,res)=>{const w=reqWs(req); if(!txt(w)) return fail(res,op,"validation",400,"workspaceId is required."); if(check&&check(req,w)) return fail(res,op,"validation",400,"Request identifiers do not match."); if(!uc) return fail(res,op,"unavailable",503,"Operation unavailable."); try{const r=await uc.execute(build(req,w)); if(r.status==="failure") return fail(res,op,r.failure.kind,map(r.failure.kind),r.failure.code??"Operation failed."); return ok(res,op,r.value);}catch{return fail(res,op,"validation",400,"Invalid request.");}});
cmd("post","/api/asset-composition/workspaces/:workspaceId/plans","asset-composition:create-plan",d.createPlan,(req,w)=>({...(req.body??{}),targetWorkspaceId:createWorkspaceId(w)}),(req,w)=>mismatch(w,req.body?.targetWorkspaceId)||mismatch(w,req.body?.workspaceId));
cmd("patch","/api/asset-composition/workspaces/:workspaceId/plans/:planId","asset-composition:update-plan",d.updatePlan,(req,w)=>({...(req.body??{}),targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId)}),(req,w)=>mismatch(w,req.body?.targetWorkspaceId)||mismatch(w,req.body?.workspaceId)||mismatch(S(req.params?.planId),req.body?.planId));
cmd("post","/api/asset-composition/workspaces/:workspaceId/plans/:planId/projections","asset-composition:add-projection",d.addProjection,(req,w)=>({...(req.body??{}),targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId)}),(req,w)=>mismatch(w,req.body?.targetWorkspaceId)||mismatch(S(req.params?.planId),req.body?.planId)||mismatch(S(req.params?.projectionId),req.body?.projectionId));
cmd("post","/api/asset-composition/workspaces/:workspaceId/plans/:planId/relationships","asset-composition:connect-nodes",d.connectNodes,(req,w)=>({...(req.body??{}),targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId)}),(req,w)=>mismatch(w,req.body?.targetWorkspaceId)||mismatch(S(req.params?.planId),req.body?.planId)||mismatch(S(req.params?.sourceNodeId),req.body?.sourceNodeId)||mismatch(S(req.params?.targetNodeId),req.body?.targetNodeId));
cmd("post","/api/asset-composition/workspaces/:workspaceId/plans/:planId/validate","asset-composition:validate-plan",d.validatePlan,(req,w)=>({targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId)}),(req,w)=>mismatch(w,req.body?.targetWorkspaceId)||mismatch(S(req.params?.planId),req.body?.planId));
if(d.readModel){d.app.get('/api/asset-composition/workspaces/:workspaceId/projections/:projectionId/plans',async(req,res)=>{try{const w=reqWs(req); const projectionId=S(req.params?.projectionId); if(!txt(w)||!txt(projectionId)) return fail(res,'asset-composition:list-plans-for-projection','validation',400,'Invalid request.'); return ok(res,'asset-composition:list-plans-for-projection',await d.readModel!.listPlansForProjection({targetWorkspaceId:createWorkspaceId(w),projectionId}));}catch{return fail(res,'asset-composition:list-plans-for-projection','validation',400,'Invalid request.');}});
d.app.get('/api/asset-composition/workspaces/:workspaceId/effective-assets/:kind/:id/plans',async(req,res)=>{try{const w=reqWs(req); const kind=S(req.params?.kind); const id=S(req.params?.id); if(!txt(w)||!txt(kind)||!txt(id)) return fail(res,'asset-composition:list-plans-for-effective-asset','validation',400,'Invalid request.'); return ok(res,'asset-composition:list-plans-for-effective-asset',await d.readModel!.listPlansForEffectiveAssetReference({targetWorkspaceId:createWorkspaceId(w),effectiveAssetReference:{kind:normalizeAssetReferenceKind(kind),id:normalizeAssetId(id),version:txt(req.query?.version)?S(req.query?.version):undefined}}));}catch{return fail(res,'asset-composition:list-plans-for-effective-asset','validation',400,'Invalid request.');}});
d.app.get('/api/asset-composition/workspaces/:workspaceId/plans-needing-attention',async(req,res)=>{try{const w=reqWs(req); if(!txt(w)) return fail(res,'asset-composition:list-plans-needing-attention','validation',400,'workspaceId is required.'); return ok(res,'asset-composition:list-plans-needing-attention',await d.readModel!.listPlansNeedingAttention({targetWorkspaceId:createWorkspaceId(w)}));}catch{return fail(res,'asset-composition:list-plans-needing-attention','validation',400,'Invalid request.');}});
}
}
