import { normalizeAssetId, normalizeAssetReferenceKind } from "../../../../contracts/asset";
import { normalizeAssetCompositionPlanStatus } from "../../../../contracts/asset-composition";
import { createWorkspaceId } from "../../../../contracts/workspace";
import type { WorkspaceAssetCompositionReadModelService } from "../../../../application/services/asset/workspace-asset-composition-read-model.service";
import type { AddProjectionToCompositionPlanUseCase, ArchiveAssetCompositionPlanUseCase, ConnectCompositionNodesUseCase, CreateAssetCompositionPlanUseCase, DisconnectCompositionNodesUseCase, ListAssetCompositionPlansUseCase, ReadAssetCompositionPlanUseCase, RemoveProjectionFromCompositionPlanUseCase, UpdateAssetCompositionPlanUseCase, ValidateAssetCompositionPlanUseCase } from "../../../../application/use-cases/asset-composition";

type Req={params?:Record<string,unknown>;query?:Record<string,unknown>;body?:Record<string,unknown>}; type Res={status:(code:number)=>Res;json:(payload:unknown)=>void}; interface App { get:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; post:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; patch:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; delete:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; }
const S=(v:unknown)=>typeof v==="string"?v.trim():""; const txt=(v:unknown)=>S(v).length>0; const reqWs=(req:Req)=>S(req.params?.workspaceId);
const map=(code:string)=>code==="validation"?400:code==="not-found"?404:code==="conflict"||code==="blocked"?409:code==="unsupported"?501:code==="unavailable"?503:500;
const fail=(res:Res,op:string,code:string,status:number,m:string)=>res.status(status).json({ok:false,error:{operation:op,code,message:m}}); const ok=(res:Res,op:string,value:unknown)=>res.status(200).json({ok:true,operation:op,value});
export interface RegisterAssetCompositionApiRoutesDependencies { app:App; createPlan?:CreateAssetCompositionPlanUseCase; updatePlan?:UpdateAssetCompositionPlanUseCase; readPlan?:ReadAssetCompositionPlanUseCase; listPlans?:ListAssetCompositionPlansUseCase; archivePlan?:ArchiveAssetCompositionPlanUseCase; addProjection?:AddProjectionToCompositionPlanUseCase; removeProjection?:RemoveProjectionFromCompositionPlanUseCase; connectNodes?:ConnectCompositionNodesUseCase; disconnectNodes?:DisconnectCompositionNodesUseCase; validatePlan?:ValidateAssetCompositionPlanUseCase; readModel?:WorkspaceAssetCompositionReadModelService; }
export function registerAssetCompositionApiRoutes(d:RegisterAssetCompositionApiRoutesDependencies):void {
const cmd=(method:"post"|"patch",path:string,op:string,uc:any,build:(req:Req,w:string)=>Record<string,unknown>)=>d.app[method](path,async(req,res)=>{const w=reqWs(req); if(!txt(w)) return fail(res,op,"validation",400,"workspaceId is required."); if(!uc) return fail(res,op,"unavailable",503,"Operation unavailable."); try{const r=await uc.execute(build(req,w)); if(r.status==="failure") return fail(res,op,r.failure.kind,map(r.failure.kind),"Operation failed."); return ok(res,op,r.value);}catch{return fail(res,op,"validation",400,"Invalid request.");}});
cmd("post","/api/asset-composition/workspaces/:workspaceId/plans","asset-composition:create-plan",d.createPlan,(req,w)=>({...(req.body??{}),targetWorkspaceId:createWorkspaceId(w)}));
cmd("patch","/api/asset-composition/workspaces/:workspaceId/plans/:planId","asset-composition:update-plan",d.updatePlan,(req,w)=>({...(req.body??{}),targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId)}));
cmd("post","/api/asset-composition/workspaces/:workspaceId/plans/:planId/archive","asset-composition:archive-plan",d.archivePlan,(req,w)=>({targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId)}));
cmd("post","/api/asset-composition/workspaces/:workspaceId/plans/:planId/projections","asset-composition:add-projection",d.addProjection,(req,w)=>({...(req.body??{}),targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId)}));
cmd("post","/api/asset-composition/workspaces/:workspaceId/plans/:planId/relationships","asset-composition:connect-nodes",d.connectNodes,(req,w)=>({...(req.body??{}),targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId)}));
cmd("post","/api/asset-composition/workspaces/:workspaceId/plans/:planId/validate","asset-composition:validate-plan",d.validatePlan,(req,w)=>({targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId)}));
 d.app.get('/api/asset-composition/workspaces/:workspaceId/plans',async(req,res)=>{const w=reqWs(req); if(!txt(w)||!d.listPlans) return fail(res,'asset-composition:list-plans',txt(w)?'unavailable':'validation',txt(w)?503:400,'Invalid request.'); try{const r=await d.listPlans.execute({targetWorkspaceId:createWorkspaceId(w),status:txt(req.query?.status)?normalizeAssetCompositionPlanStatus(S(req.query?.status)):undefined,text:txt(req.query?.text)?S(req.query?.text):undefined,limit:txt(req.query?.limit)?Number(S(req.query?.limit)):undefined,cursor:txt(req.query?.cursor)?S(req.query?.cursor):undefined}); if(r.status==='failure') return fail(res,'asset-composition:list-plans',r.failure.kind,map(r.failure.kind),'Operation failed.'); return ok(res,'asset-composition:list-plans',r.value);}catch{return fail(res,'asset-composition:list-plans','validation',400,'Invalid request.');}});
 d.app.get('/api/asset-composition/workspaces/:workspaceId/plans/:planId',async(req,res)=>{const w=reqWs(req); if(!txt(w)||!d.readPlan) return fail(res,'asset-composition:read-plan',txt(w)?'unavailable':'validation',txt(w)?503:400,'Invalid request.'); const r=await d.readPlan.execute({targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId) as never}); if(r.status==='failure') return fail(res,'asset-composition:read-plan',r.failure.kind,map(r.failure.kind),'Operation failed.'); return ok(res,'asset-composition:read-plan',r.value);});
 d.app.delete('/api/asset-composition/workspaces/:workspaceId/plans/:planId/projections/:projectionId',async(req,res)=>{const w=reqWs(req); if(!txt(w)||!d.removeProjection) return fail(res,'asset-composition:remove-projection',txt(w)?'unavailable':'validation',txt(w)?503:400,'Invalid request.'); const r=await d.removeProjection.execute({targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId) as never,projectionId:S(req.params?.projectionId) as never}); if(r.status==='failure') return fail(res,'asset-composition:remove-projection',r.failure.kind,map(r.failure.kind),'Operation failed.'); return ok(res,'asset-composition:remove-projection',r.value);});
 d.app.delete('/api/asset-composition/workspaces/:workspaceId/plans/:planId/relationships/:relationshipId',async(req,res)=>{const w=reqWs(req); if(!txt(w)||!d.disconnectNodes) return fail(res,'asset-composition:disconnect-nodes',txt(w)?'unavailable':'validation',txt(w)?503:400,'Invalid request.'); const r=await d.disconnectNodes.execute({targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId) as never,relationshipId:S(req.params?.relationshipId) as never}); if(r.status==='failure') return fail(res,'asset-composition:disconnect-nodes',r.failure.kind,map(r.failure.kind),'Operation failed.'); return ok(res,'asset-composition:disconnect-nodes',r.value);});
 if(d.readModel){d.app.get('/api/asset-composition/workspaces/:workspaceId/plan-summaries',async(req,res)=>{const w=reqWs(req); if(!txt(w)) return fail(res,'asset-composition:list-plan-summaries','validation',400,'workspaceId is required.'); return ok(res,'asset-composition:list-plan-summaries',await d.readModel!.listCompositionPlanSummaries({targetWorkspaceId:createWorkspaceId(w)}));});
 d.app.get('/api/asset-composition/workspaces/:workspaceId/plan-details/:planId',async(req,res)=>{const w=reqWs(req); if(!txt(w)) return fail(res,'asset-composition:read-plan-detail','validation',400,'workspaceId is required.'); const v=await d.readModel!.readCompositionPlanDetail({targetWorkspaceId:createWorkspaceId(w),planId:S(req.params?.planId)}); return v?ok(res,'asset-composition:read-plan-detail',v):fail(res,'asset-composition:read-plan-detail','not-found',404,'Plan not found.');});
 d.app.get('/api/asset-composition/workspaces/:workspaceId/projections/:projectionId/plans',async(req,res)=>ok(res,'asset-composition:list-plans-for-projection',await d.readModel!.listPlansForProjection({targetWorkspaceId:createWorkspaceId(reqWs(req)),projectionId:S(req.params?.projectionId)})));
 d.app.get('/api/asset-composition/workspaces/:workspaceId/effective-assets/:kind/:id/plans',async(req,res)=>ok(res,'asset-composition:list-plans-for-effective-asset',await d.readModel!.listPlansForEffectiveAssetReference({targetWorkspaceId:createWorkspaceId(reqWs(req)),effectiveAssetReference:{kind:normalizeAssetReferenceKind(S(req.params?.kind)),id:normalizeAssetId(S(req.params?.id)),version:txt(req.query?.version)?S(req.query?.version):undefined}})));
 d.app.get('/api/asset-composition/workspaces/:workspaceId/plans-needing-attention',async(req,res)=>ok(res,'asset-composition:list-plans-needing-attention',await d.readModel!.listPlansNeedingAttention({targetWorkspaceId:createWorkspaceId(reqWs(req))})));
 }
}
