import type { EffectiveAssetProjectionRepositoryPort } from "../../../../application/ports/effective-asset-projections";
import type { WorkspaceEffectiveAssetProjectionReadModelService } from "../../../../application/services/asset/workspace-effective-asset-projection-read-model.service";
import type { CreateAuthoredAssetEffectiveProjectionUseCase, CreateOverrideEffectiveProjectionUseCase, PreviewDraftEffectiveAssetProjectionUseCase, RefreshAuthoredAssetEffectiveProjectionUseCase, RefreshOverrideEffectiveProjectionUseCase } from "../../../../application/use-cases/effective-asset-projections";
type Req={params?:Record<string,unknown>;query?:Record<string,unknown>;body?:Record<string,unknown>}; type Res={status:(code:number)=>Res;json:(payload:unknown)=>void}; interface App { get:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; post:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; }
const S=(v:unknown)=>typeof v==="string"?v.trim():""; const txt=(v:unknown)=>S(v).length>0; const map=(code:string)=>code==="validation"?400:code==="not-found"?404:code==="conflict"||code==="blocked"?409:code==="unsupported"?501:code==="unavailable"?503:500; const reqWs=(req:Req)=>S(req.params?.workspaceId); const fail=(res:Res,op:string,code:string,status:number,m:string)=>res.status(status).json({ok:false,error:{operation:op,code,message:m}}); const ok=(res:Res,op:string,value:unknown)=>res.status(200).json({ok:true,operation:op,value});
export interface RegisterEffectiveAssetProjectionApiRoutesDependencies {app:App; createAuthored?:CreateAuthoredAssetEffectiveProjectionUseCase; refreshAuthored?:RefreshAuthoredAssetEffectiveProjectionUseCase; previewDraft?:PreviewDraftEffectiveAssetProjectionUseCase; createOverride?:CreateOverrideEffectiveProjectionUseCase; refreshOverride?:RefreshOverrideEffectiveProjectionUseCase; readModel?:WorkspaceEffectiveAssetProjectionReadModelService; projectionRepository?:EffectiveAssetProjectionRepositoryPort;}
export function registerEffectiveAssetProjectionApiRoutes(d:RegisterEffectiveAssetProjectionApiRoutesDependencies):void {
const cmd=(path:string,op:string,wf:string,uc:any)=>d.app.post(path,async(req,res)=>{const w=reqWs(req); if(!txt(w)) return fail(res,op,"validation",400,"workspaceId is required."); if(req.body?.[wf] && S(req.body[wf])!==w) return fail(res,op,"validation",400,"workspace route/body mismatch."); if(!uc) return fail(res,op,"unavailable",503,"Operation unavailable."); try{const r=await uc.execute({...(req.body??{}),[wf]:w}); if(r.kind==="failure") return fail(res,op,r.failure.code,map(r.failure.code),"Operation failed."); return ok(res,op,r.value);}catch{return fail(res,op,"internal",500,"Operation failed.");}});
cmd("/api/effective-asset-projections/workspaces/:workspaceId/authored","effective-asset-projections.create-authored","targetWorkspaceId",d.createAuthored); cmd("/api/effective-asset-projections/workspaces/:workspaceId/drafts/preview","effective-asset-projections.preview-draft","targetWorkspaceId",d.previewDraft); cmd("/api/effective-asset-projections/workspaces/:workspaceId/overrides","effective-asset-projections.create-override","targetWorkspaceId",d.createOverride);
d.app.post("/api/effective-asset-projections/workspaces/:workspaceId/authored/:projectionId/refresh",async(req,res)=>{const w=reqWs(req); const p=S(req.params?.projectionId); if(!txt(w)||!txt(p)) return fail(res,"effective-asset-projections.refresh-authored","validation",400,"workspaceId and projectionId are required."); if(!d.refreshAuthored) return fail(res,"effective-asset-projections.refresh-authored","unavailable",503,"Operation unavailable."); const r=await d.refreshAuthored.execute({...(req.body??{}),targetWorkspaceId:w,projectionId:p} as any); if(r.kind==="failure") return fail(res,"effective-asset-projections.refresh-authored",r.failure.code,map(r.failure.code),"Operation failed."); return ok(res,"effective-asset-projections.refresh-authored",r.value);});
d.app.post("/api/effective-asset-projections/workspaces/:workspaceId/overrides/:projectionId/refresh",async(req,res)=>{const w=reqWs(req); const p=S(req.params?.projectionId); if(!txt(w)||!txt(p)) return fail(res,"effective-asset-projections.refresh-override","validation",400,"workspaceId and projectionId are required."); if(!d.refreshOverride) return fail(res,"effective-asset-projections.refresh-override","unavailable",503,"Operation unavailable."); const r=await d.refreshOverride.execute({...(req.body??{}),targetWorkspaceId:w,projectionId:p} as any); if(r.kind==="failure") return fail(res,"effective-asset-projections.refresh-override",r.failure.code,map(r.failure.code),"Operation failed."); return ok(res,"effective-asset-projections.refresh-override",r.value);});
d.app.get("/api/effective-asset-projections/workspaces/:workspaceId/projections",async(req,res)=>{const w=reqWs(req); if(!txt(w)) return fail(res,"effective-asset-projections.list","validation",400,"workspaceId is required."); if(!d.readModel) return fail(res,"effective-asset-projections.list","unavailable",503,"Read unavailable."); return ok(res,"effective-asset-projections.list",await d.readModel.listByWorkspace({targetWorkspaceId:w as never,limit:25,cursor:S(req.query?.cursor)||undefined,status:txt(req.query?.status)?S(req.query?.status) as never:undefined,sourceKind:txt(req.query?.sourceKind)?S(req.query?.sourceKind) as never:undefined,policy:txt(req.query?.policy)?S(req.query?.policy) as never:undefined}));});
d.app.get("/api/effective-asset-projections/workspaces/:workspaceId/projections/:projectionId",async(req,res)=>{const w=reqWs(req); const p=S(req.params?.projectionId); if(!txt(w)||!txt(p)) return fail(res,"effective-asset-projections.read","validation",400,"workspaceId and projectionId are required."); if(!d.readModel) return fail(res,"effective-asset-projections.read","unavailable",503,"Read unavailable."); const v=await d.readModel.readByProjectionId(w as never,p); if(!v) return fail(res,"effective-asset-projections.read","not-found",404,"Projection not found."); return ok(res,"effective-asset-projections.read",v);});
}
