import type { AssetReferenceKind } from "../../../../contracts/asset";
import type { EffectiveAssetProjectionPolicy, EffectiveAssetProjectionSourceKind, EffectiveAssetProjectionStatus } from "../../../../contracts/effective-asset-projections";
import type { EffectiveAssetProjectionRepositoryPort } from "../../../../application/ports/effective-asset-projections";
import type { WorkspaceEffectiveAssetProjectionReadModelService } from "../../../../application/services/asset/workspace-effective-asset-projection-read-model.service";
import type { CreateAuthoredAssetEffectiveProjectionUseCase, CreateOverrideEffectiveProjectionUseCase, PreviewDraftEffectiveAssetProjectionUseCase, RefreshAuthoredAssetEffectiveProjectionUseCase, RefreshOverrideEffectiveProjectionUseCase } from "../../../../application/use-cases/effective-asset-projections";
type Req={params?:Record<string,unknown>;query?:Record<string,unknown>;body?:Record<string,unknown>}; type Res={status:(code:number)=>Res;json:(payload:unknown)=>void}; interface App { get:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; post:(p:string,h:(req:Req,res:Res)=>Promise<void>|void)=>void; }
const S=(v:unknown)=>typeof v==="string"?v.trim():""; const txt=(v:unknown)=>S(v).length>0; const map=(code:string)=>code==="validation"?400:code==="not-found"?404:code==="conflict"||code==="blocked"?409:code==="unsupported"?501:code==="unavailable"?503:500; const reqWs=(req:Req)=>S(req.params?.workspaceId); const fail=(res:Res,op:string,code:string,status:number,m:string)=>res.status(status).json({ok:false,error:{operation:op,code,message:m}}); const ok=(res:Res,op:string,value:unknown)=>res.status(200).json({ok:true,operation:op,value});
const statuses: readonly EffectiveAssetProjectionStatus[] = ["ready","draft-only","blocked","conflicted","invalid","source-missing","unsupported","stale","disabled"];
const sourceKinds: readonly EffectiveAssetProjectionSourceKind[]=["workspace-authored","workspace-override","user-library-link","user-library-copy","pack-import"];
const policies: readonly EffectiveAssetProjectionPolicy[]=["safe-fields-only","safe-fields-with-overrides","strict-safe-readiness"];
const kinds: readonly AssetReferenceKind[]=["asset-definition","asset-instance"];
const asOne=<T extends string>(v:unknown, allowed: readonly T[])=>{const s=S(v);return (allowed as readonly string[]).includes(s)?s as T:undefined;};
const asLimit=(v:unknown)=>{const n=Number(S(v)); return Number.isInteger(n)&&n>0&&n<=200?n:25;};
export interface RegisterEffectiveAssetProjectionApiRoutesDependencies {app:App; createAuthored?:CreateAuthoredAssetEffectiveProjectionUseCase; refreshAuthored?:RefreshAuthoredAssetEffectiveProjectionUseCase; previewDraft?:PreviewDraftEffectiveAssetProjectionUseCase; createOverride?:CreateOverrideEffectiveProjectionUseCase; refreshOverride?:RefreshOverrideEffectiveProjectionUseCase; readModel?:WorkspaceEffectiveAssetProjectionReadModelService; projectionRepository?:EffectiveAssetProjectionRepositoryPort;}
export function registerEffectiveAssetProjectionApiRoutes(d:RegisterEffectiveAssetProjectionApiRoutesDependencies):void {
const cmd=(path:string,op:string,wf:string,uc:any)=>d.app.post(path,async(req,res)=>{const w=reqWs(req); if(!txt(w)) return fail(res,op,"validation",400,"workspaceId is required."); if(req.body?.[wf] && S(req.body[wf])!==w) return fail(res,op,"validation",400,"workspace route/body mismatch."); if(!uc) return fail(res,op,"unavailable",503,"Operation unavailable."); try{const r=await uc.execute({...(req.body??{}),[wf]:w}); if(r.kind==="failure") return fail(res,op,r.failure.code,map(r.failure.code),"Operation failed."); return ok(res,op,r.value);}catch{return fail(res,op,"internal",500,"Operation failed.");}});
cmd("/api/effective-asset-projections/workspaces/:workspaceId/authored","effective-asset-projections.create-authored","targetWorkspaceId",d.createAuthored); cmd("/api/effective-asset-projections/workspaces/:workspaceId/drafts/preview","effective-asset-projections.preview-draft","targetWorkspaceId",d.previewDraft); cmd("/api/effective-asset-projections/workspaces/:workspaceId/overrides","effective-asset-projections.create-override","targetWorkspaceId",d.createOverride);
d.app.post("/api/effective-asset-projections/workspaces/:workspaceId/authored/:projectionId/refresh",async(req,res)=>{const w=reqWs(req); const p=S(req.params?.projectionId); if(!txt(w)||!txt(p)) return fail(res,"effective-asset-projections.refresh-authored","validation",400,"workspaceId and projectionId are required."); if(!d.refreshAuthored) return fail(res,"effective-asset-projections.refresh-authored","unavailable",503,"Operation unavailable."); const r=await d.refreshAuthored.execute({...(req.body??{}),targetWorkspaceId:w,projectionId:p} as never); if(r.kind==="failure") return fail(res,"effective-asset-projections.refresh-authored",r.failure.code,map(r.failure.code),"Operation failed."); return ok(res,"effective-asset-projections.refresh-authored",r.value);});
d.app.get("/api/effective-asset-projections/workspaces/:workspaceId/projections",async(req,res)=>{const w=reqWs(req); if(!txt(w)||!d.readModel) return fail(res,"effective-asset-projections.list",txt(w)?"unavailable":"validation",txt(w)?503:400,txt(w)?"Read unavailable.":"workspaceId is required."); return ok(res,"effective-asset-projections.list",await d.readModel.listByWorkspace({targetWorkspaceId:w as never,limit:asLimit(req.query?.limit),cursor:S(req.query?.cursor)||undefined,status:asOne(req.query?.status,statuses),sourceKind:asOne(req.query?.sourceKind,sourceKinds),policy:asOne(req.query?.policy,policies)}));});
d.app.get("/api/effective-asset-projections/workspaces/:workspaceId/projections/:projectionId",async(req,res)=>{const w=reqWs(req); const p=S(req.params?.projectionId); if(!txt(w)||!txt(p)||!d.readModel) return fail(res,"effective-asset-projections.read",(!txt(w)||!txt(p))?"validation":"unavailable",(!txt(w)||!txt(p))?400:503,(!txt(w)||!txt(p))?"workspaceId and projectionId are required.":"Read unavailable."); const v=await d.readModel.readByProjectionId(w as never,p); if(!v) return fail(res,"effective-asset-projections.read","not-found",404,"Projection not found."); return ok(res,"effective-asset-projections.read",v);});
d.app.get("/api/effective-asset-projections/workspaces/:workspaceId/projections/by-effective-reference",async(req,res)=>{const w=reqWs(req); const kind=asOne(req.query?.kind,kinds); const id=S(req.query?.id); const version=S(req.query?.version)||undefined; if(!txt(w)||!kind||!txt(id)) return fail(res,"effective-asset-projections.read-by-effective-reference","validation",400,"workspaceId, kind, and id are required."); if(!d.readModel) return fail(res,"effective-asset-projections.read-by-effective-reference","unavailable",503,"Read unavailable."); const v=await d.readModel.readByEffectiveAssetReference(w as never,{kind,id,version}); if(!v) return fail(res,"effective-asset-projections.read-by-effective-reference","not-found",404,"Projection not found."); return ok(res,"effective-asset-projections.read-by-effective-reference",v);});
d.app.get("/api/effective-asset-projections/workspaces/:workspaceId/projections/blocked",async(req,res)=>{const w=reqWs(req); if(!txt(w)||!d.projectionRepository) return fail(res,"effective-asset-projections.list-blocked",txt(w)?"unavailable":"validation",txt(w)?503:400,txt(w)?"Read unavailable.":"workspaceId is required."); const records=await d.projectionRepository.listBlockedConflictedOrStaleEffectiveAssetProjectionRecords(w as never); return ok(res,"effective-asset-projections.list-blocked",{summaries:records.map((r)=>({projectionId:r.projectionId,status:r.status,effectiveAssetReference:r.effectiveAssetReference,projectedFields:r.projectedFields,diagnostics:r.diagnostics,blockers:r.blockers}))});});
}
