#!/usr/bin/env python3
"""Maintain an approval-gated implementation roadmap and durable Markdown report."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit


SCHEMA_VERSION = 1
MAX_JSON_BYTES = 1024 * 1024
IDENTIFIER = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
INCREMENT_DONE = {"completed", "implemented-pending-qualification"}
GENERATED_NOTICE = (
    "<!-- Generated by manage-implementation-roadmaps. "
    "Use roadmap.py; do not edit manually. -->"
)


class RoadmapError(ValueError):
    """Raised when roadmap input or a state transition is invalid."""


def now_utc() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=True, separators=(",", ":"), sort_keys=True)


def fingerprint(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def require_object(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise RoadmapError(f"{label} must be a JSON object.")
    return value


def require_list(value: Any, label: str, *, minimum: int = 0) -> list[Any]:
    if not isinstance(value, list) or len(value) < minimum:
        raise RoadmapError(f"{label} must be an array with at least {minimum} item(s).")
    return value


def require_string(value: Any, label: str, *, maximum: int = 4000) -> str:
    if not isinstance(value, str) or not value.strip():
        raise RoadmapError(f"{label} must be a non-empty string.")
    normalized = value.strip()
    if len(normalized) > maximum:
        raise RoadmapError(f"{label} exceeds the {maximum}-character limit.")
    if any(
        (ord(character) < 32 and character not in {"\n", "\t"})
        or ord(character) == 127
        for character in normalized
    ):
        raise RoadmapError(f"{label} contains unsupported control characters.")
    return normalized


def require_identifier(value: Any, label: str) -> str:
    identifier = require_string(value, label, maximum=64)
    if not IDENTIFIER.fullmatch(identifier):
        raise RoadmapError(
            f"{label} must use lowercase letters, numbers, and single hyphens."
        )
    return identifier


def require_string_list(
    value: Any, label: str, *, minimum: int = 0, maximum_items: int = 100
) -> list[str]:
    items = require_list(value, label, minimum=minimum)
    if len(items) > maximum_items:
        raise RoadmapError(f"{label} exceeds the {maximum_items}-item limit.")
    return [require_string(item, f"{label}[{index}]") for index, item in enumerate(items)]


def reject_unknown(value: dict[str, Any], allowed: set[str], label: str) -> None:
    unknown = sorted(set(value) - allowed)
    if unknown:
        raise RoadmapError(f"{label} contains unsupported field(s): {', '.join(unknown)}.")


def read_json(path: Path, label: str) -> dict[str, Any]:
    try:
        raw = path.read_bytes()
    except OSError as error:
        raise RoadmapError(f"Unable to read {label}: {error}") from error
    if len(raw) > MAX_JSON_BYTES:
        raise RoadmapError(f"{label} exceeds the {MAX_JSON_BYTES}-byte limit.")
    try:
        return require_object(json.loads(raw.decode("utf-8")), label)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise RoadmapError(f"{label} must be valid UTF-8 JSON: {error}") from error


def safe_relative_path(repo: Path, value: Any, label: str) -> str:
    raw = require_string(value, label, maximum=500)
    candidate = (repo / raw).resolve()
    try:
        relative = candidate.relative_to(repo)
    except ValueError as error:
        raise RoadmapError(f"{label} must stay inside the repository.") from error
    if relative == Path("."):
        raise RoadmapError(f"{label} must name a file inside the repository.")
    return relative.as_posix()


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8", newline="\n")
        os.replace(temporary, path)
    except OSError as error:
        raise RoadmapError(f"Unable to write {path.name}: {error}") from error
    finally:
        try:
            temporary.unlink(missing_ok=True)
        except OSError:
            pass


def normalize_text(value: str) -> str:
    return value.replace("\r\n", "\n")


def markdown(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def bullet_lines(values: list[str], empty: str = "None.") -> list[str]:
    return [f"- {value}" for value in values] if values else [empty]


def relative_markdown_link(from_path: str, to_path: str) -> str:
    relative = os.path.relpath(to_path, start=str(Path(from_path).parent))
    return Path(relative).as_posix()


def decision_fingerprint(decision: dict[str, Any]) -> str:
    return fingerprint(
        {
            "id": decision["id"],
            "title": decision["title"],
            "question": decision["question"],
            "context": decision["context"],
            "options": decision["options"],
        }
    )


def roadmap_fingerprint(state: dict[str, Any]) -> str:
    decisions = [
        {
            "id": item["id"],
            "proposalFingerprint": item["proposalFingerprint"],
            "selectedOptionId": item.get("selectedOptionId"),
        }
        for item in state["decisions"]
    ]
    definitions = []
    runtime_fields = {
        "status",
        "startedAt",
        "completedAt",
        "research",
        "plan",
        "completedChunks",
        "completionSummary",
        "pendingCriteria",
    }
    for increment in state["increments"]:
        definitions.append(
            {key: value for key, value in increment.items() if key not in runtime_fields}
        )
    return fingerprint(
        {
            "objective": state["objective"],
            "decisions": decisions,
            "increments": definitions,
        }
    )


def approved_decisions_are_current(state: dict[str, Any]) -> bool:
    return all(
        item.get("status") == "approved"
        and item.get("approvedFingerprint") == item.get("proposalFingerprint")
        for item in state["decisions"]
    )


def approval_is_current(state: dict[str, Any]) -> bool:
    approval = state.get("roadmapApproval")
    return bool(
        approval
        and approved_decisions_are_current(state)
        and approval.get("fingerprint") == roadmap_fingerprint(state)
    )


def find_increment(state: dict[str, Any], increment_id: str) -> dict[str, Any]:
    for increment in state["increments"]:
        if increment["id"] == increment_id:
            return increment
    raise RoadmapError(f"Unknown increment id: {increment_id}.")


def current_increment(state: dict[str, Any]) -> dict[str, Any]:
    increment_id = state.get("currentIncrementId")
    if not increment_id:
        raise RoadmapError("No increment is currently active.")
    return find_increment(state, increment_id)


def latest_criterion_evidence(
    state: dict[str, Any], increment_id: str, criterion_id: str
) -> dict[str, Any] | None:
    for item in reversed(state["evidence"]):
        if item["incrementId"] == increment_id and item["criterionId"] == criterion_id:
            return item
    return None


def validate_source(value: Any, label: str) -> dict[str, str]:
    source = require_object(value, label)
    reject_unknown(source, {"title", "url", "note"}, label)
    result = {"title": require_string(source.get("title"), f"{label}.title")}
    if source.get("url") is not None:
        link = require_string(source["url"], f"{label}.url", maximum=1000)
        parsed = urlsplit(link)
        if parsed.scheme and parsed.scheme not in {"http", "https"}:
            raise RoadmapError(f"{label}.url uses an unsupported link scheme.")
        if parsed.scheme in {"http", "https"} and not parsed.netloc:
            raise RoadmapError(f"{label}.url must include a host.")
        if (
            (not parsed.scheme and link.startswith(("/", "\\", "//")))
            or "\\" in link
            or any(character.isspace() or character in {'<', '>', '"'} for character in link)
        ):
            raise RoadmapError(
                f"{label}.url must be a safe HTTP(S) or repository-relative link."
            )
        result["url"] = link
    if source.get("note") is not None:
        result["note"] = require_string(source["note"], f"{label}.note")
    return result


def validate_option(value: Any, label: str) -> dict[str, Any]:
    option = require_object(value, label)
    reject_unknown(
        option,
        {"id", "label", "summary", "tradeoffs", "consequences", "recommended"},
        label,
    )
    recommended = option.get("recommended", False)
    if not isinstance(recommended, bool):
        raise RoadmapError(f"{label}.recommended must be a boolean.")
    return {
        "id": require_identifier(option.get("id"), f"{label}.id"),
        "label": require_string(option.get("label"), f"{label}.label", maximum=160),
        "summary": require_string(option.get("summary"), f"{label}.summary"),
        "tradeoffs": require_string_list(
            option.get("tradeoffs", []), f"{label}.tradeoffs"
        ),
        "consequences": require_string_list(
            option.get("consequences", []), f"{label}.consequences"
        ),
        "recommended": recommended,
    }


def validate_criterion(value: Any, label: str) -> dict[str, str]:
    criterion = require_object(value, label)
    reject_unknown(criterion, {"id", "description", "qualification"}, label)
    qualification = criterion.get("qualification", "local")
    if qualification not in {"local", "controlled-environment"}:
        raise RoadmapError(
            f"{label}.qualification must be local or controlled-environment."
        )
    return {
        "id": require_identifier(criterion.get("id"), f"{label}.id"),
        "description": require_string(
            criterion.get("description"), f"{label}.description"
        ),
        "qualification": qualification,
    }


def validate_work_package(value: Any, label: str) -> dict[str, str]:
    package = require_object(value, label)
    reject_unknown(package, {"id", "title", "outcome"}, label)
    return {
        "id": require_identifier(package.get("id"), f"{label}.id"),
        "title": require_string(package.get("title"), f"{label}.title", maximum=200),
        "outcome": require_string(package.get("outcome"), f"{label}.outcome"),
    }


def validate_increment(value: Any, label: str) -> dict[str, Any]:
    item = require_object(value, label)
    reject_unknown(
        item,
        {
            "id",
            "number",
            "title",
            "objective",
            "dependsOn",
            "workPackages",
            "deliverables",
            "acceptanceCriteria",
            "verification",
            "rollback",
            "excluded",
            "allowPendingQualification",
        },
        label,
    )
    number = item.get("number")
    if not isinstance(number, int) or isinstance(number, bool) or number < 0:
        raise RoadmapError(f"{label}.number must be a non-negative integer.")
    allow_pending = item.get("allowPendingQualification", False)
    if not isinstance(allow_pending, bool):
        raise RoadmapError(f"{label}.allowPendingQualification must be a boolean.")
    criteria = [
        validate_criterion(entry, f"{label}.acceptanceCriteria[{index}]")
        for index, entry in enumerate(
            require_list(
                item.get("acceptanceCriteria"),
                f"{label}.acceptanceCriteria",
                minimum=1,
            )
        )
    ]
    criterion_ids = [entry["id"] for entry in criteria]
    if len(criterion_ids) != len(set(criterion_ids)):
        raise RoadmapError(f"{label}.acceptanceCriteria contains duplicate ids.")
    return {
        "id": require_identifier(item.get("id"), f"{label}.id"),
        "number": number,
        "title": require_string(item.get("title"), f"{label}.title", maximum=200),
        "objective": require_string(item.get("objective"), f"{label}.objective"),
        "dependsOn": [
            require_identifier(entry, f"{label}.dependsOn[{index}]")
            for index, entry in enumerate(
                require_list(item.get("dependsOn", []), f"{label}.dependsOn")
            )
        ],
        "workPackages": [
            validate_work_package(entry, f"{label}.workPackages[{index}]")
            for index, entry in enumerate(
                require_list(item.get("workPackages", []), f"{label}.workPackages")
            )
        ],
        "deliverables": require_string_list(
            item.get("deliverables"), f"{label}.deliverables", minimum=1
        ),
        "acceptanceCriteria": criteria,
        "verification": require_string_list(
            item.get("verification"), f"{label}.verification", minimum=1
        ),
        "rollback": require_string(item.get("rollback"), f"{label}.rollback"),
        "excluded": require_string_list(item.get("excluded", []), f"{label}.excluded"),
        "allowPendingQualification": allow_pending,
        "status": "pending",
        "startedAt": None,
        "completedAt": None,
        "research": [],
        "plan": None,
        "completedChunks": [],
    }


def validate_plan(value: Any, increment: dict[str, Any]) -> dict[str, Any]:
    plan = require_object(value, "event.plan")
    reject_unknown(
        plan,
        {
            "summary",
            "steps",
            "chunks",
            "tests",
            "documentation",
            "rollback",
            "assumptions",
        },
        "event.plan",
    )
    criterion_ids = {item["id"] for item in increment["acceptanceCriteria"]}
    chunks = []
    for index, value in enumerate(
        require_list(plan.get("chunks"), "event.plan.chunks", minimum=1)
    ):
        label = f"event.plan.chunks[{index}]"
        chunk = require_object(value, label)
        reject_unknown(chunk, {"id", "title", "outcome", "criteriaIds"}, label)
        covered = [
            require_identifier(item, f"{label}.criteriaIds[{item_index}]")
            for item_index, item in enumerate(
                require_list(chunk.get("criteriaIds"), f"{label}.criteriaIds", minimum=1)
            )
        ]
        unknown = sorted(set(covered) - criterion_ids)
        if unknown:
            raise RoadmapError(
                f"{label}.criteriaIds references unknown criteria: {', '.join(unknown)}."
            )
        chunks.append(
            {
                "id": require_identifier(chunk.get("id"), f"{label}.id"),
                "title": require_string(
                    chunk.get("title"), f"{label}.title", maximum=200
                ),
                "outcome": require_string(chunk.get("outcome"), f"{label}.outcome"),
                "criteriaIds": covered,
            }
        )
    chunk_ids = [item["id"] for item in chunks]
    if len(chunk_ids) != len(set(chunk_ids)):
        raise RoadmapError("event.plan.chunks contains duplicate ids.")
    uncovered = sorted(
        criterion_ids - {criterion for chunk in chunks for criterion in chunk["criteriaIds"]}
    )
    if uncovered:
        raise RoadmapError(
            "Every acceptance criterion must be assigned to a planned chunk; "
            f"missing: {', '.join(uncovered)}."
        )
    return {
        "summary": require_string(plan.get("summary"), "event.plan.summary"),
        "steps": require_string_list(
            plan.get("steps"), "event.plan.steps", minimum=1
        ),
        "chunks": chunks,
        "tests": require_string_list(plan.get("tests"), "event.plan.tests", minimum=1),
        "documentation": require_string_list(
            plan.get("documentation"),
            "event.plan.documentation",
            minimum=1,
        ),
        "rollback": require_string(plan.get("rollback"), "event.plan.rollback"),
        "assumptions": require_string_list(
            plan.get("assumptions", []), "event.plan.assumptions"
        ),
    }


def invalidate_roadmap_approval(state: dict[str, Any]) -> None:
    state["roadmapApproval"] = None


def handle_discovery_recorded(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(
        event,
        {"type", "summary", "sources", "constraints", "decisionRequired"},
        "event",
    )
    if state["status"] not in {"discovery", "decision-options", "roadmap-drafting"}:
        raise RoadmapError("Discovery can only be recorded before roadmap review.")
    decision_required = event.get("decisionRequired")
    if not isinstance(decision_required, bool):
        raise RoadmapError("event.decisionRequired must be a boolean.")
    state["discovery"] = {
        "summary": require_string(event.get("summary"), "event.summary"),
        "sources": [
            validate_source(item, f"event.sources[{index}]")
            for index, item in enumerate(
                require_list(event.get("sources", []), "event.sources")
            )
        ],
        "constraints": require_string_list(
            event.get("constraints", []), "event.constraints"
        ),
        "decisionRequired": decision_required,
        "recordedAt": now_utc(),
    }
    state["status"] = "decision-options" if decision_required else "roadmap-drafting"


def handle_decision_proposed(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(event, {"type", "decision"}, "event")
    if not state.get("discovery"):
        raise RoadmapError("Record discovery before proposing a decision.")
    raw = require_object(event.get("decision"), "event.decision")
    reject_unknown(raw, {"id", "title", "question", "context", "options"}, "event.decision")
    options = [
        validate_option(item, f"event.decision.options[{index}]")
        for index, item in enumerate(
            require_list(raw.get("options"), "event.decision.options", minimum=2)
        )
    ]
    if len(options) > 3:
        raise RoadmapError("A decision must present two or three options.")
    option_ids = [item["id"] for item in options]
    if len(option_ids) != len(set(option_ids)):
        raise RoadmapError("Decision option ids must be unique.")
    if sum(1 for item in options if item["recommended"]) != 1:
        raise RoadmapError("Exactly one decision option must be recommended.")
    decision = {
        "id": require_identifier(raw.get("id"), "event.decision.id"),
        "title": require_string(raw.get("title"), "event.decision.title", maximum=200),
        "question": require_string(raw.get("question"), "event.decision.question"),
        "context": require_string(raw.get("context"), "event.decision.context"),
        "options": options,
        "status": "awaiting-approval",
        "selectedOptionId": None,
        "approvedFingerprint": None,
        "approvedAt": None,
    }
    decision["proposalFingerprint"] = decision_fingerprint(decision)
    existing = next(
        (item for item in state["decisions"] if item["id"] == decision["id"]), None
    )
    if existing:
        state["decisions"][state["decisions"].index(existing)] = decision
    else:
        state["decisions"].append(decision)
    invalidate_roadmap_approval(state)
    state["status"] = "decision-approval"


def handle_decision_approved(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(event, {"type", "decisionId", "optionId", "note"}, "event")
    decision_id = require_identifier(event.get("decisionId"), "event.decisionId")
    option_id = require_identifier(event.get("optionId"), "event.optionId")
    decision = next(
        (item for item in state["decisions"] if item["id"] == decision_id), None
    )
    if not decision:
        raise RoadmapError(f"Unknown decision id: {decision_id}.")
    if option_id not in {item["id"] for item in decision["options"]}:
        raise RoadmapError(f"Unknown option id {option_id} for decision {decision_id}.")
    decision["status"] = "approved"
    decision["selectedOptionId"] = option_id
    decision["approvedFingerprint"] = decision["proposalFingerprint"]
    decision["approvedAt"] = now_utc()
    decision["approvalNote"] = (
        require_string(event["note"], "event.note") if event.get("note") else None
    )
    invalidate_roadmap_approval(state)
    state["status"] = (
        "roadmap-drafting" if approved_decisions_are_current(state) else "decision-approval"
    )


def handle_roadmap_defined(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(event, {"type", "increments"}, "event")
    if not state.get("discovery"):
        raise RoadmapError("Record discovery before defining increments.")
    if not approved_decisions_are_current(state):
        raise RoadmapError("Approve every proposed high-level decision first.")
    increments = [
        validate_increment(item, f"event.increments[{index}]")
        for index, item in enumerate(
            require_list(event.get("increments"), "event.increments", minimum=1)
        )
    ]
    ids = [item["id"] for item in increments]
    numbers = [item["number"] for item in increments]
    if len(ids) != len(set(ids)):
        raise RoadmapError("Increment ids must be unique.")
    if sorted(numbers) != list(range(min(numbers), max(numbers) + 1)):
        raise RoadmapError("Increment numbers must be contiguous.")
    by_id = {item["id"]: item for item in increments}
    for item in increments:
        for dependency in item["dependsOn"]:
            if dependency not in by_id:
                raise RoadmapError(
                    f"Increment {item['id']} depends on unknown increment {dependency}."
                )
            if by_id[dependency]["number"] >= item["number"]:
                raise RoadmapError(
                    f"Increment {item['id']} must depend only on earlier increments."
                )
    if state["increments"] and any(
        item["status"] != "pending" for item in state["increments"]
    ):
        raise RoadmapError(
            "Do not redefine a roadmap after execution starts; record feedback and "
            "create a successor roadmap or resume after an approved bounded update."
        )
    state["increments"] = sorted(increments, key=lambda item: item["number"])
    invalidate_roadmap_approval(state)
    state["status"] = "roadmap-review"


def handle_roadmap_approved(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(event, {"type", "note"}, "event")
    if not state["increments"]:
        raise RoadmapError("Define at least one increment before roadmap approval.")
    if not approved_decisions_are_current(state):
        raise RoadmapError("High-level decisions are missing or stale.")
    state["roadmapApproval"] = {
        "fingerprint": roadmap_fingerprint(state),
        "approvedAt": now_utc(),
        "note": require_string(event["note"], "event.note")
        if event.get("note")
        else None,
    }
    if state.get("currentIncrementId"):
        increment = current_increment(state)
        if increment["plan"]:
            increment["status"] = (
                "verifying"
                if len(increment["completedChunks"])
                == len(increment["plan"]["chunks"])
                else "implementing"
            )
        elif increment["research"]:
            increment["status"] = "planning"
        else:
            increment["status"] = "researching"
        state["status"] = "executing"
    elif state["increments"] and all(
        item["status"] == "completed" for item in state["increments"]
    ):
        state["status"] = "roadmap-ready-to-close"
    elif any(
        item["status"] == "implemented-pending-qualification"
        for item in state["increments"]
    ):
        state["status"] = "implementation-complete-qualification-pending"
    else:
        state["status"] = "ready"


def handle_increment_started(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(event, {"type", "incrementId"}, "event")
    if state.get("currentIncrementId"):
        raise RoadmapError("Complete or block the active increment before starting another.")
    if not approval_is_current(state):
        raise RoadmapError("Roadmap approval is absent or stale.")
    increment_id = require_identifier(event.get("incrementId"), "event.incrementId")
    increment = find_increment(state, increment_id)
    pending = [item for item in state["increments"] if item["status"] == "pending"]
    if not pending or pending[0]["id"] != increment_id:
        raise RoadmapError("Start the next pending increment; skipping is not allowed.")
    incomplete = [
        dependency
        for dependency in increment["dependsOn"]
        if find_increment(state, dependency)["status"] not in INCREMENT_DONE
    ]
    if incomplete:
        raise RoadmapError(
            f"Increment dependencies are incomplete: {', '.join(incomplete)}."
        )
    increment["status"] = "researching"
    increment["startedAt"] = now_utc()
    state["currentIncrementId"] = increment_id
    state["status"] = "executing"


def handle_increment_research_recorded(
    state: dict[str, Any], event: dict[str, Any]
) -> None:
    reject_unknown(event, {"type", "summary", "sources", "risks"}, "event")
    increment = current_increment(state)
    if increment["status"] not in {"researching", "planning"}:
        raise RoadmapError("Record research before implementation begins.")
    increment["research"].append(
        {
            "summary": require_string(event.get("summary"), "event.summary"),
            "sources": [
                validate_source(item, f"event.sources[{index}]")
                for index, item in enumerate(
                    require_list(event.get("sources", []), "event.sources")
                )
            ],
            "risks": require_string_list(event.get("risks", []), "event.risks"),
            "recordedAt": now_utc(),
        }
    )
    increment["status"] = "planning"


def handle_increment_plan_recorded(
    state: dict[str, Any], event: dict[str, Any]
) -> None:
    reject_unknown(event, {"type", "plan"}, "event")
    increment = current_increment(state)
    if not increment["research"]:
        raise RoadmapError("Record increment research before its implementation plan.")
    if increment["completedChunks"]:
        raise RoadmapError("Do not replace an implementation plan after chunks complete.")
    increment["plan"] = validate_plan(event.get("plan"), increment)
    increment["plan"]["recordedAt"] = now_utc()
    increment["plan"]["fingerprint"] = fingerprint(increment["plan"])
    increment["status"] = "implementing"


def handle_chunk_recorded(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(
        event,
        {
            "type",
            "chunkId",
            "summary",
            "areas",
            "tests",
            "documentation",
            "feedbackAddressed",
        },
        "event",
    )
    increment = current_increment(state)
    if increment["status"] not in {"implementing", "verifying"} or not increment["plan"]:
        raise RoadmapError("Record research and an increment plan before work chunks.")
    chunk_id = require_identifier(event.get("chunkId"), "event.chunkId")
    planned = next(
        (item for item in increment["plan"]["chunks"] if item["id"] == chunk_id), None
    )
    if not planned:
        raise RoadmapError(f"Chunk {chunk_id} is not in the approved increment plan.")
    if chunk_id in increment["completedChunks"]:
        raise RoadmapError(f"Chunk {chunk_id} has already been recorded.")
    record = {
        "id": f"{increment['id']}-{chunk_id}",
        "incrementId": increment["id"],
        "chunkId": chunk_id,
        "title": planned["title"],
        "summary": require_string(event.get("summary"), "event.summary"),
        "areas": require_string_list(event.get("areas"), "event.areas", minimum=1),
        "tests": require_string_list(event.get("tests", []), "event.tests"),
        "documentation": require_string_list(
            event.get("documentation", []), "event.documentation"
        ),
        "feedbackAddressed": [
            require_identifier(item, f"event.feedbackAddressed[{index}]")
            for index, item in enumerate(
                require_list(
                    event.get("feedbackAddressed", []),
                    "event.feedbackAddressed",
                )
            )
        ],
        "criteriaIds": planned["criteriaIds"],
        "completedAt": now_utc(),
    }
    known_feedback = {item["id"] for item in state["feedback"]}
    unknown_feedback = sorted(set(record["feedbackAddressed"]) - known_feedback)
    if unknown_feedback:
        raise RoadmapError(
            f"Chunk references unknown feedback: {', '.join(unknown_feedback)}."
        )
    state["chunks"].append(record)
    increment["completedChunks"].append(chunk_id)
    increment["status"] = (
        "verifying"
        if len(increment["completedChunks"]) == len(increment["plan"]["chunks"])
        else "implementing"
    )


def handle_evidence_recorded(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(
        event,
        {
            "type",
            "incrementId",
            "criterionId",
            "kind",
            "outcome",
            "summary",
            "command",
            "artifact",
        },
        "event",
    )
    increment_id = require_identifier(event.get("incrementId"), "event.incrementId")
    criterion_id = require_identifier(event.get("criterionId"), "event.criterionId")
    increment = find_increment(state, increment_id)
    if increment["status"] == "pending":
        raise RoadmapError("Do not record evidence before an increment starts.")
    if increment["status"] == "completed":
        raise RoadmapError(
            "Completed increments are immutable; record regression feedback instead."
        )
    criterion = next(
        (
            item
            for item in increment["acceptanceCriteria"]
            if item["id"] == criterion_id
        ),
        None,
    )
    if not criterion:
        raise RoadmapError(
            f"Unknown criterion {criterion_id} for increment {increment_id}."
        )
    kind = event.get("kind")
    if kind not in {"test", "documentation", "review", "manual", "external"}:
        raise RoadmapError(
            "event.kind must be test, documentation, review, manual, or external."
        )
    outcome = event.get("outcome")
    if outcome not in {"passed", "failed", "pending"}:
        raise RoadmapError("event.outcome must be passed, failed, or pending.")
    if outcome == "pending" and criterion["qualification"] != "controlled-environment":
        raise RoadmapError("Only controlled-environment evidence may remain pending.")
    state["evidence"].append(
        {
            "id": f"evidence-{len(state['evidence']) + 1}",
            "incrementId": increment_id,
            "criterionId": criterion_id,
            "kind": kind,
            "outcome": outcome,
            "summary": require_string(event.get("summary"), "event.summary"),
            "command": require_string(event["command"], "event.command")
            if event.get("command")
            else None,
            "artifact": require_string(event["artifact"], "event.artifact")
            if event.get("artifact")
            else None,
            "recordedAt": now_utc(),
        }
    )
    if increment["status"] == "implemented-pending-qualification":
        pending = []
        for expected in increment["acceptanceCriteria"]:
            latest = latest_criterion_evidence(
                state, increment_id, expected["id"]
            )
            if not latest or latest["outcome"] != "passed":
                pending.append(expected["id"])
        increment["pendingCriteria"] = pending
        if not pending:
            increment["status"] = "completed"
            if all(item["status"] == "completed" for item in state["increments"]):
                state["status"] = "roadmap-ready-to-close"


def handle_feedback_recorded(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(
        event,
        {
            "type",
            "id",
            "summary",
            "category",
            "impact",
            "targetIncrementId",
            "disposition",
            "nextAction",
        },
        "event",
    )
    feedback_id = require_identifier(event.get("id"), "event.id")
    if any(item["id"] == feedback_id for item in state["feedback"]):
        raise RoadmapError(f"Feedback {feedback_id} has already been recorded.")
    category = event.get("category")
    if category not in {
        "clarification",
        "defect",
        "scope",
        "decision",
        "environment",
        "verification",
    }:
        raise RoadmapError("event.category is not supported.")
    impact = event.get("impact")
    if impact not in {
        "within-increment",
        "later-increment",
        "high-level",
        "scope-change",
        "environment",
    }:
        raise RoadmapError("event.impact is not supported.")
    disposition = event.get("disposition")
    if disposition not in {"accepted", "deferred", "needs-decision", "blocked"}:
        raise RoadmapError("event.disposition is not supported.")
    target = event.get("targetIncrementId")
    if target is not None:
        target = require_identifier(target, "event.targetIncrementId")
        find_increment(state, target)
    record = {
        "id": feedback_id,
        "summary": require_string(event.get("summary"), "event.summary"),
        "category": category,
        "impact": impact,
        "targetIncrementId": target,
        "disposition": disposition,
        "nextAction": require_string(event.get("nextAction"), "event.nextAction"),
        "recordedAt": now_utc(),
    }
    state["feedback"].append(record)
    if impact in {"high-level", "scope-change"} or disposition == "needs-decision":
        invalidate_roadmap_approval(state)
        state["status"] = "approval-required"
        if state.get("currentIncrementId"):
            current_increment(state)["status"] = "paused-for-approval"


def handle_blocker_recorded(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(event, {"type", "id", "kind", "summary", "requiredAction"}, "event")
    blocker_id = require_identifier(event.get("id"), "event.id")
    if any(item["id"] == blocker_id for item in state["blockers"]):
        raise RoadmapError(f"Blocker {blocker_id} has already been recorded.")
    kind = event.get("kind")
    if kind not in {
        "environment",
        "dependency",
        "decision",
        "credential",
        "production-authority",
        "technical",
    }:
        raise RoadmapError("event.kind is not supported.")
    state["blockers"].append(
        {
            "id": blocker_id,
            "kind": kind,
            "summary": require_string(event.get("summary"), "event.summary"),
            "requiredAction": require_string(
                event.get("requiredAction"), "event.requiredAction"
            ),
            "status": "open",
            "recordedAt": now_utc(),
            "resolvedAt": None,
            "resolution": None,
        }
    )
    if state.get("currentIncrementId"):
        current_increment(state)["status"] = "blocked"
    state["status"] = "blocked"


def handle_resumed(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(event, {"type", "blockerId", "resolution", "reconciliation"}, "event")
    blocker_id = require_identifier(event.get("blockerId"), "event.blockerId")
    blocker = next(
        (
            item
            for item in state["blockers"]
            if item["id"] == blocker_id and item["status"] == "open"
        ),
        None,
    )
    if not blocker:
        raise RoadmapError(f"Open blocker {blocker_id} was not found.")
    blocker["status"] = "resolved"
    blocker["resolvedAt"] = now_utc()
    blocker["resolution"] = require_string(event.get("resolution"), "event.resolution")
    reconciliation = require_string(
        event.get("reconciliation"), "event.reconciliation"
    )
    state["resumeAudits"].append(
        {
            "blockerId": blocker_id,
            "reconciliation": reconciliation,
            "recordedAt": now_utc(),
        }
    )
    if any(item["status"] == "open" for item in state["blockers"]):
        state["status"] = "blocked"
        return
    if not approval_is_current(state):
        state["status"] = "approval-required"
        if state.get("currentIncrementId"):
            current_increment(state)["status"] = "paused-for-approval"
        return
    if state.get("currentIncrementId"):
        increment = current_increment(state)
        if increment["plan"]:
            increment["status"] = (
                "verifying"
                if len(increment["completedChunks"])
                == len(increment["plan"]["chunks"])
                else "implementing"
            )
        elif increment["research"]:
            increment["status"] = "planning"
        else:
            increment["status"] = "researching"
        state["status"] = "executing"
    else:
        state["status"] = "ready"


def handle_increment_completed(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(event, {"type", "summary"}, "event")
    if not approval_is_current(state):
        raise RoadmapError("Renew roadmap approval before completing the increment.")
    increment = current_increment(state)
    if not increment["plan"]:
        raise RoadmapError("The active increment has no implementation plan.")
    planned = {item["id"] for item in increment["plan"]["chunks"]}
    if set(increment["completedChunks"]) != planned:
        missing = sorted(planned - set(increment["completedChunks"]))
        raise RoadmapError(
            f"Complete every planned chunk before closing the increment: {', '.join(missing)}."
        )
    pending = []
    for criterion in increment["acceptanceCriteria"]:
        evidence = latest_criterion_evidence(state, increment["id"], criterion["id"])
        if not evidence:
            raise RoadmapError(
                f"Acceptance criterion {criterion['id']} has no evidence."
            )
        if evidence["outcome"] == "failed":
            raise RoadmapError(
                f"Acceptance criterion {criterion['id']} currently fails."
            )
        if evidence["outcome"] == "pending":
            if (
                criterion["qualification"] != "controlled-environment"
                or not increment["allowPendingQualification"]
            ):
                raise RoadmapError(
                    f"Acceptance criterion {criterion['id']} may not remain pending."
                )
            pending.append(criterion["id"])
    increment["status"] = (
        "implemented-pending-qualification" if pending else "completed"
    )
    increment["completedAt"] = now_utc()
    increment["completionSummary"] = require_string(
        event.get("summary"), "event.summary"
    )
    increment["pendingCriteria"] = pending
    state["currentIncrementId"] = None
    remaining = [item for item in state["increments"] if item["status"] == "pending"]
    if remaining:
        state["status"] = "ready"
    elif any(item["status"] == "implemented-pending-qualification" for item in state["increments"]):
        state["status"] = "implementation-complete-qualification-pending"
    else:
        state["status"] = "roadmap-ready-to-close"


def handle_roadmap_completed(state: dict[str, Any], event: dict[str, Any]) -> None:
    reject_unknown(event, {"type", "summary"}, "event")
    if not state["increments"]:
        raise RoadmapError("Define and execute at least one increment first.")
    if not approval_is_current(state):
        raise RoadmapError("Roadmap approval is absent or stale.")
    if state.get("currentIncrementId"):
        raise RoadmapError("Complete the active increment first.")
    if any(item["status"] != "completed" for item in state["increments"]):
        raise RoadmapError(
            "Every increment and controlled-environment qualification must pass first."
        )
    state["status"] = "completed"
    state["completion"] = {
        "summary": require_string(event.get("summary"), "event.summary"),
        "completedAt": now_utc(),
    }


EVENT_HANDLERS = {
    "discovery-recorded": handle_discovery_recorded,
    "decision-proposed": handle_decision_proposed,
    "decision-approved": handle_decision_approved,
    "roadmap-defined": handle_roadmap_defined,
    "roadmap-approved": handle_roadmap_approved,
    "increment-started": handle_increment_started,
    "increment-research-recorded": handle_increment_research_recorded,
    "increment-plan-recorded": handle_increment_plan_recorded,
    "chunk-recorded": handle_chunk_recorded,
    "evidence-recorded": handle_evidence_recorded,
    "feedback-recorded": handle_feedback_recorded,
    "blocker-recorded": handle_blocker_recorded,
    "resumed": handle_resumed,
    "increment-completed": handle_increment_completed,
    "roadmap-completed": handle_roadmap_completed,
}


def apply_event(state: dict[str, Any], event: dict[str, Any]) -> dict[str, Any]:
    event_type = require_string(event.get("type"), "event.type", maximum=80)
    if state.get("status") == "completed":
        raise RoadmapError(
            "Completed roadmaps are immutable; create a successor roadmap."
        )
    handler = EVENT_HANDLERS.get(event_type)
    if not handler:
        raise RoadmapError(f"Unsupported event type: {event_type}.")
    updated = copy.deepcopy(state)
    handler(updated, event)
    timestamp = now_utc()
    updated["updatedAt"] = timestamp
    updated["history"].append(
        {
            "sequence": len(updated["history"]) + 1,
            "type": event_type,
            "eventFingerprint": fingerprint(event),
            "recordedAt": timestamp,
        }
    )
    return updated


def validate_state_shape(repo: Path, state: dict[str, Any]) -> None:
    allowed = {
        "schemaVersion",
        "name",
        "slug",
        "objective",
        "createdAt",
        "updatedAt",
        "paths",
        "status",
        "discovery",
        "decisions",
        "increments",
        "roadmapApproval",
        "currentIncrementId",
        "chunks",
        "feedback",
        "evidence",
        "blockers",
        "resumeAudits",
        "history",
        "completion",
    }
    reject_unknown(state, allowed, "state")
    if state.get("schemaVersion") != SCHEMA_VERSION:
        raise RoadmapError(
            f"Unsupported state schema version: {state.get('schemaVersion')}."
        )
    require_string(state.get("name"), "state.name", maximum=200)
    require_identifier(state.get("slug"), "state.slug")
    require_string(state.get("objective"), "state.objective")
    require_string(state.get("createdAt"), "state.createdAt", maximum=80)
    require_string(state.get("updatedAt"), "state.updatedAt", maximum=80)
    require_string(state.get("status"), "state.status", maximum=80)
    paths = require_object(state.get("paths"), "state.paths")
    reject_unknown(paths, {"state", "roadmap", "report"}, "state.paths")
    normalized_paths = {
        key: safe_relative_path(repo, paths.get(key), f"state.paths.{key}")
        for key in ("state", "roadmap", "report")
    }
    if len(set(normalized_paths.values())) != 3:
        raise RoadmapError("State, roadmap, and report paths must be distinct.")
    for key in (
        "decisions",
        "increments",
        "chunks",
        "feedback",
        "evidence",
        "blockers",
        "resumeAudits",
        "history",
    ):
        require_list(state.get(key), f"state.{key}")
    if state.get("currentIncrementId") is not None:
        find_increment(
            state,
            require_identifier(
                state["currentIncrementId"], "state.currentIncrementId"
            ),
        )
    if state["roadmapApproval"] and not approval_is_current(state):
        raise RoadmapError("Stored roadmap approval is stale.")


def render_sources(sources: list[dict[str, str]]) -> list[str]:
    lines = []
    for source in sources:
        title = markdown(source["title"])
        if source.get("url"):
            title = f"[{title}](<{source['url']}>)"
        note = f" - {markdown(source['note'])}" if source.get("note") else ""
        lines.append(f"- {title}{note}")
    return lines or ["None recorded."]


def evidence_label(state: dict[str, Any], increment_id: str, criterion_id: str) -> str:
    evidence = latest_criterion_evidence(state, increment_id, criterion_id)
    if not evidence:
        return "not recorded"
    return f"{evidence['outcome']} ({evidence['kind']})"


def render_roadmap(state: dict[str, Any]) -> str:
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {state['name']} Implementation Roadmap",
        "",
        f"- Status: `{state['status']}`",
        f"- Updated: `{state['updatedAt']}`",
        "",
        "## Objective",
        "",
        state["objective"],
        "",
        "## Discovery",
        "",
    ]
    discovery = state.get("discovery")
    if discovery:
        lines.extend(
            [
                discovery["summary"],
                "",
                "### Constraints",
                "",
                *bullet_lines(discovery["constraints"]),
                "",
                "### Sources",
                "",
                *render_sources(discovery["sources"]),
            ]
        )
    else:
        lines.append("Discovery has not been recorded.")
    lines.extend(["", "## High-level decisions", ""])
    if not state["decisions"]:
        lines.append("No high-level decision has been recorded.")
    for decision in state["decisions"]:
        selected = decision.get("selectedOptionId") or "awaiting approval"
        lines.extend(
            [
                f"### {decision['title']}",
                "",
                decision["question"],
                "",
                decision["context"],
                "",
                f"- Status: `{decision['status']}`",
                f"- Selected option: `{selected}`",
                "",
                "| Option | Summary | Recommended | Tradeoffs | Consequences |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for option in decision["options"]:
            lines.append(
                "| "
                + " | ".join(
                    [
                        markdown(f"{option['label']} ({option['id']})"),
                        markdown(option["summary"]),
                        "yes" if option["recommended"] else "no",
                        markdown("; ".join(option["tradeoffs"]) or "None"),
                        markdown("; ".join(option["consequences"]) or "None"),
                    ]
                )
                + " |"
            )
        lines.append("")
    lines.extend(["## Increment map", ""])
    if state["increments"]:
        lines.extend(
            [
                "| Increment | Outcome | Dependencies | Status |",
                "| --- | --- | --- | --- |",
            ]
        )
        for increment in state["increments"]:
            dependencies = ", ".join(increment["dependsOn"]) or "None"
            lines.append(
                f"| {increment['number']}: {markdown(increment['title'])} "
                f"| {markdown(increment['objective'])} | {dependencies} "
                f"| `{increment['status']}` |"
            )
    else:
        lines.append("The increment roadmap has not been defined.")
    for increment in state["increments"]:
        lines.extend(
            [
                "",
                f"## Increment {increment['number']}: {increment['title']}",
                "",
                f"- Id: `{increment['id']}`",
                f"- Status: `{increment['status']}`",
                "- Dependencies: "
                + (
                    ", ".join(f"`{item}`" for item in increment["dependsOn"])
                    or "None"
                ),
                "",
                increment["objective"],
                "",
                "### Work packages",
                "",
            ]
        )
        if increment["workPackages"]:
            lines.extend(
                f"- **{item['title']}** (`{item['id']}`): {item['outcome']}"
                for item in increment["workPackages"]
            )
        else:
            lines.append("None recorded.")
        lines.extend(
            [
                "",
                "### Deliverables",
                "",
                *bullet_lines(increment["deliverables"]),
                "",
                "### Acceptance criteria",
                "",
                "| Criterion | Qualification | Latest evidence |",
                "| --- | --- | --- |",
            ]
        )
        for criterion in increment["acceptanceCriteria"]:
            lines.append(
                f"| `{criterion['id']}`: {markdown(criterion['description'])} "
                f"| {criterion['qualification']} "
                f"| {evidence_label(state, increment['id'], criterion['id'])} |"
            )
        lines.extend(
            [
                "",
                "### Verification",
                "",
                *bullet_lines(increment["verification"]),
                "",
                "### Rollback",
                "",
                increment["rollback"],
                "",
                "### Excluded",
                "",
                *bullet_lines(increment["excluded"]),
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def next_checkpoint(state: dict[str, Any]) -> str:
    status = state["status"]
    if status == "discovery":
        return "Inspect the repository and record discovery."
    if status in {"decision-options", "decision-approval"}:
        return (
            "Present two or three high-level options and obtain explicit user approval."
        )
    if status in {"roadmap-drafting", "roadmap-review"}:
        return "Define the increments and obtain explicit roadmap approval."
    if status == "approval-required":
        return "Reconcile feedback and obtain renewed user approval before continuing."
    if status == "ready":
        return (
            "Start the next pending increment, then research and plan it before editing."
        )
    if status == "executing":
        return "Complete the active planned chunk and update this report."
    if status == "blocked":
        return "Resolve the recorded blocker and complete a resume reconciliation."
    if status == "implementation-complete-qualification-pending":
        return "Collect the outstanding controlled-environment evidence."
    if status == "roadmap-ready-to-close":
        return "Review final evidence and record roadmap completion."
    if status == "completed":
        return "Roadmap complete; create a successor roadmap for new scope."
    return "Review the state and choose the next approved transition."


def render_report(state: dict[str, Any]) -> str:
    roadmap_link = relative_markdown_link(
        state["paths"]["report"], state["paths"]["roadmap"]
    )
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {state['name']} Implementation Report",
        "",
        f"- Roadmap: [{state['name']} implementation roadmap]({roadmap_link})",
        f"- Status: `{state['status']}`",
        f"- Current increment: `{state.get('currentIncrementId') or 'none'}`",
        f"- Updated: `{state['updatedAt']}`",
        "",
        "## Next checkpoint",
        "",
        next_checkpoint(state),
        "",
        "## Increment status",
        "",
    ]
    if state["increments"]:
        lines.extend(
            [
                "| Increment | Status | Completed chunks | Pending criteria |",
                "| --- | --- | --- | --- |",
            ]
        )
        for increment in state["increments"]:
            chunks = ", ".join(increment["completedChunks"]) or "None"
            pending = ", ".join(increment.get("pendingCriteria", [])) or "None"
            lines.append(
                f"| {increment['number']}: {markdown(increment['title'])} "
                f"| `{increment['status']}` | {chunks} | {pending} |"
            )
    else:
        lines.append("No increments defined.")
    lines.extend(["", "## Approved decisions", ""])
    if state["decisions"]:
        lines.extend(
            [
                "| Decision | Selected option | Status |",
                "| --- | --- | --- |",
            ]
        )
        for decision in state["decisions"]:
            lines.append(
                f"| {markdown(decision['title'])} "
                f"| `{decision.get('selectedOptionId') or 'none'}` "
                f"| `{decision['status']}` |"
            )
    else:
        lines.append("None recorded.")
    active = None
    if state.get("currentIncrementId"):
        active = current_increment(state)
    lines.extend(["", "## Current increment plan", ""])
    if active and active.get("plan"):
        lines.extend([active["plan"]["summary"], "", "### Steps", ""])
        lines.extend(
            f"{index}. {step}"
            for index, step in enumerate(active["plan"]["steps"], 1)
        )
        lines.extend(["", "### Planned chunks", ""])
        for chunk in active["plan"]["chunks"]:
            marker = "x" if chunk["id"] in active["completedChunks"] else " "
            lines.append(
                f"- [{marker}] **{chunk['title']}** (`{chunk['id']}`): "
                f"{chunk['outcome']}"
            )
    else:
        lines.append("No active implementation plan.")
    lines.extend(["", "## Completed chunks", ""])
    if state["chunks"]:
        for chunk in state["chunks"]:
            lines.extend(
                [
                    f"### {chunk['title']} "
                    f"(`{chunk['incrementId']}/{chunk['chunkId']}`)",
                    "",
                    chunk["summary"],
                    "",
                    "- Areas: " + "; ".join(chunk["areas"]),
                    "- Tests: "
                    + ("; ".join(chunk["tests"]) or "None recorded"),
                    "- Documentation: "
                    + ("; ".join(chunk["documentation"]) or "None recorded"),
                    "- Feedback addressed: "
                    + ("; ".join(chunk["feedbackAddressed"]) or "None"),
                    f"- Completed: `{chunk['completedAt']}`",
                    "",
                ]
            )
    else:
        lines.append("No coherent work chunk has been completed.")
    lines.extend(["", "## Feedback register", ""])
    if state["feedback"]:
        lines.extend(
            [
                "| Id | Summary | Impact | Disposition | Next action |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for item in state["feedback"]:
            lines.append(
                f"| `{item['id']}` | {markdown(item['summary'])} "
                f"| {item['impact']} | {item['disposition']} "
                f"| {markdown(item['nextAction'])} |"
            )
    else:
        lines.append("None recorded.")
    lines.extend(["", "## Evidence ledger", ""])
    if state["evidence"]:
        lines.extend(
            [
                "| Increment / criterion | Kind | Outcome | Summary | Artifact |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for item in state["evidence"]:
            lines.append(
                f"| `{item['incrementId']}/{item['criterionId']}` "
                f"| {item['kind']} | **{item['outcome']}** "
                f"| {markdown(item['summary'])} "
                f"| {markdown(item.get('artifact') or 'None')} |"
            )
    else:
        lines.append("None recorded.")
    lines.extend(["", "## Blockers and resume audits", ""])
    if state["blockers"]:
        for blocker in state["blockers"]:
            lines.append(
                f"- **{blocker['id']}** ({blocker['kind']}, {blocker['status']}): "
                f"{blocker['summary']} Required action: {blocker['requiredAction']}"
            )
    else:
        lines.append("No blockers recorded.")
    if state["resumeAudits"]:
        lines.extend(["", "### Resume audits", ""])
        for audit in state["resumeAudits"]:
            lines.append(
                f"- `{audit['blockerId']}` at `{audit['recordedAt']}`: "
                f"{audit['reconciliation']}"
            )
    if state.get("completion"):
        lines.extend(
            [
                "",
                "## Completion",
                "",
                state["completion"]["summary"],
                "",
                f"Completed at `{state['completion']['completedAt']}`.",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def document_contents(state: dict[str, Any]) -> dict[str, str]:
    return {
        state["paths"]["roadmap"]: render_roadmap(state),
        state["paths"]["report"]: render_report(state),
    }


def ensure_documents_match(repo: Path, state: dict[str, Any]) -> None:
    mismatches = []
    for relative, expected in document_contents(state).items():
        path = repo / relative
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            mismatches.append(relative)
            continue
        if normalize_text(actual) != expected:
            mismatches.append(relative)
    if mismatches:
        raise RoadmapError(
            "Generated document drift detected: "
            + ", ".join(mismatches)
            + ". Run the render command to restore documents from state."
        )


def write_project_files(repo: Path, state: dict[str, Any]) -> None:
    state_content = (
        json.dumps(state, indent=2, ensure_ascii=True, sort_keys=True) + "\n"
    )
    atomic_write(repo / state["paths"]["state"], state_content)
    for relative, content in document_contents(state).items():
        atomic_write(repo / relative, content)


def initial_state(repo: Path, config: dict[str, Any]) -> dict[str, Any]:
    reject_unknown(
        config,
        {
            "name",
            "slug",
            "objective",
            "statePath",
            "roadmapPath",
            "reportPath",
        },
        "config",
    )
    name = require_string(config.get("name"), "config.name", maximum=200)
    slug = require_identifier(config.get("slug"), "config.slug")
    objective = require_string(config.get("objective"), "config.objective")
    paths = {
        "state": safe_relative_path(
            repo,
            config.get(
                "statePath", f".implementation-roadmaps/{slug}/state.json"
            ),
            "config.statePath",
        ),
        "roadmap": safe_relative_path(
            repo,
            config.get(
                "roadmapPath", f"docs/{slug}-implementation-roadmap.md"
            ),
            "config.roadmapPath",
        ),
        "report": safe_relative_path(
            repo,
            config.get(
                "reportPath", f"docs/{slug}-implementation-report.md"
            ),
            "config.reportPath",
        ),
    }
    if len(set(paths.values())) != 3:
        raise RoadmapError("State, roadmap, and report paths must be distinct.")
    existing = [
        relative for relative in paths.values() if (repo / relative).exists()
    ]
    if existing:
        raise RoadmapError(
            "Refusing to overwrite existing file(s): " + ", ".join(existing)
        )
    timestamp = now_utc()
    state = {
        "schemaVersion": SCHEMA_VERSION,
        "name": name,
        "slug": slug,
        "objective": objective,
        "createdAt": timestamp,
        "updatedAt": timestamp,
        "paths": paths,
        "status": "discovery",
        "discovery": None,
        "decisions": [],
        "increments": [],
        "roadmapApproval": None,
        "currentIncrementId": None,
        "chunks": [],
        "feedback": [],
        "evidence": [],
        "blockers": [],
        "resumeAudits": [],
        "history": [],
        "completion": None,
    }
    validate_state_shape(repo, state)
    return state


def resolve_repo(value: str) -> Path:
    repo = Path(value).resolve()
    if not repo.is_dir():
        raise RoadmapError(f"Repository directory does not exist: {repo}")
    return repo


def load_state(repo: Path, value: str) -> tuple[Path, dict[str, Any]]:
    relative = safe_relative_path(repo, value, "--state")
    path = repo / relative
    state = read_json(path, "state")
    validate_state_shape(repo, state)
    if state["paths"]["state"] != relative:
        raise RoadmapError("--state does not match state.paths.state.")
    return path, state


def result_payload(repo: Path, state: dict[str, Any]) -> dict[str, Any]:
    return {
        "status": state["status"],
        "currentIncrementId": state.get("currentIncrementId"),
        "statePath": str((repo / state["paths"]["state"]).resolve()),
        "roadmapPath": str((repo / state["paths"]["roadmap"]).resolve()),
        "reportPath": str((repo / state["paths"]["report"]).resolve()),
        "roadmapFingerprint": (
            roadmap_fingerprint(state) if state["increments"] else None
        ),
    }


def command_init(args: argparse.Namespace) -> dict[str, Any]:
    repo = resolve_repo(args.repo)
    config = read_json(Path(args.config).resolve(), "config")
    state = initial_state(repo, config)
    write_project_files(repo, state)
    return result_payload(repo, state)


def command_apply(args: argparse.Namespace) -> dict[str, Any]:
    repo = resolve_repo(args.repo)
    _, state = load_state(repo, args.state)
    ensure_documents_match(repo, state)
    event = read_json(Path(args.event_file).resolve(), "event")
    updated = apply_event(state, event)
    validate_state_shape(repo, updated)
    if not args.dry_run:
        write_project_files(repo, updated)
    result = result_payload(repo, updated)
    result["dryRun"] = args.dry_run
    result["eventFingerprint"] = fingerprint(event)
    return result


def command_validate(args: argparse.Namespace) -> dict[str, Any]:
    repo = resolve_repo(args.repo)
    _, state = load_state(repo, args.state)
    ensure_documents_match(repo, state)
    result = result_payload(repo, state)
    result["valid"] = True
    return result


def command_render(args: argparse.Namespace) -> dict[str, Any]:
    repo = resolve_repo(args.repo)
    _, state = load_state(repo, args.state)
    contents = document_contents(state)
    if not args.dry_run:
        for relative, content in contents.items():
            atomic_write(repo / relative, content)
    result = result_payload(repo, state)
    result["dryRun"] = args.dry_run
    return result


def command_status(args: argparse.Namespace) -> dict[str, Any]:
    repo = resolve_repo(args.repo)
    _, state = load_state(repo, args.state)
    result = result_payload(repo, state)
    result["nextCheckpoint"] = next_checkpoint(state)
    return result


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Maintain an approval-gated implementation roadmap."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser(
        "init", help="Create roadmap state and documents."
    )
    init_parser.add_argument("--repo", default=".")
    init_parser.add_argument("--config", required=True)
    init_parser.set_defaults(handler=command_init)

    for name, handler, help_text in (
        ("apply", command_apply, "Apply one validated event."),
        (
            "validate",
            command_validate,
            "Validate state and generated documents.",
        ),
        ("render", command_render, "Restore generated documents from state."),
        ("status", command_status, "Show the next workflow checkpoint."),
    ):
        subparser = subparsers.add_parser(name, help=help_text)
        subparser.add_argument("--repo", default=".")
        subparser.add_argument("--state", required=True)
        if name in {"apply", "render"}:
            subparser.add_argument("--dry-run", action="store_true")
        if name == "apply":
            subparser.add_argument("--event-file", required=True)
        subparser.set_defaults(handler=handler)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        result = args.handler(args)
    except RoadmapError as error:
        print(f"roadmap.py: error: {error}", file=sys.stderr)
        return 2
    except (KeyError, TypeError, IndexError) as error:
        print(
            f"roadmap.py: error: malformed roadmap state or event: {error}",
            file=sys.stderr,
        )
        return 2
    print(json.dumps(result, indent=2, ensure_ascii=True, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
