import type { UserLibraryAssetRepositoryPort, WorkspaceUserLibraryLinkRepositoryPort } from "../../../../application/ports/user-library";
import type { CopyUserLibraryAssetToWorkspaceUseCase, ImportWorkspaceAssetToWorkspaceUseCase, LinkUserLibraryAssetToWorkspaceUseCase, PromoteWorkspaceAssetToUserLibraryUseCase } from "../../../../application/use-cases/user-library";
import type { WorkspaceEffectiveAssetSourceResolver } from "../../../../application/services/asset";
import { createWorkspaceId } from "../../../../contracts/workspace";
import { API_USER_LIBRARY_ASSET_LIST_OPERATION, API_USER_LIBRARY_ASSET_READ_OPERATION, API_USER_LIBRARY_COPY_OPERATION, API_USER_LIBRARY_IMPORT_OPERATION, API_USER_LIBRARY_LINK_LIST_OPERATION, API_USER_LIBRARY_LINK_OPERATION, API_USER_LIBRARY_LINK_READ_OPERATION, API_USER_LIBRARY_PROMOTE_OPERATION, API_WORKSPACE_EFFECTIVE_ASSET_SOURCE_LIST_OPERATION, createApiUserLibraryFailureResponse, createApiUserLibraryOperationSuccessResponse } from "../../../../contracts/api";
interface Req { headers?: Record<string, string | string[] | undefined>; body?: unknown; params?: Record<string, string | undefined>; query?: Record<string, unknown>; }
interface Res { status: (c:number)=>Res; json:(b:unknown)=>void; }
interface App { get:(p:string,h:(r:Req,s:Res)=>Promise<void>)=>void; post:(p:string,h:(r:Req,s:Res)=>Promise<void>)=>void; }
export interface RegisterUserLibraryApiRoutesDependencies { app: App; promoteUseCase?: PromoteWorkspaceAssetToUserLibraryUseCase; linkUseCase?: LinkUserLibraryAssetToWorkspaceUseCase; copyUseCase?: CopyUserLibraryAssetToWorkspaceUseCase; importUseCase?: ImportWorkspaceAssetToWorkspaceUseCase; userLibraryAssetRepository?: UserLibraryAssetRepositoryPort; workspaceUserLibraryLinkRepository?: WorkspaceUserLibraryLinkRepositoryPort; workspaceEffectiveAssetSourceResolver?: WorkspaceEffectiveAssetSourceResolver; }
export function registerUserLibraryApiRoutes(d: RegisterUserLibraryApiRoutesDependencies): void {
 d.app.post('/api/user-library/assets/promote', async (req,res)=>{ const c=contextFrom(req); if(!d.promoteUseCase) return unavailable(res, API_USER_LIBRARY_PROMOTE_OPERATION, c); try { const cmd=req.body as any; cmd.sourceWorkspaceId=createWorkspaceId(cmd?.sourceWorkspaceId); const result=await d.promoteUseCase.execute(cmd); return res.status(result.ok?200:400).json(createApiUserLibraryOperationSuccessResponse(API_USER_LIBRARY_PROMOTE_OPERATION,result,c)); } catch { return res.status(400).json(createApiUserLibraryFailureResponse(API_USER_LIBRARY_PROMOTE_OPERATION,'validation','Promotion request is invalid.',c)); } });
 d.app.post('/api/user-library/workspace-links', async (req,res)=>{ const c=contextFrom(req); if(!d.linkUseCase) return unavailable(res, API_USER_LIBRARY_LINK_OPERATION,c); try { const cmd=req.body as any; cmd.targetWorkspaceId=createWorkspaceId(cmd?.targetWorkspaceId); const result=await d.linkUseCase.execute(cmd); return res.status(result.ok?200:400).json(createApiUserLibraryOperationSuccessResponse(API_USER_LIBRARY_LINK_OPERATION,result,c)); } catch { return res.status(400).json(createApiUserLibraryFailureResponse(API_USER_LIBRARY_LINK_OPERATION,'validation','Link request is invalid.',c)); } });
 d.app.post('/api/workspaces/:workspaceId/user-library/copies', async (req,res)=>{ const c=contextFrom(req); if(!d.copyUseCase) return unavailable(res, API_USER_LIBRARY_COPY_OPERATION,c); try { const cmd={...(req.body as any), targetWorkspaceId:createWorkspaceId(req.params?.workspaceId ?? '')}; const result=await d.copyUseCase.execute(cmd); return res.status(result.ok?200:400).json(createApiUserLibraryOperationSuccessResponse(API_USER_LIBRARY_COPY_OPERATION,result,c)); } catch { return res.status(400).json(createApiUserLibraryFailureResponse(API_USER_LIBRARY_COPY_OPERATION,'validation','Copy request is invalid.',c)); } });
 d.app.post('/api/workspaces/:targetWorkspaceId/imports/workspace-asset', async (req,res)=>{ const c=contextFrom(req); if(!d.importUseCase) return unavailable(res, API_USER_LIBRARY_IMPORT_OPERATION,c); try { const body=req.body as any; const cmd={...body,targetWorkspaceId:createWorkspaceId(req.params?.targetWorkspaceId ?? ''),sourceWorkspaceId:createWorkspaceId(body?.sourceWorkspaceId)}; const result=await d.importUseCase.execute(cmd); return res.status(result.ok?200:400).json(createApiUserLibraryOperationSuccessResponse(API_USER_LIBRARY_IMPORT_OPERATION,result,c)); } catch { return res.status(400).json(createApiUserLibraryFailureResponse(API_USER_LIBRARY_IMPORT_OPERATION,'validation','Import request is invalid.',c)); } });
 d.app.get('/api/user-library/assets', async (req,res)=>{ const c=contextFrom(req); if(!d.userLibraryAssetRepository) return unavailable(res, API_USER_LIBRARY_ASSET_LIST_OPERATION,c); try { const q=req.query ?? {}; const value=await d.userLibraryAssetRepository.listUserLibraryAssetRecords({ text: s(q.text), status: s(q.status) as any, sourceWorkspaceId: s(q.sourceWorkspaceId) as any, sourceKind: s(q.sourceKind) as any, limit: n(q.limit), cursor: s(q.cursor) }); return res.status(200).json(createApiUserLibraryOperationSuccessResponse(API_USER_LIBRARY_ASSET_LIST_OPERATION, value, c)); } catch { return res.status(500).json(createApiUserLibraryFailureResponse(API_USER_LIBRARY_ASSET_LIST_OPERATION,'internal','Unable to list user-library assets.',c)); } });
 d.app.get('/api/user-library/assets/:assetId', async (req,res)=>{ const c=contextFrom(req); if(!d.userLibraryAssetRepository) return unavailable(res, API_USER_LIBRARY_ASSET_READ_OPERATION,c); try { const r=await d.userLibraryAssetRepository.readUserLibraryAssetRecordById(req.params?.assetId as any, s(req.query?.version) as any); if(!r) return res.status(404).json(createApiUserLibraryFailureResponse(API_USER_LIBRARY_ASSET_READ_OPERATION,'not-found','User-library asset was not found.',c)); return res.status(200).json(createApiUserLibraryOperationSuccessResponse(API_USER_LIBRARY_ASSET_READ_OPERATION,r,c)); } catch { return res.status(400).json(createApiUserLibraryFailureResponse(API_USER_LIBRARY_ASSET_READ_OPERATION,'validation','User-library asset read request is invalid.',c)); } });
 d.app.get('/api/workspaces/:workspaceId/user-library/links', async (req,res)=>{ const c=contextFrom(req); if(!d.workspaceUserLibraryLinkRepository) return unavailable(res, API_USER_LIBRARY_LINK_LIST_OPERATION,c); try { const workspaceId=createWorkspaceId(req.params?.workspaceId ?? ''); const q=req.query ?? {}; const value=await d.workspaceUserLibraryLinkRepository.listWorkspaceUserLibraryLinkRecords({ targetWorkspaceId: workspaceId, status: s(q.status) as any, propagationPolicy: s(q.propagationPolicy) as any, text: s(q.text), limit: n(q.limit), cursor: s(q.cursor) }); return res.status(200).json(createApiUserLibraryOperationSuccessResponse(API_USER_LIBRARY_LINK_LIST_OPERATION,value,c)); } catch { return res.status(400).json(createApiUserLibraryFailureResponse(API_USER_LIBRARY_LINK_LIST_OPERATION,'validation','Workspace link list request is invalid.',c)); } });
 d.app.get('/api/workspaces/:workspaceId/user-library/links/:linkId', async (req,res)=>{ const c=contextFrom(req); if(!d.workspaceUserLibraryLinkRepository) return unavailable(res, API_USER_LIBRARY_LINK_READ_OPERATION,c); try { const workspaceId=createWorkspaceId(req.params?.workspaceId ?? ''); const r=await d.workspaceUserLibraryLinkRepository.readWorkspaceUserLibraryLinkRecord(workspaceId, req.params?.linkId as any); if(!r) return res.status(404).json(createApiUserLibraryFailureResponse(API_USER_LIBRARY_LINK_READ_OPERATION,'not-found','Workspace user-library link was not found.',c)); return res.status(200).json(createApiUserLibraryOperationSuccessResponse(API_USER_LIBRARY_LINK_READ_OPERATION,r,c)); } catch { return res.status(400).json(createApiUserLibraryFailureResponse(API_USER_LIBRARY_LINK_READ_OPERATION,'validation','Workspace link read request is invalid.',c)); } });
 d.app.get('/api/workspaces/:workspaceId/effective-asset-sources', async (req,res)=>{ const c=contextFrom(req); if(!d.workspaceEffectiveAssetSourceResolver) return unavailable(res, API_WORKSPACE_EFFECTIVE_ASSET_SOURCE_LIST_OPERATION,c); try { const workspaceId=createWorkspaceId(req.params?.workspaceId ?? ''); const aid=s(req.query?.assetId); if(!aid) throw new Error(); const item=await d.workspaceEffectiveAssetSourceResolver.resolve(workspaceId,{definitionRef:{kind:String(req.query?.kind ?? 'asset-definition') as any,id:aid as any,version:s(req.query?.version)}}); return res.status(200).json(createApiUserLibraryOperationSuccessResponse(API_WORKSPACE_EFFECTIVE_ASSET_SOURCE_LIST_OPERATION,{items:[item]},c)); } catch { return res.status(400).json(createApiUserLibraryFailureResponse(API_WORKSPACE_EFFECTIVE_ASSET_SOURCE_LIST_OPERATION,'validation','Effective source request is invalid.',c)); } });
}
const s=(v:unknown)=> typeof v==='string'?v:undefined; const n=(v:unknown)=>{const x=Number(v); return Number.isFinite(x)?x:undefined;};
function unavailable(res:Res,op:string,c:{requestId?:string;correlationId?:string}){ return res.status(503).json(createApiUserLibraryFailureResponse(op,'unavailable','User-library operation is unavailable in this server composition.',c)); }
function contextFrom(r:Req){ const h=(k:string)=>{ const v=r.headers?.[k] ?? r.headers?.[k.toLowerCase()]; return Array.isArray(v)?v[0]:v; }; return { requestId: h('x-request-id'), correlationId: h('x-correlation-id') }; }
