import { readFileSync } from "node:fs";
import path from "node:path";
import type { TlsCertificateMode } from "../../modules/contracts/security";
import {
  createCompositeTlsCertificateProvider,
  createFilesystemTlsCertificateStore,
  parseTlsCertificateHosts,
} from "../../modules/adapters/security/tls";

type ThinClientViteHttpsEnvironment = Partial<Record<
  | "AI_SYSTEM_BUILDER_THIN_CLIENT_HTTPS_ENABLED"
  | "AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_CERT_PATH"
  | "AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_KEY_PATH"
  | "AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_CERT_DIRECTORY"
  | "AI_SYSTEM_BUILDER_TLS_CERT_MODE"
  | "AI_SYSTEM_BUILDER_TLS_CERT_DIRECTORY"
  | "AI_SYSTEM_BUILDER_TLS_CERT_HOSTS"
  | "INIT_CWD",
  string
>>;

const DEFAULT_TLS_CERT_MODE: TlsCertificateMode = "manual";
const AUTO_TLS_CERT_MODES = new Set<TlsCertificateMode>(["auto-self-signed", "auto-local-ca"]);

function isEnabled(value: string | undefined): boolean {
  return value?.trim().toLowerCase() === "true";
}

export function isThinClientViteHttpsEnabled(
  environment: ThinClientViteHttpsEnvironment = process.env,
): boolean {
  return isEnabled(environment.AI_SYSTEM_BUILDER_THIN_CLIENT_HTTPS_ENABLED);
}

function requirePath(value: string | undefined, variableName: string): string {
  const trimmedPath = value?.trim();
  if (!trimmedPath) {
    throw new Error(`${variableName} is required when AI_SYSTEM_BUILDER_THIN_CLIENT_HTTPS_ENABLED=true.`);
  }

  return trimmedPath;
}

function hasValue(value: string | undefined): boolean {
  return Boolean(value?.trim());
}

function readRequiredPemFile(path: string, variableName: string, includePathInError: boolean): Buffer {
  try {
    return readFileSync(path);
  } catch (error) {
    const reason = error instanceof Error ? error.message : "unknown read error";
    if (includePathInError) {
      throw new Error(`${variableName} could not be read at \"${path}\": ${reason}`);
    }
    throw new Error(`${variableName} could not be read.`);
  }
}

function validateCertificatePemShape(contents: Buffer, variableName: string): void {
  const pemText = contents.toString("utf8");
  if (!pemText.includes("-----BEGIN CERTIFICATE-----")) {
    throw new Error(`${variableName} must point to a PEM certificate file containing -----BEGIN CERTIFICATE-----.`);
  }
}

function validatePrivateKeyPemShape(contents: Buffer, variableName: string): void {
  const pemText = contents.toString("utf8");
  const hasSupportedHeader = [
    "-----BEGIN PRIVATE KEY-----",
    "-----BEGIN RSA PRIVATE KEY-----",
    "-----BEGIN EC PRIVATE KEY-----",
  ].some((header) => pemText.includes(header));

  if (!hasSupportedHeader) {
    throw new Error(
      `${variableName} must point to a PEM private key file with a supported BEGIN header.`,
    );
  }
}

function isThinClientAppRootDirectory(directory: string): boolean {
  try {
    const packageJson = JSON.parse(readFileSync(path.join(directory, "package.json"), "utf8")) as { name?: unknown };
    return packageJson.name === "@ai-system-builder/thin-client";
  } catch {
    return false;
  }
}

function resolveThinClientAppRootDirectory(environment: ThinClientViteHttpsEnvironment): string {
  const seedDirectories = [environment.INIT_CWD, process.cwd()].filter((value): value is string => hasValue(value));

  for (const seedDirectory of seedDirectories) {
    let cursor = path.resolve(seedDirectory);
    while (true) {
      if (isThinClientAppRootDirectory(cursor)) return cursor;

      const workspaceThinClientDirectory = path.join(cursor, "apps", "thin-client");
      if (isThinClientAppRootDirectory(workspaceThinClientDirectory)) return workspaceThinClientDirectory;

      const parent = path.dirname(cursor);
      if (parent === cursor) break;
      cursor = parent;
    }
  }

  return path.resolve("apps", "thin-client");
}

function resolveThinClientCertificateDirectory(environment: ThinClientViteHttpsEnvironment): string {
  const configuredDirectory =
    environment.AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_CERT_DIRECTORY?.trim() ||
    environment.AI_SYSTEM_BUILDER_TLS_CERT_DIRECTORY?.trim();

  return configuredDirectory || path.join(resolveThinClientAppRootDirectory(environment), ".local", "security", "tls");
}

function resolveTlsCertificateMode(environment: ThinClientViteHttpsEnvironment): TlsCertificateMode {
  return (environment.AI_SYSTEM_BUILDER_TLS_CERT_MODE?.trim() || DEFAULT_TLS_CERT_MODE) as TlsCertificateMode;
}

async function resolveAutoGeneratedHttpsConfig(
  environment: ThinClientViteHttpsEnvironment,
  mode: TlsCertificateMode,
): Promise<{ cert: Buffer; key: Buffer }> {
  const tlsProvider = createCompositeTlsCertificateProvider(createFilesystemTlsCertificateStore());
  const tlsMaterial = await tlsProvider.resolveCertificateMaterial({
    httpsEnabled: true,
    httpsRequired: false,
    mode,
    certificateDirectory: resolveThinClientCertificateDirectory(environment),
    hosts: parseTlsCertificateHosts(environment.AI_SYSTEM_BUILDER_TLS_CERT_HOSTS),
    now: new Date(),
  });

  if (!tlsMaterial) {
    throw new Error(`AI_SYSTEM_BUILDER_TLS_CERT_MODE=${mode} did not produce thin-client HTTPS certificate material.`);
  }

  return {
    cert: Buffer.from(tlsMaterial.certPem, "utf8"),
    key: Buffer.from(tlsMaterial.keyPem, "utf8"),
  };
}

export async function resolveThinClientViteHttpsConfig(
  environment: ThinClientViteHttpsEnvironment = process.env,
): Promise<false | { cert: Buffer; key: Buffer }> {
  if (!isThinClientViteHttpsEnabled(environment)) {
    return false;
  }

  const hasExplicitCertPath = hasValue(environment.AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_CERT_PATH);
  const hasExplicitKeyPath = hasValue(environment.AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_KEY_PATH);
  const tlsCertificateMode = resolveTlsCertificateMode(environment);

  if (!hasExplicitCertPath && !hasExplicitKeyPath && AUTO_TLS_CERT_MODES.has(tlsCertificateMode)) {
    return resolveAutoGeneratedHttpsConfig(environment, tlsCertificateMode);
  }

  const certPath = requirePath(
    environment.AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_CERT_PATH,
    "AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_CERT_PATH",
  );
  const keyPath = requirePath(
    environment.AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_KEY_PATH,
    "AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_KEY_PATH",
  );

  const cert = readRequiredPemFile(certPath, "AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_CERT_PATH", true);
  const key = readRequiredPemFile(keyPath, "AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_KEY_PATH", false);
  validateCertificatePemShape(cert, "AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_CERT_PATH");
  validatePrivateKeyPemShape(key, "AI_SYSTEM_BUILDER_THIN_CLIENT_TLS_KEY_PATH");

  return {
    cert,
    key,
  };
}
