import { normalizeAssetReference } from "../asset";
import { createWorkspaceId } from "../workspace";
import type { CreateAssetDraftCommand, CreateAssetOverrideCommand, CreateWorkspaceAuthoredAssetCommand, DisableAssetOverrideCommand, PublishAssetDraftCommand, ResolveAssetCustomizationConflictCommand, UpdateAssetDraftCommand, UpdateAssetOverrideCommand } from "./asset-authoring-commands";
import { normalizeSafeAssetEditableFieldPatch } from "./asset-authoring-editable-fields";
import { normalizeAssetDraftId, normalizeAssetOverrideId, normalizeAssetRevisionId, normalizeAuthoredAssetId } from "./asset-authoring-identity";
import type { AssetCustomizationTarget, AssetOverrideRecord, AuthoredAssetDraftRecord, AuthoredAssetRecord, AuthoredAssetRevisionRecord } from "./asset-authoring-models";
import { normalizeAssetAuthoringStatus, normalizeAssetOverrideStatus } from "./asset-authoring-status";

const t=(v:unknown,l:string)=>{if(typeof v!=="string"||v.trim().length===0||v!==v.trim()){throw new Error(`${l} is invalid.`);} return v;};
export function normalizeAssetCustomizationTarget(v:AssetCustomizationTarget):AssetCustomizationTarget{return {...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),effectiveAssetReference:normalizeAssetReference(v.effectiveAssetReference),...(v.baseRevision?{baseRevision:t(v.baseRevision,"Base revision")}:{})};}
export function normalizeAuthoredAssetRecord(v:AuthoredAssetRecord):AuthoredAssetRecord{return {...v,authoredAssetId:normalizeAuthoredAssetId(v.authoredAssetId),workspaceId:createWorkspaceId(v.workspaceId),assetReference:normalizeAssetReference(v.assetReference),currentRevisionId:normalizeAssetRevisionId(v.currentRevisionId),status:normalizeAssetAuthoringStatus(v.status),editableValues:normalizeSafeAssetEditableFieldPatch(v.editableValues),createdAt:t(v.createdAt,"Created at"),updatedAt:t(v.updatedAt,"Updated at")};}
export function normalizeAuthoredAssetDraftRecord(v:AuthoredAssetDraftRecord):AuthoredAssetDraftRecord{return {...v,draftId:normalizeAssetDraftId(v.draftId),targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),...(v.baseAssetReference?{baseAssetReference:normalizeAssetReference(v.baseAssetReference)}:{}),draftEditableValues:normalizeSafeAssetEditableFieldPatch(v.draftEditableValues),status:normalizeAssetAuthoringStatus(v.status),createdAt:t(v.createdAt,"Created at"),updatedAt:t(v.updatedAt,"Updated at")};}
export function normalizeAuthoredAssetRevisionRecord(v:AuthoredAssetRevisionRecord):AuthoredAssetRevisionRecord{return {...v,revisionId:normalizeAssetRevisionId(v.revisionId),authoredAssetId:normalizeAuthoredAssetId(v.authoredAssetId),revision:t(v.revision,"Revision"),status:normalizeAssetAuthoringStatus(v.status),editableValues:normalizeSafeAssetEditableFieldPatch(v.editableValues),createdAt:t(v.createdAt,"Created at"),updatedAt:t(v.updatedAt,"Updated at")};}
export function normalizeAssetOverrideRecord(v:AssetOverrideRecord):AssetOverrideRecord{ if(v.customizationTarget.sourceKind==="system-owned-asset"&&v.overrideScope!=="system-derived") throw new Error("System-owned sources require system-derived scope."); return {...v,overrideId:normalizeAssetOverrideId(v.overrideId),targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),customizationTarget:normalizeAssetCustomizationTarget(v.customizationTarget),baseAssetReference:normalizeAssetReference(v.baseAssetReference),status:normalizeAssetOverrideStatus(v.status),overrideValues:normalizeSafeAssetEditableFieldPatch(v.overrideValues),createdAt:t(v.createdAt,"Created at"),updatedAt:t(v.updatedAt,"Updated at")};}
export const normalizeCreateWorkspaceAuthoredAssetCommand=(v:CreateWorkspaceAuthoredAssetCommand)=>({...v,workspaceId:createWorkspaceId(v.workspaceId),initialEditableValues:normalizeSafeAssetEditableFieldPatch(v.initialEditableValues),...(v.baseTarget?{baseTarget:normalizeAssetCustomizationTarget(v.baseTarget)}:{})});
export const normalizeCreateAssetDraftCommand=(v:CreateAssetDraftCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),...(v.baseTarget?{baseTarget:normalizeAssetCustomizationTarget(v.baseTarget)}:{}),draftEditableValues:normalizeSafeAssetEditableFieldPatch(v.draftEditableValues)});
export const normalizeUpdateAssetDraftCommand=(v:UpdateAssetDraftCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),draftId:normalizeAssetDraftId(v.draftId),draftEditablePatch:normalizeSafeAssetEditableFieldPatch(v.draftEditablePatch)});
export const normalizePublishAssetDraftCommand=(v:PublishAssetDraftCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),draftId:normalizeAssetDraftId(v.draftId),...(v.expectedBaseRevision?{expectedBaseRevision:t(v.expectedBaseRevision,"Expected base revision")}:{})});
export const normalizeCreateAssetOverrideCommand=(v:CreateAssetOverrideCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),target:normalizeAssetCustomizationTarget(v.target),overrideValues:normalizeSafeAssetEditableFieldPatch(v.overrideValues)});
export const normalizeUpdateAssetOverrideCommand=(v:UpdateAssetOverrideCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),overrideId:normalizeAssetOverrideId(v.overrideId),overrideValues:normalizeSafeAssetEditableFieldPatch(v.overrideValues)});
export const normalizeDisableAssetOverrideCommand=(v:DisableAssetOverrideCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),overrideId:normalizeAssetOverrideId(v.overrideId)});
export const normalizeResolveAssetCustomizationConflictCommand=(v:ResolveAssetCustomizationConflictCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),...(v.authoredAssetId?{authoredAssetId:normalizeAuthoredAssetId(v.authoredAssetId)}:{}),...(v.revisionId?{revisionId:normalizeAssetRevisionId(v.revisionId)}:{}),...(v.overrideId?{overrideId:normalizeAssetOverrideId(v.overrideId)}:{})});
