export type PlanSummaryViewModel={id:string;name:string;statusLabel:string;nodes:number;relationships:number;missing:number};
export type PlanNodeViewModel={id:string;projectionId:string;label:string;statusLabel:string};
export type PlanRelationshipViewModel={id:string;sourceNodeId:string;targetNodeId:string;kindLabel:string;statusLabel:string};
export type PlanDetailViewModel={id:string;name:string;statusLabel:string;nodes:PlanNodeViewModel[];relationships:PlanRelationshipViewModel[];messages:string[]};
export type AssetOptionViewModel={id:string;label:string};
const planStatus:Record<string,string>={draft:'Draft',valid:'Ready for planning',blocked:'Needs attention',conflicted:'Needs attention',stale:'Refresh needed',unsupported:'Not supported',invalid:'Needs attention',archived:'Needs attention'};
const nodeStatus:Record<string,string>={'ready-for-planning':'Ready for planning',ready:'Ready for planning',planned:'Ready for planning',blocked:'Needs attention',conflicted:'Needs attention','missing-projection':'Missing requirement','stale-projection':'Refresh needed',unsupported:'Not supported',invalid:'Needs attention',disabled:'Not supported'};
const relStatus:Record<string,string>={compatible:'Ready for planning',unknown:'Needs attention',blocked:'Needs attention',conflicted:'Needs attention','missing-dependency':'Missing requirement',unsupported:'Not supported',stale:'Refresh needed',invalid:'Needs attention'};
const relKind:Record<string,string>={'depends-on':'Depends on','feeds-into':'Feeds into',configures:'Configures','uses-model':'Uses model','uses-data':'Uses data','produces-output':'Produces output','requires-capability':'Requires capability',supports:'Supports'};
const blockedAssetStatuses = new Set(['blocked','conflicted','stale','disabled','unsupported','invalid','source-missing','draft-only']);
const safe=(value:unknown,fallback:string)=>typeof value==='string'&&value.trim()?value.trim():fallback;
const mapStatus=(table:Record<string,string>,value:unknown)=>table[String(value??'').trim()]??'Needs attention';
export const sanitizeMessage=(value:unknown)=>safe(value,'Needs attention.').replace(/(token|secret|path|base64|workflow|prompt|payload|provider|command|env|ipc|repository)/ig,'[hidden]').slice(0,180);
export function mapPlanSummary(value:any):PlanSummaryViewModel{const s=value?.summary??value; const id=S(s?.planId); if(!id) return {id:'',name:'Plan',statusLabel:'Needs attention',nodes:0,relationships:0,missing:0}; return {id,name:safe(s?.name,'Plan'),statusLabel:mapStatus(planStatus,s?.status),nodes:Number(s?.nodesCount??s?.planningSummary?.totalNodes??s?.totalNodes??0),relationships:Number(s?.relationshipsCount??s?.planningSummary?.totalRelationships??s?.totalRelationships??0),missing:Number(s?.missingDependencyCount??s?.planningSummary?.missingDependencyCount??0)};}
const S=(v:unknown)=>typeof v==='string'?v.trim():'';
export function mapPlanDetail(value:any):PlanDetailViewModel{const summary=value?.summary??{}; const planId=S(summary?.planId); const nodes=(Array.isArray(value?.nodes)?value.nodes:[]).map((n:any)=>{const id=S(n?.nodeId); const projectionId=S(n?.selectedProjectionId); if(!id||!projectionId) return undefined; return {id,projectionId,label:safe(n?.safeLabel,'Asset'),statusLabel:mapStatus(nodeStatus,n?.status)};}).filter(Boolean) as PlanNodeViewModel[];
const relationships=(Array.isArray(value?.relationships)?value.relationships:[]).map((r:any)=>{const id=S(r?.relationshipId); const sourceNodeId=S(r?.sourceNodeId); const targetNodeId=S(r?.targetNodeId); if(!id||!sourceNodeId||!targetNodeId) return undefined; return {id,sourceNodeId,targetNodeId,kindLabel:relKind[S(r?.kind)]??'Connection',statusLabel:mapStatus(relStatus,r?.compatibilityStatus)};}).filter(Boolean) as PlanRelationshipViewModel[];
const messages=[...(value?.blockers??[]),...(value?.diagnostics??[])].map((x:any)=>sanitizeMessage(x?.message)).filter(Boolean).slice(0,8);
return {id:planId,name:safe(summary?.name,'Plan'),statusLabel:mapStatus(planStatus,summary?.status),nodes,relationships,messages};}
export function mapAvailableAssets(items:any[]):AssetOptionViewModel[]{return items.filter((x)=>!blockedAssetStatuses.has(String(x?.status??''))&&(String(x?.status??'')==='ready'||x?.planningConsumable===true||String(x?.readinessLabel??'').toLowerCase().includes('ready'))).map((x)=>({id:String(x?.projectionId??''),label:`${safe(x?.projectedFields?.['display-name']??x?.displayName,'Asset')} (${safe(x?.sourceKind,'Workspace')})`})).filter((x)=>x.id);}
