import { useEffect, useMemo, useState } from "react";
import { mapAvailableAssets, mapPlanDetail, mapPlanSummary } from "./assetPlansViewModel";
import { mapRuntimeSetup } from "../../runtime-readiness/components/runtimeSetupViewModel";
import { createThinClientRuntimeReadinessClient } from "../../runtime-readiness/api/thinClientRuntimeReadinessClient";
import { createThinClientExecutionPlansClient } from "../../execution-plans/api/thinClientExecutionPlansClient";
import { mapPreview } from "../../execution-plans/components/executionPlanPreviewViewModel";
import { TermWithHint } from "../../../../../../modules/ui/shared";

const REL_KINDS = [
  ["depends-on", "Depends on"],["feeds-into", "Feeds into"],["configures", "Configures"],["uses-model", "Uses model"],["uses-data", "Uses data"],["produces-output", "Produces output"],["requires-capability", "Requires capability"],["supports", "Supports"],
] as const;

export function AssetPlansTab({ workspaceId, client, projectionClient }: { workspaceId: string; client: any; projectionClient: any; }) {
 const [plans,setPlans]=useState<any[]>([]); const [selectedPlanId,setSelectedPlanId]=useState(''); const [detail,setDetail]=useState<any>(); const [available,setAvailable]=useState<any[]>([]);
 const [state,setState]=useState<"idle"|"loading"|"error">('idle'); const [message,setMessage]=useState(''); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [projectionId,setProjectionId]=useState('');
 const [sourceNodeId,setSourceNodeId]=useState(''); const [relationshipKind,setRelationshipKind]=useState('depends-on'); const [targetNodeId,setTargetNodeId]=useState(''); const runtimeClient=useMemo(()=>createThinClientRuntimeReadinessClient(),[]); const executionPlanClient=useMemo(()=>createThinClientExecutionPlansClient(),[]); const [setupBinding,setSetupBinding]=useState<any>(); const [setupInventory,setSetupInventory]=useState<any>(); const [latestPreview,setLatestPreview]=useState<any>(); const [previewDetail,setPreviewDetail]=useState<any>();
 const refreshPlans=async(selectId?:string)=>{setState('loading'); const r=await client.listPlanSummaries({targetWorkspaceId:workspaceId}); if(!r.ok){setState('error');setMessage(r.error.message); return;} const items=(r.value.summaries??[]).map(mapPlanSummary); setPlans(items); const next=selectId??selectedPlanId??items[0]?.id??''; setSelectedPlanId(next); setState('idle');};
 const refreshDetail=async(planId:string)=>{ if(!planId)return; const r=await client.readPlanDetail({targetWorkspaceId:workspaceId,planId}); if(!r.ok){setMessage(r.error.message); return;} setDetail(mapPlanDetail(r.value)); };
 const refreshSetup=async(planId:string)=>{ const inv=runtimeClient.summarizeInventory?await runtimeClient.summarizeInventory(workspaceId):undefined; if(inv?.ok) setSetupInventory(inv.value); const latest=runtimeClient.readLatestRuntimeReadinessForCompositionPlan?await runtimeClient.readLatestRuntimeReadinessForCompositionPlan({workspaceId,compositionPlanId:planId}):undefined; if(latest?.ok) setSetupBinding(latest.value); else setSetupBinding(undefined);};
 const refreshPreview=async(planId:string)=>{ if(!planId) return; const latest=executionPlanClient.readLatestExecutionPlanForCompositionPlan?await executionPlanClient.readLatestExecutionPlanForCompositionPlan({workspaceId,compositionPlanId:planId}):undefined; if(!latest?.ok){setLatestPreview(undefined); setPreviewDetail(undefined); return;} setLatestPreview(latest.value); const previewId=latest.value?.executionPlanId??latest.value?.plan?.executionPlanId; if(previewId && executionPlanClient.readExecutionPlanDetail){ const d=await executionPlanClient.readExecutionPlanDetail({workspaceId,executionPlanId:previewId}); if(d?.ok) setPreviewDetail(d.value); } };
 useEffect(()=>{void refreshPlans();},[workspaceId]); useEffect(()=>{void refreshDetail(selectedPlanId); void refreshSetup(selectedPlanId); void refreshPreview(selectedPlanId);},[selectedPlanId]);
 useEffect(()=>{(async()=>{const r=await projectionClient?.listProjections?.(workspaceId); if(!r?.ok) return; setAvailable(mapAvailableAssets(r.value.summaries??r.value.projections??r.value.items??[]));})();},[workspaceId,projectionClient]);
 const nodeLabel=useMemo(()=>new Map((detail?.nodes??[]).map((n:any)=>[n.id,n.label])),[detail]);
 const setup=mapRuntimeSetup(setupBinding, setupInventory);
 const canCreate=typeof runtimeClient.createBinding==='function' && (detail?.isValidForSetup===true || detail?.isValid===true || detail?.status==='valid');
 const canValidate=typeof runtimeClient.validateBinding==='function' && !!(setupBinding?.binding?.readinessBindingId||setupBinding?.readinessBindingId);
 const preview=mapPreview(latestPreview, previewDetail);
 const readinessBindingId=setupBinding?.summary?.readinessBindingId??setupBinding?.readinessBindingId??setupBinding?.binding?.readinessBindingId??"";
 const canPreparePreview=!!readinessBindingId && typeof executionPlanClient.createExecutionPlan==='function';
 const canCheckPreview=!!preview.id && typeof executionPlanClient.validateExecutionPlan==='function';
 
 return <section className="ui-stack ui-stack--sm"><h2>Plans</h2>
 <form onSubmit={async(e)=>{e.preventDefault(); const r=await client.createPlan({targetWorkspaceId:workspaceId,name:name.trim(),description:description.trim()||undefined}); if(!r.ok){setMessage(r.error.message);return;} const id=r.value.plan?.planId??r.value.planId; setMessage('Plan created.'); setName(''); setDescription(''); await refreshPlans(id); if(id) await refreshDetail(id);}} className="ui-panel ui-stack ui-stack--xs"><h3>Create plan</h3><p><small>A plan organizes assets before you build a system. Nothing runs from this screen.</small></p><label className="ui-stack ui-stack--sm"><span><TermWithHint termId="planName">Name</TermWithHint></span><input aria-label="Name" value={name} onChange={(e)=>setName(e.target.value)} /></label><label className="ui-stack ui-stack--sm"><span><TermWithHint termId="planDescription">Description</TermWithHint></span><input aria-label="Description" value={description} onChange={(e)=>setDescription(e.target.value)} /></label><button>Create plan</button></form>
 {state==='loading'?<p role="status">Loading plans...</p>:null}{state==='error'?<p role="alert">Unable to load plans right now.</p>:null}
 {!plans.length&&state==='idle'?<p>No plans yet. Create a plan to organize assets before building a system.</p>:null}
 <ul>{plans.map((p:any)=><li key={p.id}><button onClick={()=>setSelectedPlanId(p.id)}>{p.name}</button> — {p.statusLabel} — Nodes {p.nodes} · Connections {p.relationships} · Missing requirements {p.missing}</li>)}</ul>
 {detail?<section className="ui-panel ui-stack ui-stack--xs"><h3>Plan details</h3><p><strong>{detail.name}</strong> — {detail.statusLabel}</p><h4>Assets in this plan</h4>
 {client.addProjectionToPlan?<div><label className="ui-stack ui-stack--sm"><span><TermWithHint termId="asset">Asset to add</TermWithHint></span><select aria-label="Asset to add" value={projectionId} onChange={(e)=>setProjectionId(e.target.value)}><option value="">Select an asset</option>{available.map((a:any)=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label><button onClick={async()=>{const r=await client.addProjectionToPlan({targetWorkspaceId:workspaceId,planId:detail.id,projectionId}); setMessage(r.ok?'Added to plan.':r.error.message); if(r.ok){await refreshPlans(detail.id); await refreshDetail(detail.id);}}}>Add to plan</button></div>:<p>Adding assets to plans is not available yet.</p>}
 <ul>{(detail.nodes??[]).map((n:any)=><li key={n.id}>{n.label} — {n.statusLabel} {client.removeProjectionFromPlan?<button onClick={async()=>{if(!n.projectionId){setMessage('Adding assets to plans is not available yet.'); return;} const r=await client.removeProjectionFromPlan({targetWorkspaceId:workspaceId,planId:detail.id,projectionId:n.projectionId}); setMessage(r.ok?'Removed.':r.error.message); if(r.ok){await refreshPlans(detail.id); await refreshDetail(detail.id);}}}>Remove</button>:null}</li>)}</ul>
 <h4>Connections</h4>{client.connectNodes?<div><label className="ui-stack ui-stack--sm"><span><TermWithHint termId="asset">Source asset</TermWithHint></span><select aria-label="Source asset" value={sourceNodeId} onChange={(e)=>setSourceNodeId(e.target.value)}><option value="">Source</option>{detail.nodes.map((n:any)=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label className="ui-stack ui-stack--sm"><span><TermWithHint termId="connection">Relationship kind</TermWithHint></span><select aria-label="Relationship kind" value={relationshipKind} onChange={(e)=>setRelationshipKind(e.target.value)}>{REL_KINDS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="ui-stack ui-stack--sm"><span><TermWithHint termId="asset">Target asset</TermWithHint></span><select aria-label="Target asset" value={targetNodeId} onChange={(e)=>setTargetNodeId(e.target.value)}><option value="">Target</option>{detail.nodes.map((n:any)=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><button onClick={async()=>{const r=await client.connectNodes({targetWorkspaceId:workspaceId,planId:detail.id,sourceNodeId,kind:relationshipKind,targetNodeId}); setMessage(r.ok?'Connection added.':r.error.message); if(r.ok){await refreshPlans(detail.id); await refreshDetail(detail.id);}}}>Add connection</button></div>:<p>Connections are not available yet.</p>}
 <ul>{(detail.relationships??[]).map((rel:any)=><li key={rel.id}>{nodeLabel.get(rel.sourceNodeId)??'Asset'} {rel.kindLabel} {nodeLabel.get(rel.targetNodeId)??'Asset'} — {rel.statusLabel} {client.disconnectNodes?<button onClick={async()=>{const r=await client.disconnectNodes({targetWorkspaceId:workspaceId,planId:detail.id,relationshipId:rel.id}); setMessage(r.ok?'Connection removed.':r.error.message); if(r.ok){await refreshPlans(detail.id); await refreshDetail(detail.id);}}}>Remove connection</button>:null}</li>)}</ul>
 {client.validatePlan?<button onClick={async()=>{const r=await client.validatePlan({targetWorkspaceId:workspaceId,planId:detail.id}); setMessage(r.ok?'Plan checked.':r.error.message); if(r.ok){await refreshPlans(detail.id); await refreshDetail(detail.id);}}}>Check plan</button>:<p>Plan checking is not available yet.</p>}
 <h4>Setup</h4><p><small>Nothing runs from this screen.</small></p>{!setupBinding?<p>Setup has not been checked for this plan yet.</p>:<><p>{setup.statusLabel}{setup.needsAttention?' — Needs attention':''}</p><p>Missing requirement {setup.counts.missing} · Provider unavailable {setup.counts.unavailable} · Needs configuration {setup.counts.configuration} · Permission needed {setup.counts.permission} · Refresh needed {setup.counts.stale}</p><h5>Requirements</h5><ul>{setup.requirements.map((r:any,i:number)=><li key={i}>{r.label} · {r.capability} · {r.required} · {r.status} · Options {r.candidates}</li>)}</ul><h5>Available options</h5><ul>{setup.options.map((o:any,i:number)=><li key={i}>{o.label} · {o.kind} · {o.availability} · Capabilities {o.capabilityCount}</li>)}</ul><h5>Selected setup choices</h5><ul>{setup.selected.map((x:any,i:number)=><li key={i}>{x.requirement} · {x.choice} · {x.status}</li>)}</ul><h5>Issues to fix</h5><ul>{setup.issues.map((m:string,i:number)=><li key={i}>{m}</li>)}</ul><h5>Inventory summary</h5>{setup.inventory?<p>Known providers {setup.inventory.knownProviders} · Known capabilities {setup.inventory.knownCapabilities} · Available providers {setup.inventory.availableProviders} · Unavailable providers {setup.inventory.unavailableProviders} · Needs configuration {setup.inventory.needsConfiguration} · Permission needed {setup.inventory.permissionNeeded} · Refresh needed {setup.inventory.refreshNeeded}</p>:<p>Setup inventory is not available yet.</p>}</>}
{!setupBinding?(canCreate?<button onClick={async()=>{const r=await runtimeClient.createBinding({workspaceId,compositionPlanId:detail.id}); setMessage(r.ok?'Setup checked.':r.error.message); if(r.ok){setSetupBinding(r.value); await refreshSetup(detail.id);}}}>Check setup</button>:<p>Check the plan before checking setup.</p>):(canValidate?<button onClick={async()=>{const id=setupBinding?.summary?.readinessBindingId??setupBinding?.readinessBindingId; const r=await runtimeClient.validateBinding({workspaceId,readinessBindingId:id}); setMessage(r.ok?'Setup checked again.':r.error.message); if(r.ok){setSetupBinding(r.value); await refreshSetup(detail.id);}}}>Check setup again</button>:<p>Setup re-checking is not available yet.</p>)}<h5>Plan preview</h5><p><small>Prepare and check a preview for review. Nothing runs from this screen.</small></p>
 {!preview.id?<><p>No plan preview has been prepared yet.</p>{!readinessBindingId?<p>Check setup before preparing a preview.</p>:(canPreparePreview?<button onClick={async()=>{const r=await executionPlanClient.createExecutionPlan({workspaceId,runtimeReadinessBindingId:readinessBindingId}); setMessage(r.ok?'Preview prepared.':'Unable to prepare preview right now.'); if(r.ok) await refreshPreview(detail.id);}}>Prepare preview</button>:<p>Plan preview preparation is not available yet.</p>)}</>:<><p>{preview.statusLabel}</p><p>Planned steps {preview.counts.steps} · Missing input {preview.counts.missingInputs} · Missing output {preview.counts.missingOutputs} · Provider setup required {preview.counts.providerSetupRequired} · Safety review required {preview.counts.safetyReviewRequired} · Blockers {preview.counts.blockers} · Diagnostics {preview.counts.diagnostics}</p>{canCheckPreview?<button onClick={async()=>{const r=await executionPlanClient.validateExecutionPlan({workspaceId,executionPlanId:preview.id}); setMessage(r.ok?'Preview checked.':'Unable to check preview right now.'); if(r.ok) await refreshPreview(detail.id);}}>Check preview</button>:<p>Preview checking is not available yet.</p>}
 <h6>Planned steps</h6><ul>{preview.steps.map((step:any,i:number)=><li key={i}>{step.label} · {step.status}{step.summary?` · ${step.summary}`:''}</li>)}</ul>
 <h6>Estimates</h6><p>Compute {preview.estimates.computeCategory??'Not available'} · Storage {preview.estimates.storageCategory??'Not available'} · Duration {preview.estimates.durationCategory??'Not available'}</p>
 <h6>Issues to fix</h6>{preview.issues.length?<ul>{preview.issues.map((issue:string,i:number)=><li key={i}>{issue}</li>)}</ul>:<p>No issues to fix right now.</p>}
 </>}<h4>Messages / Needs attention</h4><ul>{(detail.messages??[]).map((m:string,i:number)=><li key={i}>{m}</li>)}</ul></section>:null}
 {message?<p role="status">{message}</p>:null}</section>;
}
