import { describe, expect, it } from "bun:test";
import { readSource } from "../../tests/testUtils";

describe("StudioShellPage contracts", () => {
  it("composes bounded shell panels and service orchestration", () => {
    const source = readSource("ui/pages/StudioShellPage.tsx");

    expect(source).toContain('data-testid="studio-shell-page"');
    expect(source).toContain("StudioShellService");
    expect(source).toContain("StudioShellPanel");
    expect(source).toContain("StudioShellValidationIssuesPanel");
    expect(source).toContain("Studio/session context");
    expect(source).toContain("Asset draft authoring");
    expect(source).toContain("Taxonomy / contract / provenance");
    expect(source).toContain("Dependencies");
    expect(source).toContain("Lifecycle / publish / version status");
    expect(source).toContain("StudioShellValidationIssuesPanel");
    expect(source).toContain("StudioShellExtensionRegistry");
    expect(source).toContain("getWorkflowStudioModeStateStore");
    expect(source).toContain("StudioAssetHostBoundary");
    expect(source).toContain("workflowStudioSurfaceAssetDefinition");
    expect(source).toContain("InlineAssetReturnStatuses.noSelection");
    expect(source).toContain("workflowModeRoute");
    expect(source).toContain("workflowEntryRoute");
    expect(source).toContain("WorkflowStudioEntryPaths");
    expect(source).toContain("workflowModeState");
    expect(source).toContain("studioRegistration");
    expect(source).toContain("shellTitle");
    expect(source).toContain("toolbarActions");
    expect(source).toContain("toolbarActionsToRender");
    expect(source).toContain("workflowModeToggleAction");
    expect(source).toContain("shouldShowLeftDrawerToggle");
    expect(source).toContain("useBlocker");
    expect(source).toContain("useBeforeUnload");
    expect(source).toContain("hasWorkflowUnsavedChanges");
    expect(source).toContain("hasWorkflowMetadataUnsavedChanges");
    expect(source).toContain("saveDraftFromAuthoringAsync");
    expect(source).toContain("workflowUnsavedNavigationBlocker");
    expect(source).toContain("getWorkflowStudioUnsavedPrompt");
    expect(source).toContain("Saving changes...");
    expect(source).toContain("Save failed");
    expect(source).toContain("Workflow metadata");
    expect(source).toContain("Workflow name");
    expect(source).toContain('label: workflowModeState.selectedModeId === "canvas" ? "Wizard" : "Canvas"');
    expect(source).toContain('data-testid="studio-shell-authoring-toolbar"');
    expect(source).toContain('data-testid="studio-shell-workflow-draft-status"');
    expect(source).toContain('data-testid="studio-shell-workflow-draft-status-badge"');
    expect(source).toContain("buildWorkflowStudioRunHistoryPath");
    expect(source).toContain("buildWorkflowStudioRunDetailPath");
    expect(source).toContain("View run history");
    expect(source).toContain('data-testid="studio-shell-left-drawer-toggle"');
    expect(source).toContain('data-testid="studio-shell-right-drawer-toggle"');
    expect(source).toContain("runToolbarAction(");
    expect(source).toContain("setWorkflowModeFromToolbar(");
    expect(source).toContain("buildCreateMetadata(");
    expect(source).toContain("renderExtensions(");
    expect(source).toContain("StudioShellExtensionSlots");
    expect(source).toContain("service.loadSnapshot");
    expect(source).toContain("service.createDraft");
    expect(source).toContain("service.updateDraft");
    expect(source).toContain("service.updateDependencies");
    expect(source).toContain("service.transitionLifecycle");
    expect(source).toContain("service.publishVersion");
    expect(source).toContain("service.validateDraft");
    expect(source).toContain("service.getPersistedWorkflow");
    expect(source).toContain("service.duplicatePersistedWorkflow");
    expect(source).toContain("service.assessWorkflowExecutionReadiness");
    expect(source).toContain("service.runWorkflowDraft");
    expect(source.indexOf("Asset draft authoring")).toBeLessThan(source.indexOf("ui-studio-shell__grid"));
  });
});
