import type { ConversationTurnRepositoryPort, AssistantResponseRepositoryPort } from '../../ports/conversations';
import type { ExecutionRunRepositoryPort, ExecutionEventRepositoryPort, ExecutionAttemptRepositoryPort } from '../../ports/execution-runs';
import { createWorkspaceId } from '../../../contracts/workspace';
import type { ConversationTurnActivityReadModel } from './conversation-read-model-types';

const SAFE_EVENT:Record<string,string>={'run-queued':'Run queued','attempt-started':'Invocation started','result-recorded':'Response recorded','run-succeeded':'Completed','run-failed':'Failed','cancellation-requested':'Cancellation requested','run-cancelled':'Cancelled','retry-requested':'Retry requested','retry-started':'Retry accepted'};
export class ConversationTurnActivityReadModelService {
constructor(private readonly turns:ConversationTurnRepositoryPort, private readonly responses:AssistantResponseRepositoryPort, private readonly runs:ExecutionRunRepositoryPort, private readonly attempts:ExecutionAttemptRepositoryPort, private readonly events:ExecutionEventRepositoryPort){}
async readActivity(request:{workspaceId:string; conversationSessionId:string; conversationTurnId:string}):Promise<ConversationTurnActivityReadModel>{ if(!request.workspaceId) return {ok:false,code:'workspace-required',message:'Workspace is required.'}; const ws=createWorkspaceId(request.workspaceId); const turn=await this.turns.getConversationTurnById(ws,request.conversationTurnId as any); if(!turn) return {ok:false,code:'turn-not-found',message:'Turn not found.'}; if(turn.conversationSessionId!==request.conversationSessionId) return {ok:false,code:'workspace-mismatch',message:'Turn does not belong to session.'}; const run=turn.executionRunId?await this.runs.getExecutionRunById(ws,turn.executionRunId):undefined; const events=run?await this.events.listExecutionEventsByRun(ws,run.id,50):{events:[]}; const attempt=run?await this.attempts.getLatestExecutionAttemptForRun(ws,run.id):undefined; const response=await this.responses.listAssistantResponsesByTurn(ws,turn.id);
return {ok:true,turnId:turn.id,turnStatus:turn.status,executionRunId:run?.id,executionStatus:run?.status,progressState:run?.progress?.phase ?? turn.status,failureCategory:run?.diagnostics[0]?.code,assistantResponseAvailable:response.some((r)=>r.status==='completed'),cancellation:{supported:false,available:false},retry:{supported:false,available:false,deferred:true},events:events.events.filter((e)=>SAFE_EVENT[e.kind]).map((e)=>({at:e.at,kind:e.kind,label:SAFE_EVENT[e.kind]})),createdAt:turn.createdAt,updatedAt:turn.updatedAt,completedAt:turn.completedAt}; }
}
