import type { CreateExecutionPlanUseCase, ValidateExecutionPlanUseCase } from "../../../../application/use-cases/execution-plans";
import type { ExecutionPlanReadModelService } from "../../../../application/services/execution-plans";
import type { IpcMainHandlePort } from "../ipcMainHandlePort";
import { DESKTOP_EXECUTION_PLANS_ARCHIVE_PLAN_REQUEST_CHANNEL, DESKTOP_EXECUTION_PLANS_CREATE_PLAN_REQUEST_CHANNEL, DESKTOP_EXECUTION_PLANS_LIST_FOR_COMPOSITION_PLAN_REQUEST_CHANNEL, DESKTOP_EXECUTION_PLANS_LIST_FOR_RUNTIME_READINESS_BINDING_REQUEST_CHANNEL, DESKTOP_EXECUTION_PLANS_LIST_NEEDING_ATTENTION_REQUEST_CHANNEL, DESKTOP_EXECUTION_PLANS_LIST_SUMMARIES_REQUEST_CHANNEL, DESKTOP_EXECUTION_PLANS_READ_DETAIL_REQUEST_CHANNEL, DESKTOP_EXECUTION_PLANS_READ_LATEST_FOR_COMPOSITION_PLAN_REQUEST_CHANNEL, DESKTOP_EXECUTION_PLANS_READ_LATEST_FOR_RUNTIME_READINESS_BINDING_REQUEST_CHANNEL, DESKTOP_EXECUTION_PLANS_SUMMARIZE_WORKSPACE_REQUEST_CHANNEL, DESKTOP_EXECUTION_PLANS_VALIDATE_PLAN_REQUEST_CHANNEL } from "../../../../contracts/ipc";
export interface RegisterExecutionPlansIpcDependencies { ipcMain: IpcMainHandlePort; executionPlans: { create: CreateExecutionPlanUseCase; validate: ValidateExecutionPlanUseCase; readModel: ExecutionPlanReadModelService; archive?: { execute: (c:{workspaceId:string;executionPlanId:string})=>Promise<unknown> }; }; }
const ok=(r:any,v:unknown)=>({ok:true,requestId:r?.requestId,correlationId:r?.correlationId,value:v});
const fail=(r:any,code:string,message:string)=>({ok:false,requestId:r?.requestId,correlationId:r?.correlationId,error:{code,message}});
export function registerExecutionPlansIpc({ipcMain,executionPlans}: RegisterExecutionPlansIpcDependencies): void {
 const req=(fn:(p:any)=>Promise<unknown>,validate:(p:any)=>string|undefined)=>(async (_e:unknown,r:any)=>{const m=validate(r?.payload);if(m) return fail(r,'validation',m); try{return ok(r, await fn(r.payload));}catch{return fail(r,'internal','Unable to complete request.');}});
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_CREATE_PLAN_REQUEST_CHANNEL.value, req((p)=>executionPlans.create.execute(p), (p)=>!p?.workspaceId||!p?.runtimeReadinessBindingId?'Workspace id and runtime readiness binding id are required.':undefined));
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_VALIDATE_PLAN_REQUEST_CHANNEL.value, req((p)=>executionPlans.validate.execute(p),(p)=>!p?.workspaceId||!p?.executionPlanId?'Workspace id and execution plan id are required.':undefined));
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_ARCHIVE_PLAN_REQUEST_CHANNEL.value, async (_e,r:any)=>{if(!executionPlans.archive) return fail(r,'unavailable','Execution plan archive is not available.'); const p=r?.payload; if(!p?.workspaceId||!p?.executionPlanId) return fail(r,'validation','Workspace id and execution plan id are required.'); try{return ok(r,await executionPlans.archive.execute(p));}catch{return fail(r,'internal','Unable to complete request.');}});
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_LIST_SUMMARIES_REQUEST_CHANNEL.value, req((p)=>executionPlans.readModel.listExecutionPlanSummaries(p),(p)=>!p?.workspaceId?'Workspace id is required.':undefined));
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_READ_DETAIL_REQUEST_CHANNEL.value, req((p)=>executionPlans.readModel.readExecutionPlanDetail(p),(p)=>!p?.workspaceId||!p?.executionPlanId?'Workspace id and execution plan id are required.':undefined));
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_LIST_FOR_COMPOSITION_PLAN_REQUEST_CHANNEL.value, req((p)=>executionPlans.readModel.listExecutionPlansForCompositionPlan(p),(p)=>!p?.workspaceId||!p?.compositionPlanId?'Workspace id and composition plan id are required.':undefined));
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_READ_LATEST_FOR_COMPOSITION_PLAN_REQUEST_CHANNEL.value, req((p)=>executionPlans.readModel.readLatestExecutionPlanForCompositionPlan(p),(p)=>!p?.workspaceId||!p?.compositionPlanId?'Workspace id and composition plan id are required.':undefined));
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_LIST_FOR_RUNTIME_READINESS_BINDING_REQUEST_CHANNEL.value, req((p)=>executionPlans.readModel.listExecutionPlansForRuntimeReadinessBinding(p),(p)=>!p?.workspaceId||!p?.runtimeReadinessBindingId?'Workspace id and runtime readiness binding id are required.':undefined));
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_READ_LATEST_FOR_RUNTIME_READINESS_BINDING_REQUEST_CHANNEL.value, req((p)=>executionPlans.readModel.readLatestExecutionPlanForRuntimeReadinessBinding(p),(p)=>!p?.workspaceId||!p?.runtimeReadinessBindingId?'Workspace id and runtime readiness binding id are required.':undefined));
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_LIST_NEEDING_ATTENTION_REQUEST_CHANNEL.value, req((p)=>executionPlans.readModel.listExecutionPlansNeedingAttention(p),(p)=>!p?.workspaceId?'Workspace id is required.':undefined));
 ipcMain.handle(DESKTOP_EXECUTION_PLANS_SUMMARIZE_WORKSPACE_REQUEST_CHANNEL.value, req((p)=>executionPlans.readModel.summarizeWorkspaceExecutionPlans(p),(p)=>!p?.workspaceId?'Workspace id is required.':undefined));
}
