import { useEffect, useMemo, useRef, useState } from "react";
import type { ModelBrowseItem, ModelBrowseProvider, ModelInventoryRecord } from "../../../../../../modules/contracts/model";
import { createApiModelManagementClient, type ModelManagementApiClient } from "../api/apiModelManagementClient";
import { logThinClientDiagnostic, subscribeThinClientDiagnostics, type ThinClientDiagnosticEvent } from "../../../diagnostics/thinClientDiagnostics";

type SupportedProvider = Extract<ModelBrowseProvider, "huggingface">;

export function useModelManagementFeature(client: ModelManagementApiClient = createApiModelManagementClient()) {
  const [query, setQuery] = useState("");
  const [provider, setProvider] = useState<SupportedProvider>("huggingface");
  const [browseResults, setBrowseResults] = useState<ModelBrowseItem[]>([]);
  const [inventory, setInventory] = useState<ModelInventoryRecord[]>([]);
  const [details, setDetails] = useState<Record<string, unknown> | undefined>();
  const [status, setStatus] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [browsing, setBrowsing] = useState(false);
  const [inventoryLoading, setInventoryLoading] = useState(false);
  const [downloadingModelId, setDownloadingModelId] = useState<string | undefined>();
  const [deletingModelRecordId, setDeletingModelRecordId] = useState<string | undefined>();
  const [diagnostics, setDiagnostics] = useState<ThinClientDiagnosticEvent[]>([]);
  const mountedRef = useRef(true); const browseRequestRef = useRef(0); const inventoryRequestRef = useRef(0); const detailsRequestRef = useRef(0); const downloadRequestRef = useRef(0); const deleteRequestRef = useRef(0);
  useEffect(() => { mountedRef.current = true; return () => { mountedRef.current = false; }; }, []);
  useEffect(() => subscribeThinClientDiagnostics(setDiagnostics), []);
  const loading = useMemo(() => browsing || inventoryLoading || Boolean(downloadingModelId) || Boolean(deletingModelRecordId), [browsing, inventoryLoading, downloadingModelId, deletingModelRecordId]);

  const refreshInventory = async () => { logThinClientDiagnostic("info",{feature:"model-management",operation:"list",phase:"start",message:"Inventory refresh started",metadata:{provider,endpoint:"/api/model/list"}}); const requestId = ++inventoryRequestRef.current; setInventoryLoading(true); setError(""); try { const result = await Promise.race([client.listModels({ provider }), new Promise((_,rej)=>setTimeout(()=>rej(new Error("timeout")),12000))]) as Awaited<ReturnType<typeof client.listModels>>; if (!mountedRef.current || requestId !== inventoryRequestRef.current) { logThinClientDiagnostic("info",{feature:"model-management",operation:"list",phase:"state.ignored",message:"Inventory refresh result ignored",metadata:{provider,requestId,currentRequestId:inventoryRequestRef.current,mounted:mountedRef.current,reason:mountedRef.current?"stale-request":"unmounted"}}); return; } setInventory(result.models); logThinClientDiagnostic("info",{feature:"model-management",operation:"list",phase:"state.updated",message:"Inventory state updated",metadata:{provider,requestId,currentRequestId:inventoryRequestRef.current,mounted:mountedRef.current,stale:false,resultCount:result.models.length}}); logThinClientDiagnostic("info",{feature:"model-management",operation:"list",phase:"success",message:"Inventory refresh completed",metadata:{provider,endpoint:"/api/model/list",resultCount:result.models.length}}); } catch (e) { if (!mountedRef.current || requestId !== inventoryRequestRef.current) return; const message = e instanceof Error ? e.message : "Inventory refresh failed."; logThinClientDiagnostic("warn",{feature:"model-management",operation:"list",phase:"failure",message,metadata:{provider,endpoint:"/api/model/list"}}); setError("Unable to load server model inventory. You can still browse Hugging Face models."); } finally { if (mountedRef.current && requestId === inventoryRequestRef.current) setInventoryLoading(false); } };
  useEffect(() => { void refreshInventory(); }, []);

  const browse = async () => { const trimmedQuery = query.trim(); if (!trimmedQuery) { setError("Enter a search term to browse models."); return; } const requestId = ++browseRequestRef.current; logThinClientDiagnostic("info",{feature:"model-management",operation:"browse",phase:"start",message:"Browse started",metadata:{provider,query:trimmedQuery,endpoint:"/api/model/browse"}}); setBrowsing(true); setError(""); setStatus(""); try { const res = await client.browseModels({ provider, query: trimmedQuery }); if (!mountedRef.current || requestId !== browseRequestRef.current) { logThinClientDiagnostic("info",{feature:"model-management",operation:"browse",phase:"state.ignored",message:"Browse result ignored",metadata:{provider,query:trimmedQuery,requestId,currentRequestId:browseRequestRef.current,mounted:mountedRef.current,reason:mountedRef.current?"stale-request":"unmounted"}}); return; } setBrowseResults(res.models); setStatus(`Loaded ${res.models.length} models.`);
      logThinClientDiagnostic("info",{feature:"model-management",operation:"browse",phase:"state.updated",message:"Browse state updated",metadata:{provider,query:trimmedQuery,requestId,currentRequestId:browseRequestRef.current,mounted:mountedRef.current,stale:false,resultCount:res.models.length}});
      logThinClientDiagnostic("info",{feature:"model-management",operation:"browse",phase:"success",message:`Browse success: ${res.models.length} models.`,metadata:{provider,query:trimmedQuery,endpoint:"/api/model/browse",resultCount:res.models.length}}); } catch (e) { if (!mountedRef.current || requestId !== browseRequestRef.current) return; const message = e instanceof Error ? e.message : "Browse failed."; logThinClientDiagnostic("warn",{feature:"model-management",operation:"browse",phase:"failure",message,metadata:{provider,query:trimmedQuery,endpoint:"/api/model/browse"}}); setError(message); } finally { if (mountedRef.current && requestId === browseRequestRef.current) setBrowsing(false); } };

  const viewDetails = async (modelId: string) => { const normalizedModelId = modelId.trim(); if (!normalizedModelId) { setError("Model details require a non-empty model id."); return; } const requestId = ++detailsRequestRef.current; setError(""); logThinClientDiagnostic("info",{feature:"model-management",operation:"details",phase:"start",message:"Details fetch started",metadata:{provider,modelId:normalizedModelId,endpoint:"/api/model/details"}}); try { const res = await client.getModelDetails({ provider, modelId: normalizedModelId }); if (!mountedRef.current || requestId !== detailsRequestRef.current) return; setDetails(res.model as unknown as Record<string, unknown>); logThinClientDiagnostic("info",{feature:"model-management",operation:"details",phase:"success",message:"Details fetch completed",metadata:{provider,modelId:normalizedModelId,endpoint:"/api/model/details"}}); } catch (e) { if (!mountedRef.current || requestId !== detailsRequestRef.current) return; const message = e instanceof Error ? e.message : "Details failed."; logThinClientDiagnostic("warn",{feature:"model-management",operation:"details",phase:"failure",message,metadata:{provider,modelId:normalizedModelId,endpoint:"/api/model/details"}}); setError(message); } };

  const saveReference = async (item: ModelBrowseItem) => { if (!item.provider || !item.modelId?.trim()) { setError("Save requires a provider and model id."); return; } setError(""); logThinClientDiagnostic("info",{feature:"model-management",operation:"save-reference",phase:"start",message:"Save reference started",metadata:{provider:item.provider,modelId:item.modelId,endpoint:"/api/model/reference/save"}}); try { await client.saveModelReference({ ...item, modelId: item.modelId.trim() }); setStatus(`Saved ${item.displayName}.`); await refreshInventory(); logThinClientDiagnostic("info",{feature:"model-management",operation:"save-reference",phase:"success",message:"Save reference completed",metadata:{provider:item.provider,modelId:item.modelId,endpoint:"/api/model/reference/save"}}); } catch (e) { const message = e instanceof Error ? e.message : "Save failed."; logThinClientDiagnostic("warn",{feature:"model-management",operation:"save-reference",phase:"failure",message,metadata:{provider:item.provider,modelId:item.modelId,endpoint:"/api/model/reference/save"}}); setError(message); } };

  const download = async (item: ModelBrowseItem) => { if (!item.provider || !item.modelId?.trim()) { setError("Download requires a provider and model id."); return; } const requestId = ++downloadRequestRef.current; setDownloadingModelId(item.modelId); setError(""); logThinClientDiagnostic("info",{feature:"model-management",operation:"download",phase:"start",message:"Download started",metadata:{provider:item.provider,modelId:item.modelId,endpoint:"/api/model/download"}}); try { const result = await client.downloadModel({ ...item, modelId: item.modelId.trim() }); if (!mountedRef.current || requestId !== downloadRequestRef.current) return; const downloadState = result.download.downloaded ? (result.download.fromCache ? "Already available" : "Downloaded") : "Reference saved"; setStatus(`${item.displayName}: ${downloadState}.`); await refreshInventory(); logThinClientDiagnostic("info",{feature:"model-management",operation:"download",phase:"success",message:"Download completed",metadata:{provider:item.provider,modelId:item.modelId,endpoint:"/api/model/download",downloaded:result.download.downloaded}}); } catch (e) { if (!mountedRef.current || requestId !== downloadRequestRef.current) return; const message = e instanceof Error ? e.message : "Download failed."; logThinClientDiagnostic("warn",{feature:"model-management",operation:"download",phase:"failure",message,metadata:{provider:item.provider,modelId:item.modelId,endpoint:"/api/model/download"}}); setError(message); } finally { if (mountedRef.current && requestId === downloadRequestRef.current) setDownloadingModelId(undefined); } };

  const clear = () => { setQuery(""); setBrowseResults([]); setStatus(""); setError(""); };
  const deleteRecord = async (modelRecordId: string) => { const normalized = modelRecordId.trim(); if (!normalized) { setError("Delete requires a model record id."); return; } if (!window.confirm("Delete this model record?")) return; const requestId = ++deleteRequestRef.current; setDeletingModelRecordId(normalized); setError(""); try { await client.deleteModelRecord({ modelRecordId: normalized, deleteLocalFiles: false }); await refreshInventory(); setStatus("Model record deleted."); } catch (e) { if (!mountedRef.current || requestId !== deleteRequestRef.current) return; setError(e instanceof Error ? e.message : "Delete failed."); } finally { if (mountedRef.current && requestId === deleteRequestRef.current) setDeletingModelRecordId(undefined); } };
  return { query, setQuery, provider, setProvider, browseResults, inventory, details, status, error, loading, browsing, inventoryLoading, downloadingModelId, deletingModelRecordId, diagnostics, browse, clear, refreshInventory, viewDetails, saveReference, download, deleteRecord };
}
