import type { AssetCompositionNodeId, AssetCompositionPlanId, AssetCompositionRelationshipId } from "../asset-composition";
import type { WorkspaceId } from "../workspace";
import type { RuntimeCapabilityKind, RuntimeProviderKind } from "./runtime-readiness-capability";
import type { RuntimeReadinessBlocker, RuntimeReadinessDiagnostic } from "./runtime-readiness-diagnostics";
import type { RuntimeBindingCandidateId, RuntimeBindingId, RuntimeCapabilityId, RuntimeInventorySourceId, RuntimeProviderCandidateId, RuntimeProviderId, RuntimeReadinessBindingId, RuntimeRequirementId } from "./runtime-readiness-identity";
import type { RuntimeReadinessProvenanceEvent } from "./runtime-readiness-provenance";
import type { RuntimeBindingMatchStatus, RuntimeBindingStatus, RuntimeProviderAvailabilityStatus, RuntimeReadinessStatus } from "./runtime-readiness-status";
export type RuntimeInventorySourceKind="desktop-host"|"server-host"|"manual"|"configured-provider"|"system-default";
export type RuntimeInventoryStatus="checked"|"stale"|"blocked"|"invalid";
export type RuntimeSafeMetadataValue = string | number | boolean | null | RuntimeReadinessSafeMetadata;
export type RuntimeReadinessSafeMetadata = { readonly [key: string]: RuntimeSafeMetadataValue };
export interface RuntimeRequirement{readonly requirementId:RuntimeRequirementId;readonly targetWorkspaceId:WorkspaceId;readonly compositionPlanId:AssetCompositionPlanId;readonly sourceNodeId?:AssetCompositionNodeId;readonly sourceRelationshipId?:AssetCompositionRelationshipId;readonly capabilityKind:RuntimeCapabilityKind;readonly capabilityKey:string;readonly isRequired:boolean;readonly label:string;readonly summary?:string;readonly matchingConstraints?:RuntimeReadinessSafeMetadata;readonly diagnostics:readonly RuntimeReadinessDiagnostic[];readonly blockers:readonly RuntimeReadinessBlocker[];}
export interface RuntimeCapability{readonly capabilityId:RuntimeCapabilityId;readonly capabilityKind:RuntimeCapabilityKind;readonly capabilityKey:string;readonly label:string;readonly summary?:string;readonly providerKind?:RuntimeProviderKind;readonly availabilityStatus:RuntimeProviderAvailabilityStatus;readonly configurationStatus?:RuntimeProviderAvailabilityStatus;readonly safeMetadata?:RuntimeReadinessSafeMetadata;readonly diagnostics:readonly RuntimeReadinessDiagnostic[];readonly blockers:readonly RuntimeReadinessBlocker[];}
export interface RuntimeProviderCandidate{readonly providerCandidateId:RuntimeProviderCandidateId;readonly providerId?:RuntimeProviderId;readonly providerKind:RuntimeProviderKind;readonly inventorySourceId:RuntimeInventorySourceId;readonly capabilities:readonly RuntimeCapability[];readonly availabilityStatus:RuntimeProviderAvailabilityStatus;readonly configurationStatus?:RuntimeProviderAvailabilityStatus;readonly displayLabel:string;readonly diagnosticSummary?:string;readonly diagnostics:readonly RuntimeReadinessDiagnostic[];readonly blockers:readonly RuntimeReadinessBlocker[];}
export interface RuntimeInventory{readonly targetWorkspaceId:WorkspaceId;readonly inventorySourceId:RuntimeInventorySourceId;readonly inventorySourceKind:RuntimeInventorySourceKind;readonly discoveredProviderCandidates:readonly RuntimeProviderCandidate[];readonly discoveredCapabilities:readonly RuntimeCapability[];readonly inventoryStatus:RuntimeInventoryStatus;readonly diagnostics:readonly RuntimeReadinessDiagnostic[];readonly blockers:readonly RuntimeReadinessBlocker[];readonly checkedAt?:string;}
export interface RuntimeBindingCandidate{readonly bindingCandidateId:RuntimeBindingCandidateId;readonly targetWorkspaceId:WorkspaceId;readonly requirementId:RuntimeRequirementId;readonly providerCandidateId:RuntimeProviderCandidateId;readonly capabilityId?:RuntimeCapabilityId;readonly matchStatus:RuntimeBindingMatchStatus;readonly matchQuality?:number;readonly blockers:readonly RuntimeReadinessBlocker[];readonly diagnostics:readonly RuntimeReadinessDiagnostic[];readonly label?:string;readonly summary?:string;readonly createdAt?:string;readonly updatedAt?:string;}
export interface RuntimeBinding{readonly bindingId:RuntimeBindingId;readonly targetWorkspaceId:WorkspaceId;readonly readinessBindingId:RuntimeReadinessBindingId;readonly requirementId:RuntimeRequirementId;readonly selectedProviderCandidateId:RuntimeProviderCandidateId;readonly selectedCapabilityId?:RuntimeCapabilityId;readonly status:RuntimeBindingStatus;readonly safeConfigurationReference?:RuntimeReadinessSafeMetadata;readonly diagnostics:readonly RuntimeReadinessDiagnostic[];readonly blockers:readonly RuntimeReadinessBlocker[];readonly provenance:readonly RuntimeReadinessProvenanceEvent[];readonly createdAt:string;readonly updatedAt:string;}
export interface RuntimeReadinessBinding{readonly readinessBindingId:RuntimeReadinessBindingId;readonly targetWorkspaceId:WorkspaceId;readonly compositionPlanId:AssetCompositionPlanId;readonly compositionPlanValidationAt?:string;readonly status:RuntimeReadinessStatus;readonly requirements:readonly RuntimeRequirement[];readonly providerCandidates:readonly RuntimeProviderCandidate[];readonly bindingCandidates:readonly RuntimeBindingCandidate[];readonly bindings:readonly RuntimeBinding[];readonly blockers:readonly RuntimeReadinessBlocker[];readonly diagnostics:readonly RuntimeReadinessDiagnostic[];readonly provenance:readonly RuntimeReadinessProvenanceEvent[];readonly createdAt:string;readonly updatedAt:string;readonly archivedAt?:string;}

export function normalizeRuntimeInventorySourceKind(value: string): RuntimeInventorySourceKind {
  const normalized = value.trim().toLowerCase() as RuntimeInventorySourceKind;
  if (!["desktop-host", "server-host", "manual", "configured-provider", "system-default"].includes(normalized)) {
    throw new Error("Runtime inventory source kind is invalid.");
  }
  return normalized;
}
