import type { RuntimeInventoryRepositoryPort, RuntimeReadinessBindingRepositoryPort } from "../../../application/ports/runtime-readiness";
import { normalizeAssetCompositionPlanId } from "../../../contracts/asset-composition";
import { normalizeRuntimeInventory, normalizeRuntimeInventorySourceId, normalizeRuntimeReadinessBinding, normalizeRuntimeReadinessStatus, type RuntimeInventory, type RuntimeReadinessBinding } from "../../../contracts/runtime-readiness";
import { pageRecords, textValuesMatch } from "../user-library/local-user-library-repository-helpers";
import { LocalRuntimeReadinessRecordStore } from "./local-runtime-readiness-record-store";
const sortBinding=(a:RuntimeReadinessBinding,b:RuntimeReadinessBinding)=>b.updatedAt.localeCompare(a.updatedAt)||a.readinessBindingId.localeCompare(b.readinessBindingId);
const sortInventory=(a:RuntimeInventory,b:RuntimeInventory)=>(b.checkedAt??"").localeCompare(a.checkedAt??"")||a.inventorySourceId.localeCompare(b.inventorySourceId);

export function createLocalRuntimeReadinessBindingRepositoryAdapter(o:{rootDir:string; now?:()=>string}): RuntimeReadinessBindingRepositoryPort { const store=new LocalRuntimeReadinessRecordStore(o); return {
  async saveRuntimeReadinessBindingRecord(record){const n=normalizeRuntimeReadinessBinding(record); const all=[...(await store.readBindings<RuntimeReadinessBinding>()).filter((x)=>!(x.targetWorkspaceId===n.targetWorkspaceId&&x.readinessBindingId===n.readinessBindingId)),n].sort(sortBinding); await store.writeBindings(all); return n;},
  async updateRuntimeReadinessBindingRecord(record){ return this.saveRuntimeReadinessBindingRecord(record); },
  async readRuntimeReadinessBindingRecord(targetWorkspaceId, readinessBindingId){ const safeId=readinessBindingId.trim(); if(!targetWorkspaceId) throw new Error("targetWorkspaceId is required."); return (await store.readBindings<RuntimeReadinessBinding>()).map(normalizeRuntimeReadinessBinding).find((x)=>x.targetWorkspaceId===targetWorkspaceId&&x.readinessBindingId===safeId); },
  async listRuntimeReadinessBindingRecords(query){ if(!query.targetWorkspaceId) throw new Error("targetWorkspaceId is required."); const safeStatus=query.status?normalizeRuntimeReadinessStatus(query.status):undefined; const safePlan=query.compositionPlanId?normalizeAssetCompositionPlanId(query.compositionPlanId):undefined; const records=(await store.readBindings<RuntimeReadinessBinding>()).map(normalizeRuntimeReadinessBinding).filter((x)=>x.targetWorkspaceId===query.targetWorkspaceId&&(!safeStatus||x.status===safeStatus)&&(!safePlan||x.compositionPlanId===safePlan)&&(!query.requiredCapabilityKind||x.requirements.some((r)=>r.capabilityKind===query.requiredCapabilityKind))&&(!query.providerAvailabilityStatus||x.providerCandidates.some((p)=>p.availabilityStatus===query.providerAvailabilityStatus))&&(!query.bindingStatus||x.bindings.some((b)=>b.status===query.bindingStatus))&&(!query.blockedOnly||x.blockers.length>0)&&(!query.missingRequirementsOnly||x.status==="missing-requirements")&&(!query.providerUnavailableOnly||x.status==="provider-unavailable")&&(!query.configurationRequiredOnly||x.status==="configuration-required")&&(!query.permissionRequiredOnly||x.status==="permission-required")&&(!query.staleOnly||x.status==="stale")&&(query.archived===undefined||(query.archived?Boolean(x.archivedAt):!x.archivedAt))&&(!query.createdAfter||x.createdAt>=query.createdAfter)&&(!query.createdBefore||x.createdAt<=query.createdBefore)&&(!query.updatedAfter||x.updatedAt>=query.updatedAfter)&&(!query.updatedBefore||x.updatedAt<=query.updatedBefore)&&textValuesMatch([], query.text));
  const paged=pageRecords(records.sort(sortBinding),query.limit,query.cursor); return {records:paged.records,nextCursor:paged.nextCursor}; },
  async listRuntimeReadinessBindingRecordsByCompositionPlanId(targetWorkspaceId, compositionPlanId){ return (await this.listRuntimeReadinessBindingRecords({targetWorkspaceId, compositionPlanId})).records;},
  async listDraftCheckingBlockedStaleOrArchivedRuntimeReadinessBindingRecords(targetWorkspaceId){ return (await this.listRuntimeReadinessBindingRecords({targetWorkspaceId})).records.filter((x)=>x.status==="draft"||x.status==="checking"||x.status==="blocked"||x.status==="stale"||Boolean(x.archivedAt));},
  async archiveRuntimeReadinessBindingRecord(targetWorkspaceId, readinessBindingId, archivedAt){ const record=await this.readRuntimeReadinessBindingRecord(targetWorkspaceId, readinessBindingId); if(!record) return undefined; return this.saveRuntimeReadinessBindingRecord({...record,status:"archived",archivedAt,updatedAt:archivedAt}); }
}; }

export function createLocalRuntimeInventoryRepositoryAdapter(o:{rootDir:string; now?:()=>string}): RuntimeInventoryRepositoryPort { const store=new LocalRuntimeReadinessRecordStore(o); return {
  async saveRuntimeInventoryRecord(record){ const n=normalizeRuntimeInventory(record); const all=[...(await store.readInventory<RuntimeInventory>()).filter((x)=>!(x.targetWorkspaceId===n.targetWorkspaceId&&x.inventorySourceId===n.inventorySourceId)),n].sort(sortInventory); await store.writeInventory(all); return n; },
  async updateRuntimeInventoryRecord(record){ return this.saveRuntimeInventoryRecord(record); },
  async readRuntimeInventoryRecord(targetWorkspaceId, inventorySourceId){ if(!targetWorkspaceId) throw new Error("targetWorkspaceId is required."); const sourceId=normalizeRuntimeInventorySourceId(inventorySourceId); return (await store.readInventory<RuntimeInventory>()).map(normalizeRuntimeInventory).find((x)=>x.targetWorkspaceId===targetWorkspaceId&&x.inventorySourceId===sourceId); },
  async listRuntimeInventoryRecords(query){ if(!query.targetWorkspaceId) throw new Error("targetWorkspaceId is required."); const rows=(await store.readInventory<RuntimeInventory>()).map(normalizeRuntimeInventory).filter((x)=>x.targetWorkspaceId===query.targetWorkspaceId&&(!query.inventorySourceKind||x.inventorySourceKind===query.inventorySourceKind)&&(!query.inventoryStatus||x.inventoryStatus===query.inventoryStatus)&&(!query.providerAvailabilityStatus||x.discoveredProviderCandidates.some((p)=>p.availabilityStatus===query.providerAvailabilityStatus))&&(!query.blockedOnly||x.blockers.length>0)&&(!query.staleOnly||x.inventoryStatus==="stale")&&(!query.checkedAfter||(x.checkedAt??"")>=query.checkedAfter)&&(!query.checkedBefore||(x.checkedAt??"")<=query.checkedBefore)); const paged=pageRecords(rows.sort(sortInventory),query.limit,query.cursor); return {records:paged.records,nextCursor:paged.nextCursor}; },
  async readLatestRuntimeInventoryRecord(targetWorkspaceId, inventorySourceKind){ return (await this.listRuntimeInventoryRecords({targetWorkspaceId, inventorySourceKind, limit:1})).records[0]; }
}; }
