import { describe, expect, it } from "../../testing/node-test";
import {
  API_USER_LIBRARY_ASSET_LIST_OPERATION,
  API_USER_LIBRARY_ASSET_READ_OPERATION,
  API_USER_LIBRARY_COPY_OPERATION,
  API_WORKSPACE_EFFECTIVE_ASSET_SOURCE_LIST_OPERATION,
  API_USER_LIBRARY_IMPORT_OPERATION,
  API_USER_LIBRARY_LINK_LIST_OPERATION,
  API_USER_LIBRARY_LINK_OPERATION,
  API_USER_LIBRARY_LINK_READ_OPERATION,
  API_USER_LIBRARY_PROMOTE_OPERATION,
} from "../api";
import {
  DESKTOP_USER_LIBRARY_ASSET_LIST_OPERATION,
  DESKTOP_USER_LIBRARY_ASSET_READ_OPERATION,
  DESKTOP_USER_LIBRARY_COPY_OPERATION,
  DESKTOP_WORKSPACE_EFFECTIVE_ASSET_SOURCE_LIST_OPERATION,
  DESKTOP_USER_LIBRARY_IMPORT_OPERATION,
  DESKTOP_USER_LIBRARY_LINK_LIST_OPERATION,
  DESKTOP_USER_LIBRARY_LINK_OPERATION,
  DESKTOP_USER_LIBRARY_LINK_READ_OPERATION,
  DESKTOP_USER_LIBRARY_PROMOTE_OPERATION,
} from "../ipc";

describe("user-library API/IPC parity", () => {
  it("keeps operation coverage semantically equivalent", () => {
    expect(new Set([
      API_USER_LIBRARY_PROMOTE_OPERATION,
      API_USER_LIBRARY_LINK_OPERATION,
      API_USER_LIBRARY_COPY_OPERATION,
      API_USER_LIBRARY_IMPORT_OPERATION,
      API_USER_LIBRARY_ASSET_LIST_OPERATION,
      API_USER_LIBRARY_ASSET_READ_OPERATION,
      API_USER_LIBRARY_LINK_LIST_OPERATION,
      API_USER_LIBRARY_LINK_READ_OPERATION,
      API_WORKSPACE_EFFECTIVE_ASSET_SOURCE_LIST_OPERATION,
    ])).toEqual(new Set([
      DESKTOP_USER_LIBRARY_PROMOTE_OPERATION,
      DESKTOP_USER_LIBRARY_LINK_OPERATION,
      DESKTOP_USER_LIBRARY_COPY_OPERATION,
      DESKTOP_USER_LIBRARY_IMPORT_OPERATION,
      DESKTOP_USER_LIBRARY_ASSET_LIST_OPERATION,
      DESKTOP_USER_LIBRARY_ASSET_READ_OPERATION,
      DESKTOP_USER_LIBRARY_LINK_LIST_OPERATION,
      DESKTOP_USER_LIBRARY_LINK_READ_OPERATION,
      DESKTOP_WORKSPACE_EFFECTIVE_ASSET_SOURCE_LIST_OPERATION,
    ]));
  });
});
