import * as assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

import { AssetResourceBackedMappingService } from "../asset-resource-backed-mapping.service";
import type { AssetExternalRepositoryObjectReference } from "../../../../contracts/asset";
import type { ArtifactDescriptor } from "../../../../contracts/artifact";
import type { DatasetDescriptor } from "../../../../contracts/dataset";
import type { ImageAsset } from "../../../../contracts/image";
import type { ImageGenerationOutput } from "../../../../contracts/image-generation";
import type { ModelInventoryRecord } from "../../../../contracts/model";

const service = new AssetResourceBackedMappingService();

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function assertJsonCompatible(value: unknown): void {
  assert.doesNotThrow(() => JSON.parse(JSON.stringify(value)));
}

test("artifact descriptor and reference map to safe artifact resource backings", () => {
  const descriptor: ArtifactDescriptor = {
    key: "uploads/source-image.png",
    kind: "raw-staged",
    id: "artifact-123",
    name: "Source image",
    sizeBytes: 2048,
    checksum: { algorithm: "sha256", value: "abc123" },
    format: { mediaType: "image/png", extension: "png" },
    metadata: { userLabel: "safe", token: "should-not-leak" },
  };
  const before = clone(descriptor);

  const backing = service.mapArtifactDescriptorToBacking(descriptor);
  const referenceBacking = service.mapArtifactReferenceToBacking({ key: descriptor.key, label: "Source" });

  assert.deepEqual(descriptor, before);
  assert.equal(backing.resourceKind, "artifact");
  assert.equal("kind" in backing.ref ? backing.ref.kind : undefined, "artifact");
  assert.equal(backing.contentType, "image/png");
  assert.equal(backing.checksum, "sha256:abc123");
  assert.equal(referenceBacking.role, "source");
  assert.equal("token" in (backing.metadata ?? {}), false);
  assertJsonCompatible(backing);
});

test("image asset and generated image output map without storing generated bytes", () => {
  const image: ImageAsset = {
    assetId: "image-1",
    artifactId: "artifact-1",
    source: "generated",
    metadata: {
      requestId: "request-1",
      originalFileName: "image.png",
      prompt: "A prompt",
      seed: 42,
      engine: "comfyui",
      createdAt: "2026-01-01T00:00:00.000Z",
    },
  };
  const output: ImageGenerationOutput = {
    type: "image",
    engine: "comfyui",
    fileName: "image.png",
    contentBase64: "raw-bytes-must-not-map",
    mediaType: "image/png",
    promptId: "prompt-1",
    width: 512,
    height: 512,
  };

  const linked = service.mapImageAssetToResourceBackedAsset(image);
  const generated = service.mapImageGenerationOutputToGeneratedOutputReference(output, "output-1");
  const generatedBacking = service.mapGeneratedOutputToBacking(generated);

  assert.equal(linked.assetRef.kind, "resource-backed-asset");
  assert.equal(linked.backings[0]?.resourceKind, "image");
  assert.equal(linked.primaryBackingRef?.kind, "asset-resource-backing");
  assert.equal(generated.runtimeCapabilityId, "image-generation");
  assert.equal(generated.producedAssetType, "image");
  assert.equal(generatedBacking.resourceKind, "generated-output");
  assert.equal(JSON.stringify(generated).includes("raw-bytes-must-not-map"), false);
  assert.equal(JSON.stringify(generated).includes("contentBase64"), false);
});

test("dataset descriptor maps to dataset backing with safe metadata", () => {
  const descriptor: DatasetDescriptor = {
    id: "dataset-1",
    name: "Training dataset",
    sourceArtifacts: [{ key: "uploads/a.png" }],
    transforms: [{ definitionId: "resize" }],
    createdAt: "2026-01-01T00:00:00.000Z",
    metadata: { split: "train", secret: "nope" },
  };

  const backing = service.mapDatasetDescriptorToBacking(descriptor);

  assert.equal(backing.resourceKind, "dataset");
  assert.equal(backing.displayName, "Training dataset");
  assert.equal((backing.metadata as Record<string, unknown>).sourceArtifactCount, 1);
  assert.equal(JSON.stringify(backing).includes("nope"), false);
  assertJsonCompatible(backing);
});

test("model inventory records map to model backing without local paths", () => {
  const record: ModelInventoryRecord = {
    modelRecordId: "model-record-1",
    displayName: "Adapter model",
    source: "generated",
    lifecycleStatus: "generated",
    artifactForm: "adapter",
    provider: "unknown",
    modelId: "model-1",
    localPath: "/tmp/model.safetensors",
    validationReportPath: "/tmp/report.json",
    createdAt: "2026-01-01T00:00:00.000Z",
    backingArtifactIds: ["artifact-1"],
    primaryArtifactId: "artifact-1",
    sizeBytes: 1024,
    metadata: { note: "safe", cachePath: "/tmp/cache" },
  };

  const backing = service.mapModelInventoryRecordToBacking(record);
  const serialized = JSON.stringify(backing);

  assert.equal(backing.resourceKind, "model");
  assert.equal(backing.displayName, "Adapter model");
  assert.equal(serialized.includes("/tmp/model.safetensors"), false);
  assert.equal(serialized.includes("/tmp/report.json"), false);
  assert.equal(serialized.includes("/tmp/cache"), false);
  assertJsonCompatible(backing);
});

test("external repository and Hugging Face-like targets keep object paths metadata-only and sanitize unsafe metadata", () => {
  const external: AssetExternalRepositoryObjectReference = {
    provider: "huggingface",
    repositoryId: "org/model",
    revision: "main",
    objectPath: "model.safetensors",
    objectKind: "model",
    metadata: { token: "hf_secret", cachePath: "/tmp/hf", rawPayload: "raw", commandLine: "run --token x", stackTrace: "stack", filePath: "/tmp/file", sha: "abc" },
  };
  const backing = service.mapExternalRepositoryObjectToBacking(external);
  const repoObject = service.mapArtifactRepoTargetToExternalRepositoryObject({
    provider: "huggingface",
    repository: "org/dataset",
    revision: "abc",
    path: "data/train.parquet",
  });

  assert.equal(backing.resourceKind, "external-repository-object");
  assert.equal((backing.ref as AssetExternalRepositoryObjectReference).provider, "huggingface");
  assert.equal(JSON.stringify(backing).includes("hf_secret"), false);
  assert.equal(JSON.stringify(backing).includes("/tmp/hf"), false);
  assert.equal(JSON.stringify(backing).includes("raw"), false);
  assert.equal(JSON.stringify(backing).includes("run --token x"), false);
  assert.equal(JSON.stringify(backing).includes("stack"), false);
  assert.equal(JSON.stringify(backing).includes("/tmp/file"), false);
  assert.equal(backing.backingId.includes("model.safetensors"), false);
  assert.equal(backing.backingId.startsWith("external-repository-object.internal.huggingface."), true);
  assert.equal(repoObject.provider, "huggingface");
  assert.equal(repoObject.objectPath, "data/train.parquet");

  const urlPathRef = service.mapArtifactRepoTargetToExternalRepositoryObject({
    provider: "http",
    repository: "https://user:password@example.test/org/repo?token=secret",
    path: "https://user:password@example.test/private/model.safetensors?token=secret#fragment",
  });
  assert.equal(urlPathRef.repositoryId, "https://example.test/org/repo");
  assert.equal(urlPathRef.objectPath, "https://example.test/private/model.safetensors");
});


test("local path-like and URL-like external object values are not promoted to canonical ids or auth-bearing refs", () => {
  for (const objectPath of [
    "/tmp/model.safetensors",
    "C:\\Users\\name\\model.safetensors",
    "~/cache/model.safetensors",
    "https://example.test/private/model.safetensors?token=secret",
  ]) {
    const backing = service.mapExternalRepositoryObjectToBacking({
      provider: objectPath.startsWith("http") ? "http" : "local",
      repositoryId: "https://user:password@example.test/org/repo?token=secret",
      objectPath,
      objectKind: "file",
      metadata: { authorization: "Bearer secret", path: objectPath, sha: "abc" },
    });
    const ref = backing.ref as AssetExternalRepositoryObjectReference;
    const serialized = JSON.stringify(backing);

    assert.equal(backing.backingId.includes(objectPath), false);
    assert.equal(backing.backingId.includes("example.test/private"), false);
    assert.equal(ref.repositoryId.includes("user:password"), false);
    assert.equal(ref.repositoryId.includes("token=secret"), false);
    assert.equal(ref.objectPath?.includes("token=secret"), false);
    assert.equal(serialized.includes("Bearer secret"), false);
    assert.equal(serialized.includes('"path"'), false);
  }
});

test("preview references and resource-backed links are pure JSON-compatible mapping objects", () => {
  const backing = service.mapDatasetReferenceToBacking({ id: "dataset-1", label: "Dataset" });
  const preview = service.createPreviewReference({
    previewId: "preview-1",
    previewKind: "dataset-sample",
    resourceBackingRef: { kind: "asset-resource-backing", id: backing.backingId as never },
    summary: "Five rows.",
    metadata: { rows: 5, bytes: "must-not-map" },
  });
  const link = service.mapBackingToResourceBackedAsset(
    { kind: "asset-instance", id: "asset-instance.dataset" as never },
    backing,
    "dataset",
  );

  assert.equal(preview.previewKind, "dataset-sample");
  assert.equal(JSON.stringify(preview).includes("must-not-map"), false);
  assert.equal(link.primaryBackingRef?.kind, "asset-resource-backing");
  assert.equal(link.backings[0]?.backingId, backing.backingId);
  assert.notEqual(link.backings[0], backing);
  assertJsonCompatible(link);
});

test("mapping service does not import forbidden outer layers or runtime/persistence adapters", () => {
  const source = readFileSync("modules/application/services/asset/asset-resource-backed-mapping.service.ts", "utf8");
  for (const forbidden of [
    "modules/adapters",
    "../../../adapters",
    "modules/hosts",
    "../../../hosts",
    "contracts/api",
    "contracts/ipc",
    "apps/",
    "node:fs",
    "node:path",
    "runtime/python",
    "persistence/asset",
  ]) {
    assert.equal(source.includes(forbidden), false, `unexpected import boundary: ${forbidden}`);
  }
});

test("mapping service uses centralized sanitizer behavior for nested unsafe metadata", () => {
  const backing = service.mapExternalRepositoryObjectToBacking({
    provider: "custom",
    repositoryId: "safe-repo",
    objectPath: "safe/object.json",
    metadata: {
      safe: "kept",
      nested: { label: "visible", token: "token=hidden", safeButPathValue: "/tmp/private" },
      values: ["ok", "Bearer abcdef", { command: "run" }],
      contentBase64: "data:application/octet-stream;base64,AAAA",
    },
  });
  const json = JSON.stringify(backing).toLowerCase();

  assert.equal(json.includes("kept"), true);
  for (const unsafe of ["token=hidden", "/tmp/private", "bearer", "command", "contentbase64", "base64,"]) {
    assert.equal(json.includes(unsafe), false, unsafe);
  }
});

test("mapping service imports centralized sanitizer without a second local forbidden-key regex", () => {
  const source = readFileSync("modules/application/services/asset/asset-resource-backed-mapping.service.ts", "utf8");
  assert.equal(source.includes("FORBIDDEN_METADATA_KEY_PATTERN"), false);
  assert.equal(source.includes("sanitizeAssetMetadata"), true);
});
