import type { AssistantResponseRepositoryPort, ConversationMessageRepositoryPort, ConversationSessionRepositoryPort, ConversationTurnRepositoryPort } from '../../../application/ports/conversations';
import { normalizeAssistantResponseRecord, normalizeConversationMessageRecord, normalizeConversationSessionRecord, normalizeConversationTurnRecord, type AssistantResponseRecord, type ConversationMessageRecord, type ConversationSessionRecord, type ConversationTurnRecord } from '../../../contracts/conversations';
import { pageRecords } from '../user-library/local-user-library-repository-helpers';
import { LocalConversationRecordStore } from './local-conversation-record-store';
type ConversationUpdatedRecord={id:string;updatedAt:string};
type ConversationCreatedRecord={id:string;createdAt:string};
const byUpdated=(a:ConversationUpdatedRecord,b:ConversationUpdatedRecord)=>b.updatedAt.localeCompare(a.updatedAt)||a.id.localeCompare(b.id); const byCreated=(a:ConversationCreatedRecord,b:ConversationCreatedRecord)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id);
export function createLocalConversationRepositoryAdapters(o:{rootDir:string; now?:()=>string}){const s=new LocalConversationRecordStore(o);
const sessions=async()=> (await s.readCollection<ConversationSessionRecord>('conversation-sessions.json')).map(normalizeConversationSessionRecord);
const turns=async()=> (await s.readCollection<ConversationTurnRecord>('conversation-turns.json')).map(normalizeConversationTurnRecord);
const messages=async()=> (await s.readCollection<ConversationMessageRecord>('conversation-messages.json')).map(normalizeConversationMessageRecord);
const responses=async()=> (await s.readCollection<AssistantResponseRecord>('assistant-responses.json')).map(normalizeAssistantResponseRecord);
const conversationSessionRepository:ConversationSessionRepositoryPort={async saveConversationSession(r){const n=normalizeConversationSessionRecord(r); const all=[...(await sessions()).filter(x=>!(x.workspaceId===n.workspaceId&&x.id===n.id)),n].sort(byUpdated); await s.writeCollection('conversation-sessions.json',all); return n;}, async updateConversationSession(r){return this.saveConversationSession(r)}, async getConversationSessionById(workspaceId,id){if(!workspaceId) throw new Error('workspaceId is required.'); return (await sessions()).find(x=>x.workspaceId===workspaceId&&x.id===id);}, async listConversationSessions(q){if(!q.workspaceId) throw new Error('workspaceId is required.'); const xs=(await sessions()).filter(x=>x.workspaceId===q.workspaceId&&(!q.status||x.status===q.status)&&(!q.sourceExecutionPlanId||x.sourceExecutionPlanId===q.sourceExecutionPlanId)); const p=pageRecords(xs.sort(byUpdated),q.limit,q.cursor); return {sessions:p.records,nextCursor:p.nextCursor};}};
const conversationTurnRepository:ConversationTurnRepositoryPort={async saveConversationTurn(r){const n=normalizeConversationTurnRecord(r); const all=[...(await turns()).filter(x=>!(x.workspaceId===n.workspaceId&&x.id===n.id)),n].sort((a,b)=>a.sequence-b.sequence||byCreated(a,b)); await s.writeCollection('conversation-turns.json',all); return n;}, async updateConversationTurn(r){return this.saveConversationTurn(r)}, async getConversationTurnById(workspaceId,id){if(!workspaceId) throw new Error('workspaceId is required.'); return (await turns()).find(x=>x.workspaceId===workspaceId&&x.id===id);}, async listConversationTurnsBySession(workspaceId,sessionId,status){if(!workspaceId) throw new Error('workspaceId is required.'); return (await turns()).filter(x=>x.workspaceId===workspaceId&&x.conversationSessionId===sessionId&&(!status||x.status===status)).sort((a,b)=>a.sequence-b.sequence||byCreated(a,b));}, async listConversationTurnsByExecutionRun(workspaceId,runId){if(!workspaceId) throw new Error('workspaceId is required.'); return (await turns()).filter(x=>x.workspaceId===workspaceId&&x.executionRunId===runId).sort((a,b)=>a.sequence-b.sequence||byCreated(a,b));}, async getLatestConversationTurnBySession(workspaceId,sessionId){const xs=await this.listConversationTurnsBySession(workspaceId,sessionId); return xs[xs.length-1];}};
const conversationMessageRepository:ConversationMessageRepositoryPort={async saveConversationMessage(r){const n=normalizeConversationMessageRecord(r); const all=[...(await messages()).filter(x=>!(x.workspaceId===n.workspaceId&&x.id===n.id)),n].sort(byCreated); await s.writeCollection('conversation-messages.json',all); return n;}, async getConversationMessageById(workspaceId,id){if(!workspaceId) throw new Error('workspaceId is required.'); return (await messages()).find(x=>x.workspaceId===workspaceId&&x.id===id);}, async listConversationMessagesBySession(workspaceId,sessionId){if(!workspaceId) throw new Error('workspaceId is required.'); return (await messages()).filter(x=>x.workspaceId===workspaceId&&x.conversationSessionId===sessionId).sort(byCreated);}, async listConversationMessagesByTurn(workspaceId,turnId){if(!workspaceId) throw new Error('workspaceId is required.'); return (await messages()).filter(x=>x.workspaceId===workspaceId&&x.conversationTurnId===turnId).sort(byCreated);}};
const assistantResponseRepository:AssistantResponseRepositoryPort={async saveAssistantResponse(r){const n=normalizeAssistantResponseRecord(r); const all=[...(await responses()).filter(x=>!(x.workspaceId===n.workspaceId&&x.id===n.id)),n].sort(byCreated); await s.writeCollection('assistant-responses.json',all); return n;}, async updateAssistantResponse(r){return this.saveAssistantResponse(r)}, async getAssistantResponseById(workspaceId,id){if(!workspaceId) throw new Error('workspaceId is required.'); return (await responses()).find(x=>x.workspaceId===workspaceId&&x.id===id);}, async listAssistantResponsesBySession(workspaceId,sessionId){if(!workspaceId) throw new Error('workspaceId is required.'); return (await responses()).filter(x=>x.workspaceId===workspaceId&&x.conversationSessionId===sessionId).sort(byCreated);}, async listAssistantResponsesByTurn(workspaceId,turnId){if(!workspaceId) throw new Error('workspaceId is required.'); return (await responses()).filter(x=>x.workspaceId===workspaceId&&x.conversationTurnId===turnId).sort(byCreated);}};
return {conversationSessionRepository,conversationTurnRepository,conversationMessageRepository,assistantResponseRepository};
}
