import { NodePort, NodePortCompatibilityProfile } from "../../../domain/nodes/NodePort";
import { NodeProperty } from "../../../domain/nodes/NodeProperty";
import type { ILangChainNodeCatalogDefinition } from "./VectorStoreUpsertNodeDefinition";

const projection = Object.freeze({
  group: "Tier 2 LLM",
  tags: Object.freeze(["prompting", "chat", "messages"]),
  keywords: Object.freeze(["chat prompt", "prompt builder", "system message", "context"]),
  supportsAuthoringView: true,
  supportsToolView: true,
});

export const CHAT_PROMPT_BUILDER_NODE_DEFINITION: ILangChainNodeCatalogDefinition = Object.freeze({
  technicalName: "langchain.chat_prompt_builder",
  nonTechnicalName: "Build AI Prompt",
  technicalDescription:
    "Builds a structured chat prompt from system instructions, user input, and optional context.",
  description:
    "Combine instructions, context, and user input into a clean prompt for the AI.",
  inputPorts: Object.freeze([
    new NodePort({
      id: "systemMessage",
      name: "System Message",
      description: "Optional system-level instructions that guide the AI's behavior.",
      direction: "input",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["text"], isOptional: true }),
    }),
    new NodePort({
      id: "userMessage",
      name: "User Message",
      description: "The primary user request that the AI should answer.",
      direction: "input",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["text"] }),
    }),
    new NodePort({
      id: "context",
      name: "Context",
      description: "Optional supporting context that should be included in the built prompt.",
      direction: "input",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["text", "json", "document"], isOptional: true }),
    }),
  ]),
  outputPorts: Object.freeze([
    new NodePort({
      id: "prompt",
      name: "Prompt",
      description: "Structured prompt payload that can be passed to downstream AI nodes.",
      direction: "output",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["prompt", "json"] }),
    }),
    new NodePort({
      id: "messages",
      name: "Messages",
      description: "Chat messages assembled from the provided instructions, context, and user input.",
      direction: "output",
      cardinality: "many",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["messages", "json"] }),
    }),
  ]),
  properties: Object.freeze([
    new NodeProperty({
      id: "template",
      name: "Template",
      description: "Optional custom template used to assemble the user-facing prompt content.",
      type: "multiline-text",
      value: "",
      defaultValue: "",
      projection: {
        label: "Prompt template",
        description: "Optional custom template for combining context and the user request.",
        group: "Prompting",
        order: 0,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "textarea",
      },
      isAdvanced: true,
      order: 0,
    }),
    new NodeProperty({
      id: "includeContext",
      name: "Include Context",
      description: "Include the context input when building the final prompt.",
      type: "boolean",
      value: true,
      defaultValue: true,
      projection: {
        label: "Use context",
        description: "Include the context input when building the final prompt.",
        group: "Prompting",
        order: 1,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "boolean",
      },
      order: 1,
    }),
    new NodeProperty({
      id: "contextLabel",
      name: "Context Label",
      description: "Label used before the context block in the assembled prompt.",
      type: "text",
      value: "Context",
      defaultValue: "Context",
      projection: {
        label: "Context heading",
        description: "Label used before the context block in the assembled prompt.",
        group: "Prompting",
        order: 2,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "text",
      },
      order: 2,
    }),
    new NodeProperty({
      id: "userLabel",
      name: "User Label",
      description: "Label used before the user request in the assembled prompt.",
      type: "text",
      value: "User",
      defaultValue: "User",
      projection: {
        label: "User heading",
        description: "Label used before the user request in the assembled prompt.",
        group: "Prompting",
        order: 3,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "text",
      },
      order: 3,
    }),
  ]),
  projection,
});
