import { NodePort, NodePortCompatibilityProfile } from "../../../domain/nodes/NodePort";
import { NodeProperty } from "../../../domain/nodes/NodeProperty";
import type { ILangChainNodeCatalogDefinition } from "./VectorStoreUpsertNodeDefinition";

const projection = Object.freeze({
  group: "Tier 2 LLM",
  tags: Object.freeze(["tools", "schema", "function calling"]),
  keywords: Object.freeze(["tool definition", "function tool", "tool schema", "ai tool"]),
  supportsAuthoringView: true,
  supportsToolView: true,
});

export const TOOL_DEFINITION_NODE_DEFINITION: ILangChainNodeCatalogDefinition = Object.freeze({
  technicalName: "langchain.tool_definition",
  nonTechnicalName: "Create AI Tool",
  technicalDescription:
    "Builds a workflow-valid tool definition object with model-facing metadata, argument schema, and optional execution binding hints.",
  description:
    "Describe a tool the AI can plan around, including what it does, what inputs it needs, and how strict the schema should be.",
  inputPorts: Object.freeze([
    new NodePort({
      id: "inputSchema",
      name: "Input Schema",
      description: "JSON schema describing the arguments the tool accepts.",
      direction: "input",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["json", "generic"], isOptional: true }),
    }),
    new NodePort({
      id: "toolHandler",
      name: "Tool Handler",
      description: "Optional workflow or runtime binding payload that future execution nodes can use to resolve the tool implementation.",
      direction: "input",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["generic", "json"], isOptional: true }),
    }),
  ]),
  outputPorts: Object.freeze([
    new NodePort({
      id: "tool",
      name: "Tool",
      description: "Normalized tool definition object suitable for downstream tool-aware nodes.",
      direction: "output",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["generic", "json"] }),
    }),
    new NodePort({
      id: "toolManifest",
      name: "Tool Manifest",
      description: "Metadata summary describing the published tool name, visibility, and schema requirements.",
      direction: "output",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["json", "workflow-state"] }),
    }),
  ]),
  properties: Object.freeze([
    new NodeProperty({
      id: "toolName",
      name: "Tool Name",
      description: "Stable tool identifier exposed to the model when it selects a tool call.",
      type: "text",
      value: "",
      defaultValue: "",
      constraints: { required: true },
      projection: {
        label: "Tool name",
        description: "Stable tool identifier exposed to the model when it selects a tool call.",
        group: "Definition",
        order: 0,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "text",
      },
      order: 0,
    }),
    new NodeProperty({
      id: "description",
      name: "Description",
      description: "Model-facing instruction describing what the tool does and when it should be used.",
      type: "multiline-text",
      value: "",
      defaultValue: "",
      constraints: { required: true },
      projection: {
        label: "Tool description",
        description: "Model-facing instruction describing what the tool does and when it should be used.",
        group: "Definition",
        order: 1,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "textarea",
      },
      order: 1,
    }),
    new NodeProperty({
      id: "inputSchemaSource",
      name: "Input Schema Source",
      description: "Choose whether the tool schema comes from the property editor, an incoming connection, or both.",
      type: "select",
      value: "merge",
      defaultValue: "merge",
      options: [
        { label: "Property only", value: "property", description: "Use only the schema entered on this node." },
        { label: "Input only", value: "input", description: "Use only the schema connected to the input port." },
        { label: "Merge both", value: "merge", description: "Combine property and input schemas, preferring connected input values." },
      ],
      constraints: { required: true, allowedValues: ["property", "input", "merge"] },
      projection: {
        label: "Schema source",
        description: "Choose whether the tool schema comes from the property editor, an incoming connection, or both.",
        group: "Schema",
        order: 2,
        authorVisibility: "basic",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "select",
      },
      order: 2,
    }),
    new NodeProperty({
      id: "inputSchema",
      name: "Input Schema",
      description: "Optional default argument schema used when no schema is connected to the input port.",
      type: "json",
      value: {
        type: "object",
        properties: {},
        required: [],
      },
      defaultValue: {
        type: "object",
        properties: {},
        required: [],
      },
      projection: {
        label: "Default schema",
        description: "Optional default argument schema used when no schema is connected to the input port.",
        group: "Schema",
        order: 3,
        authorVisibility: "basic",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "json-editor",
      },
      order: 3,
    }),
    new NodeProperty({
      id: "strictSchema",
      name: "Strict Schema",
      description: "Require tool calls to match the provided schema closely when the runtime supports strict validation.",
      type: "boolean",
      value: true,
      defaultValue: true,
      projection: {
        label: "Require strict schema",
        description: "Require tool calls to match the provided schema closely when the runtime supports strict validation.",
        group: "Schema",
        order: 4,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "boolean",
      },
      order: 4,
    }),
    new NodeProperty({
      id: "displayName",
      name: "Display Name",
      description: "Optional human-friendly label for authoring and tools UI views.",
      type: "text",
      value: "",
      defaultValue: "",
      projection: {
        label: "Display name",
        description: "Optional human-friendly label for authoring and tools UI views.",
        group: "Presentation",
        order: 5,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "text",
      },
      isAdvanced: true,
      order: 5,
    }),
  ]),
  projection,
});
