import { parseApiEnvelope } from "../../../security/apiErrorEnvelope";
import { secureFetch } from "../../../security/secureFetch";
export type Result<T> = { ok: true; value: T } | { ok: false; error: { code: string; message: string } };
const err = (message: string, code = "internal"): Result<never> => ({ ok: false, error: { code, message } });
const unwrap = <T,>(r: unknown): Result<T> => { const v = r as any; return v?.ok ? { ok: true, value: v.value as T } : err(v?.error?.message ?? "Unable to complete request.", v?.error?.code ?? "internal"); };
const getJson = async (url:string)=> parseApiEnvelope(await (await secureFetch(url,{method:"GET"})).json());
const postJson = async (url:string, body:unknown)=> parseApiEnvelope(await (await secureFetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)})).json());
const patchJson = async (url:string, body:unknown)=> parseApiEnvelope(await (await secureFetch(url,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)})).json());
const delJson = async (url:string)=> parseApiEnvelope(await (await secureFetch(url,{method:"DELETE"})).json());
const q=(input:Record<string,unknown>)=>{const p=new URLSearchParams(); for (const [k,v] of Object.entries(input)) if(v!==undefined&&v!=="") p.set(k,String(v)); const s=p.toString(); return s?`?${s}`:"";};
export function createThinClientAssetCompositionClient(base="/api"){
  const b=base.replace(/\/+$/,'');
  return {
    createPlan: async (input:{targetWorkspaceId:string; name:string; description?:string})=>{ try{return unwrap(await postJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plans`,input)); }catch{return err("Asset composition is unavailable.","unavailable");}},
    updatePlan: async (input:{targetWorkspaceId:string; planId:string; name?:string; description?:string; status?:string})=>{ try{return unwrap(await patchJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plans/${encodeURIComponent(input.planId)}`,input)); }catch{return err("Asset composition is unavailable.","unavailable");}},
    readPlan: async (input:{targetWorkspaceId:string; planId:string})=>{ try{return unwrap(await getJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plans/${encodeURIComponent(input.planId)}`)); }catch{return err("Asset composition is unavailable.","unavailable");}},
    listPlans: async (input:{targetWorkspaceId:string; status?:string; text?:string; limit?:number; cursor?:string})=>{ try{return unwrap(await getJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plans${q({status:input.status,text:input.text,limit:input.limit,cursor:input.cursor})}`)); }catch{return err("Asset composition is unavailable.","unavailable");}},
    archivePlan: async (input:{targetWorkspaceId:string; planId:string})=>{ try{return unwrap(await postJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plans/${encodeURIComponent(input.planId)}/archive`,{})); }catch{return err("Asset composition is unavailable.","unavailable");}},
    addProjectionToPlan: async (input:{targetWorkspaceId:string; planId:string; projectionId:string})=>{ try{return unwrap(await postJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plans/${encodeURIComponent(input.planId)}/projections`,input)); }catch{return err("Adding assets to plans is not available yet.","unavailable");}},
    removeProjectionFromPlan: async (input:{targetWorkspaceId:string; planId:string; projectionId:string})=>{ try{return unwrap(await delJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plans/${encodeURIComponent(input.planId)}/projections/${encodeURIComponent(input.projectionId)}`)); }catch{return err("Removing assets from plans is not available yet.","unavailable");}},
    connectNodes: async (input:{targetWorkspaceId:string; planId:string; sourceNodeId:string; kind:string; targetNodeId:string})=>{ try{return unwrap(await postJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plans/${encodeURIComponent(input.planId)}/relationships`,input)); }catch{return err("Connections are not available yet.","unavailable");}},
    disconnectNodes: async (input:{targetWorkspaceId:string; planId:string; relationshipId:string})=>{ try{return unwrap(await delJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plans/${encodeURIComponent(input.planId)}/relationships/${encodeURIComponent(input.relationshipId)}`)); }catch{return err("Removing connections is not available yet.","unavailable");}},
    validatePlan: async (input:{targetWorkspaceId:string; planId:string})=>{ try{return unwrap(await postJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plans/${encodeURIComponent(input.planId)}/validate`,{})); }catch{return err("Plan checking is not available yet.","unavailable");}},
    listPlanSummaries: async (input:{targetWorkspaceId:string})=>{ try{return unwrap(await getJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plan-summaries`)); }catch{return err("Asset composition is unavailable.","unavailable");}},
    readPlanDetail: async (input:{targetWorkspaceId:string; planId:string})=>{ try{return unwrap(await getJson(`${b}/asset-composition/workspaces/${encodeURIComponent(input.targetWorkspaceId)}/plan-details/${encodeURIComponent(input.planId)}`)); }catch{return err("Asset composition is unavailable.","unavailable");}},
  };
}
