import type { WorkspaceAssetAuthoringReadModelService } from "../../../../application/services/asset/workspace-asset-authoring-read-model.service";
import type { AuthoredAssetRepositoryPort, AssetDraftRepositoryPort, AssetOverrideRepositoryPort, AssetRevisionRepositoryPort } from "../../../../application/ports/asset-authoring";
import type { CreateWorkspaceAuthoredAssetUseCase, CreateAssetDraftUseCase, UpdateAssetDraftUseCase, PublishAssetDraftUseCase, CreateAssetOverrideUseCase, UpdateAssetOverrideUseCase, DisableAssetOverrideUseCase } from "../../../../application/use-cases/asset-authoring";
import { createApiAssetAuthoringFailureResponse, createApiAssetAuthoringOperationSuccessResponse, API_ASSET_AUTHORING_CREATE_WORKSPACE_AUTHORED_ASSET_OPERATION, API_ASSET_AUTHORING_CREATE_DRAFT_OPERATION, API_ASSET_AUTHORING_UPDATE_DRAFT_OPERATION, API_ASSET_AUTHORING_PUBLISH_DRAFT_OPERATION, API_ASSET_AUTHORING_CREATE_OVERRIDE_OPERATION, API_ASSET_AUTHORING_UPDATE_OVERRIDE_OPERATION, API_ASSET_AUTHORING_DISABLE_OVERRIDE_OPERATION, API_ASSET_AUTHORING_LIST_AUTHORED_ASSETS_OPERATION, API_ASSET_AUTHORING_READ_AUTHORED_ASSET_OPERATION, API_ASSET_AUTHORING_LIST_DRAFTS_OPERATION, API_ASSET_AUTHORING_READ_DRAFT_OPERATION, API_ASSET_AUTHORING_LIST_REVISIONS_OPERATION, API_ASSET_AUTHORING_READ_REVISION_OPERATION, API_ASSET_AUTHORING_LIST_OVERRIDES_OPERATION, API_ASSET_AUTHORING_READ_OVERRIDE_OPERATION, API_ASSET_AUTHORING_LIST_EFFECTIVE_SUMMARIES_OPERATION } from "../../../../contracts/api";

interface App{get:(p:string,h:any)=>void;post:(p:string,h:any)=>void}
const unavailable=(res:any,op:string,m:string)=>res.status(503).json(createApiAssetAuthoringFailureResponse(op,"unavailable",m));
const internal=(res:any,op:string,m:string)=>res.status(500).json(createApiAssetAuthoringFailureResponse(op,"internal",m));
export interface RegisterAssetAuthoringApiRoutesDependencies{app:App;createWorkspaceAuthoredAssetUseCase?:CreateWorkspaceAuthoredAssetUseCase;createAssetDraftUseCase?:CreateAssetDraftUseCase;updateAssetDraftUseCase?:UpdateAssetDraftUseCase;publishAssetDraftUseCase?:PublishAssetDraftUseCase;createAssetOverrideUseCase?:CreateAssetOverrideUseCase;updateAssetOverrideUseCase?:UpdateAssetOverrideUseCase;disableAssetOverrideUseCase?:DisableAssetOverrideUseCase;authoredAssetRepository?:AuthoredAssetRepositoryPort;assetDraftRepository?:AssetDraftRepositoryPort;assetRevisionRepository?:AssetRevisionRepositoryPort;assetOverrideRepository?:AssetOverrideRepositoryPort;effectiveSummaryReader?:WorkspaceAssetAuthoringReadModelService;}
export function registerAssetAuthoringApiRoutes(d:RegisterAssetAuthoringApiRoutesDependencies):void{
const cmd=(path:string,op:string,uc:any)=>d.app.post(path,async(req:any,res:any)=>{if(!uc)return unavailable(res,op,"Operation unavailable.");try{const r=await uc.execute(req.body as never);if(r.kind==="failure")return res.status(r.failure.code==="unavailable"?503:400).json(createApiAssetAuthoringFailureResponse(op,r.failure.code as any,r.failure.message));return res.status(200).json(createApiAssetAuthoringOperationSuccessResponse(op,r.value));}catch{return internal(res,op,"Operation failed.");}});
cmd("/api/asset-authoring/create-workspace-authored-asset",API_ASSET_AUTHORING_CREATE_WORKSPACE_AUTHORED_ASSET_OPERATION,d.createWorkspaceAuthoredAssetUseCase);
cmd("/api/asset-authoring/create-draft",API_ASSET_AUTHORING_CREATE_DRAFT_OPERATION,d.createAssetDraftUseCase);
cmd("/api/asset-authoring/update-draft",API_ASSET_AUTHORING_UPDATE_DRAFT_OPERATION,d.updateAssetDraftUseCase);
cmd("/api/asset-authoring/publish-draft",API_ASSET_AUTHORING_PUBLISH_DRAFT_OPERATION,d.publishAssetDraftUseCase);
cmd("/api/asset-authoring/create-override",API_ASSET_AUTHORING_CREATE_OVERRIDE_OPERATION,d.createAssetOverrideUseCase);
cmd("/api/asset-authoring/update-override",API_ASSET_AUTHORING_UPDATE_OVERRIDE_OPERATION,d.updateAssetOverrideUseCase);
cmd("/api/asset-authoring/disable-override",API_ASSET_AUTHORING_DISABLE_OVERRIDE_OPERATION,d.disableAssetOverrideUseCase);

const read=(path:string,op:string,fn:any)=>d.app.get(path,async(req:any,res:any)=>{if(!fn)return unavailable(res,op,"Read unavailable.");try{return res.status(200).json(createApiAssetAuthoringOperationSuccessResponse(op,await fn(req)));}catch{return internal(res,op,"Read failed.");}});
read("/api/asset-authoring/authored-assets",API_ASSET_AUTHORING_LIST_AUTHORED_ASSETS_OPERATION,(req:any)=>d.authoredAssetRepository?.listAuthoredAssetRecords({workspaceId:req.query?.workspaceId,status:req.query?.status,limit:req.query?.limit,cursor:req.query?.cursor}));
read("/api/asset-authoring/authored-assets/:authoredAssetId",API_ASSET_AUTHORING_READ_AUTHORED_ASSET_OPERATION,(req:any)=>d.authoredAssetRepository?.readAuthoredAssetRecordByWorkspace(req.query?.workspaceId,req.params.authoredAssetId));
read("/api/asset-authoring/drafts",API_ASSET_AUTHORING_LIST_DRAFTS_OPERATION,(req:any)=>d.assetDraftRepository?.listAssetDraftRecords({workspaceId:req.query?.targetWorkspaceId,status:req.query?.status,limit:req.query?.limit,cursor:req.query?.cursor}));
read("/api/asset-authoring/drafts/:draftId",API_ASSET_AUTHORING_READ_DRAFT_OPERATION,(req:any)=>d.assetDraftRepository?.readAssetDraftRecord(req.query?.targetWorkspaceId,req.params.draftId));
read("/api/asset-authoring/revisions",API_ASSET_AUTHORING_LIST_REVISIONS_OPERATION,(req:any)=>d.assetRevisionRepository?.listAssetRevisionRecords({workspaceId:req.query?.workspaceId,authoredAssetId:req.query?.authoredAssetId,status:req.query?.status,limit:req.query?.limit,cursor:req.query?.cursor}));
read("/api/asset-authoring/revisions/:revisionId",API_ASSET_AUTHORING_READ_REVISION_OPERATION,(req:any)=>d.assetRevisionRepository?.readAssetRevisionRecord(req.query?.workspaceId,req.query?.authoredAssetId,req.params.revisionId));
read("/api/asset-authoring/overrides",API_ASSET_AUTHORING_LIST_OVERRIDES_OPERATION,(req:any)=>d.assetOverrideRepository?.listAssetOverrideRecords({targetWorkspaceId:req.query?.targetWorkspaceId,status:req.query?.status,conflictStatus:req.query?.conflictStatus,limit:req.query?.limit,cursor:req.query?.cursor}));
read("/api/asset-authoring/overrides/:overrideId",API_ASSET_AUTHORING_READ_OVERRIDE_OPERATION,(req:any)=>d.assetOverrideRepository?.readAssetOverrideRecord(req.query?.targetWorkspaceId,req.params.overrideId));
read("/api/asset-authoring/effective-summaries",API_ASSET_AUTHORING_LIST_EFFECTIVE_SUMMARIES_OPERATION,async(req:any)=>({items:[await d.effectiveSummaryReader?.readEffectiveSourceSummary(req.query?.targetWorkspaceId,req.query?.assetReference)].filter(Boolean)}));
}
