import test from 'node:test';
import assert from 'node:assert/strict';
import { ExecutionPlanReadModelService } from '../execution-plan-read-model.service';
import type { ExecutionPlanRepositoryPort } from '../../../ports/execution-plans';

const plan = (workspaceId='ws.a', id='ep.1', status:any='ready-for-review') => ({ id, workspaceId, sourceCompositionPlanId:'cp.1', sourceRuntimeReadinessBindingId:'rr.1', sourceReadinessStatus:'ready', status, steps:[{id:'s.1',sourceCompositionPlanId:'cp.1',kind:'prepare-input',status:'planned',label:'Step',requiredAdapterReferenceIds:['ar.1'],inputIds:['i.1'],outputIds:['o.1'],dependencyIds:['d.1'],safetyGateIds:['g.1'],blockers:[],diagnostics:[]}], dependencies:[{id:'d.1',kind:'input-required',status:'planned',sourceStepId:'s.1',targetStepId:'s.1',label:'dep',blockers:[],diagnostics:[]}], inputs:[{id:'i.1',stepId:'s.1',kind:'user-provided',status:'available',label:'input',sourceReferenceKind:'user',required:true,blockers:[],diagnostics:[]}], outputs:[{id:'o.1',stepId:'s.1',kind:'artifact',status:'planned',label:'output',destinationReferenceKind:'workspace',required:true,blockers:[],diagnostics:[]}], adapterReferences:[{id:'ar.1',kind:'provider-adapter',status:'planned',sourceRuntimeReadinessBindingId:'rr.1',label:'adapter',blockers:[],diagnostics:[]}], safetyGates:[{id:'g.1',kind:'required-input-available',status:'passed-by-plan',label:'gate',blockers:[],diagnostics:[]}], blockers:[], diagnostics:[], resourceEstimates:[{id:'re.1',compute:'low',storage:'small',duration:'short'}], provenance:[{kind:'execution-plan-created',at:'2026-01-01T00:00:00.000Z'},{kind:'adapter-references-planned',at:'2026-01-02T00:00:00.000Z'},{kind:'safety-gates-planned',at:'2026-01-03T00:00:00.000Z'}], createdAt:'2026-01-01T00:00:00.000Z', updatedAt:'2026-01-04T00:00:00.000Z' } as any);
const repo=(plans:any[]):ExecutionPlanRepositoryPort=>({saveExecutionPlan:async(p:any)=>p,updateExecutionPlan:async(p:any)=>p,archiveExecutionPlan:async()=>undefined,getExecutionPlanById:async(ws:any,id:any)=>plans.find((p)=>p.workspaceId===ws&&p.id===id),listExecutionPlans:async(q:any)=>({plans:plans.filter((p)=>p.workspaceId===q.workspaceId && (q.sourceCompositionPlanId? p.sourceCompositionPlanId===q.sourceCompositionPlanId:true) && (q.sourceRuntimeReadinessBindingId? p.sourceRuntimeReadinessBindingId===q.sourceRuntimeReadinessBindingId:true) && (q.archived===false? !p.archivedAt:true))})});

test('workspace scoped summaries, labels, and attention', async()=>{ const svc=new ExecutionPlanReadModelService(repo([plan('ws.a','ep.1'),plan('ws.b','ep.1'),plan('ws.a','ep.2','needs-setup')])); const {summaries}=await svc.listExecutionPlanSummaries({workspaceId:'ws.a'}); assert.equal(summaries.length,2); assert.equal(summaries[0].statusLabel.includes('ready-to-run'),false); assert.equal(summaries.find((s)=>s.executionPlanId==='ep.1')?.needsAttention,false); assert.equal(summaries.find((s)=>s.executionPlanId==='ep.2')?.needsAttention,true);});

test('detail is workspace-scoped and sanitized', async()=>{ const p=plan(); p.diagnostics=[{code:'x.y',severity:'error',message:'/tmp/a token=abc stack trace'}]; const svc=new ExecutionPlanReadModelService(repo([p,plan('ws.b','ep.1')])); assert.equal(await svc.readExecutionPlanDetail({workspaceId:'ws.b',executionPlanId:'ep.2'}),undefined); const detail=await svc.readExecutionPlanDetail({workspaceId:'ws.a',executionPlanId:'ep.1'}); assert.ok(detail?.summary); assert.equal(JSON.stringify(detail).includes('/tmp/a'),false); assert.ok(detail?.stepSummaries.length); assert.ok(detail?.adapterReferenceSummaries.length);});

test('composition/runtime lookup and latest deterministic', async()=>{ const a=plan('ws.a','ep.1'); a.updatedAt='2026-01-01T00:00:00.000Z'; const b=plan('ws.a','ep.2'); b.updatedAt='2026-01-02T00:00:00.000Z'; b.sourceRuntimeReadinessBindingId='rr.2'; const svc=new ExecutionPlanReadModelService(repo([a,b,plan('ws.b','ep.9')])); assert.equal((await svc.readLatestExecutionPlanForCompositionPlan({workspaceId:'ws.a',compositionPlanId:'cp.1'}))?.executionPlanId,'ep.2'); assert.equal((await svc.readLatestExecutionPlanForRuntimeReadinessBinding({workspaceId:'ws.a',runtimeReadinessBindingId:'rr.2'}))?.executionPlanId,'ep.2');});

test('workspace summary and attention list', async()=>{ const svc=new ExecutionPlanReadModelService(repo([plan('ws.a','ep.1','ready-for-review'),plan('ws.a','ep.2','blocked'),plan('ws.b','ep.3','invalid')])); const summary=await svc.summarizeWorkspaceExecutionPlans({workspaceId:'ws.a'}); assert.equal(summary.total,2); assert.equal(summary.needingAttention,1); const attention=await svc.listExecutionPlansNeedingAttention({workspaceId:'ws.a'}); assert.equal(attention.length,1); });
