import { describe, expect, it, testDouble } from "../../../../../testing/node-test";
import { DESKTOP_ASSET_AUTHORING_CREATE_WORKSPACE_AUTHORED_ASSET_REQUEST_CHANNEL, DESKTOP_ASSET_AUTHORING_CREATE_DRAFT_REQUEST_CHANNEL, DESKTOP_ASSET_AUTHORING_CREATE_OVERRIDE_REQUEST_CHANNEL, DESKTOP_ASSET_AUTHORING_LIST_AUTHORED_ASSETS_REQUEST_CHANNEL, DESKTOP_ASSET_AUTHORING_LIST_EFFECTIVE_SUMMARIES_REQUEST_CHANNEL, DESKTOP_ASSET_AUTHORING_PUBLISH_DRAFT_REQUEST_CHANNEL } from "../../../../../contracts/ipc";
import { registerAssetAuthoringIpc } from "../registerAssetAuthoringIpc";
const mk=()=>{const handlers=new Map<string,any>(); return {handlers, ipcMain:{handle:testDouble.fn((c:string,h:any)=>handlers.set(c,h))}};};
describe("registerAssetAuthoringIpc",()=>{
it("registers channels",()=>{const {ipcMain}=mk(); registerAssetAuthoringIpc({ipcMain:ipcMain as any}); expect(ipcMain.handle.mock.calls.map((c:any)=>c[0])).toContain(DESKTOP_ASSET_AUTHORING_LIST_EFFECTIVE_SUMMARIES_REQUEST_CHANNEL.value);});
it("requires explicit workspace context", async()=>{const {handlers,ipcMain}=mk(); registerAssetAuthoringIpc({ipcMain:ipcMain as any, createWorkspaceAuthoredAssetUseCase:{execute:testDouble.fn()} as any, createAssetDraftUseCase:{execute:testDouble.fn()} as any, createAssetOverrideUseCase:{execute:testDouble.fn()} as any}); expect((await handlers.get(DESKTOP_ASSET_AUTHORING_CREATE_WORKSPACE_AUTHORED_ASSET_REQUEST_CHANNEL.value)(undefined,{payload:{}})).error.code).toBe("validation"); expect((await handlers.get(DESKTOP_ASSET_AUTHORING_CREATE_DRAFT_REQUEST_CHANNEL.value)(undefined,{payload:{}})).error.code).toBe("validation"); expect((await handlers.get(DESKTOP_ASSET_AUTHORING_CREATE_OVERRIDE_REQUEST_CHANNEL.value)(undefined,{payload:{}})).error.code).toBe("validation");});
it("maps publish mismatch failure and sanitizes unsafe fields", async()=>{const {handlers,ipcMain}=mk(); registerAssetAuthoringIpc({ipcMain:ipcMain as any, publishAssetDraftUseCase:{execute:testDouble.fn(async()=>({kind:"failure",failure:{code:"base-version-mismatch",message:"x"}}))} as any, authoredAssetRepository:{listAuthoredAssetRecords:testDouble.fn(async()=>({assets:[{id:"a",storagePath:"/tmp/secret"}]}))} as any}); const p=await handlers.get(DESKTOP_ASSET_AUTHORING_PUBLISH_DRAFT_REQUEST_CHANNEL.value)(undefined,{payload:{targetWorkspaceId:"w"}}); expect(p.error.code).toBe("base-version-mismatch"); const list=await handlers.get(DESKTOP_ASSET_AUTHORING_LIST_AUTHORED_ASSETS_REQUEST_CHANNEL.value)(undefined,{payload:{workspaceId:"w"}}); expect(JSON.stringify(list)).not.toContain("/tmp/secret");});
});
