import { describe, expect, it } from "bun:test";
import { readSource } from "../../tests/testUtils";

describe("ui/routes unit coverage", () => {
  it("defines route paths and route metadata", () => {
    const source = readSource("ui/routes/RouteConfig.ts");

    expect(source).toContain('export const ROUTE_PATHS = Object.freeze({');
    expect(source).toContain('login: "/auth/login"');
    expect(source).toContain('register: "/auth/register"');
    expect(source).toContain('build: "/build"');
    expect(source).toContain('explore: "/explore"');
    expect(source).toContain('run: "/run"');
    expect(source).toContain('workflowEditor: "/workflows/:workflowId"');
    expect(source).toContain('workflowContextWorkbench: "/workflows/:workflowId/context-workbench"');
    expect(source).toContain("export const APP_ROUTES");
    expect(source).toContain('key: "build"');
    expect(source).toContain('key: "login"');
    expect(source).toContain('key: "register"');
    expect(source).toContain('key: "explore"');
    expect(source).toContain('key: "run"');
    expect(source).toContain('key: "workflow-editor"');
    expect(source).toContain('key: "settings"');
    expect(source).toContain('key: "admin-shell"');
    expect(source).toContain('key: "admin-lite-shell"');
    expect(source).toContain('key: "authorization-reporting"');
    expect(source).toContain('key: "security-policy"');
    expect(source).toContain('key: "workspace-admin"');
    expect(source).toContain('key: "node-enrollment-review"');
    expect(source).toContain('key: "workspace-thin-membership"');
    expect(source).toContain('key: "workspace-invitation-accept"');
    expect(source).toContain('key: "identity-admin"');
    expect(source).toContain('key: "secrets-admin"');
    expect(source).toContain('key: "mcp"');
    expect(source).toContain('key: "services"');
    expect(source).toContain('key: "context"');
    expect(source).toContain('agentStudio: "/agent-studio"');
    expect(source).toContain('registry: "/studio-shell/registry"');
    expect(source).toContain('registryAssetDetail: "/studio-shell/registry/assets/:assetId"');
    expect(source).toContain('workflowStudio: "/studio-shell/workflow"');
    expect(source).toContain('workflowStudioMode: "/studio-shell/workflow/:modeId"');
    expect(source).toContain('contextBundleStudio: "/studio-shell/context-bundle"');
    expect(source).toContain('datasetPipelineStudio: "/studio-shell/dataset-pipeline"');
    expect(source).toContain('toolChainStudio: "/studio-shell/tool-chain"');
    expect(source).toContain('systemStudio: "/studio-shell/system"');
    expect(source).toContain('modelStudio: "/studio-shell/model"');
    expect(source).toContain('datasetStudio: "/studio-shell/dataset"');
    expect(source).toContain('toolStudio: "/studio-shell/tool"');
    expect(source).toContain('promptTemplateStudio: "/studio-shell/prompt-template"');
    expect(source).toContain('embeddingIndexStudio: "/studio-shell/embedding-index"');
    expect(source).toContain('configProfileStudio: "/studio-shell/config-profile"');
    expect(source).toContain('workspaceAdmin: "/settings/workspaces"');
    expect(source).toContain('adminShell: "/settings/admin"');
    expect(source).toContain('adminLiteShell: "/settings/admin-lite"');
    expect(source).toContain('nodeEnrollmentReview: "/settings/node-enrollments"');
    expect(source).toContain('authorizationReporting: "/settings/sharing/reporting"');
    expect(source).toContain('securityPolicy: "/settings/security-policy"');
    expect(source).toContain('workspaceThinMembership: "/settings/workspaces/thin"');
    expect(source).toContain('workspaceInvitationAccept: "/workspaces/:workspaceId/invitations/:invitationToken/accept"');
    expect(source).toContain('identityAdmin: "/settings/identity-admin"');
    expect(source).toContain('secretsAdmin: "/settings/secrets"');
    expect(source).toContain('key: "agent-studio"');
    expect(source).toContain('key: "registry"');
    expect(source).toContain('key: "registry-asset-detail"');
    expect(source).toContain('key: "workflow-studio"');
    expect(source).toContain('key: "workflow-studio-mode"');
    expect(source).toContain('key: "context-bundle-studio"');
    expect(source).toContain('key: "dataset-pipeline-studio"');
    expect(source).toContain('key: "tool-chain-studio"');
    expect(source).toContain('key: "system-studio"');
    expect(source).toContain('key: "dataset-studio"');
    expect(source).toContain('key: "tool-studio"');
    expect(source).toContain('key: "prompt-template-studio"');
    expect(source).toContain('key: "embedding-index-studio"');
    expect(source).toContain('key: "config-profile-studio"');
  });

  it("provides navigation helper and protected route behavior", () => {
    const configSource = readSource("ui/routes/RouteConfig.ts");
    const protectedRouteSource = readSource("ui/routes/ProtectedRoute.tsx");

    expect(configSource).toContain("getNavigationRoutes");
    expect(protectedRouteSource).toContain("useLocation");
    expect(protectedRouteSource).toContain("<Navigate");
    expect(protectedRouteSource).toContain("children ?? <Outlet />");
  });

  it("wires route tree to layout and pages", () => {
    const source = readSource("ui/routes/AppRouter.tsx");

    expect(source).toContain("createBrowserRouter");
    expect(source).toContain("<RouterProvider router={router} />");
    expect(source).toContain("<ProtectedRoute");
    expect(source).toContain("path: ROUTE_PATHS.build");
    expect(source).toContain("path: ROUTE_PATHS.login");
    expect(source).toContain("path: ROUTE_PATHS.register");
    expect(source).toContain("path: ROUTE_PATHS.explore");
    expect(source).toContain("path: ROUTE_PATHS.run");
    expect(source).toContain("path: ROUTE_PATHS.notFound");
    expect(source).toContain('path: "/index.html"');
    expect(source).toContain("path: ROUTE_PATHS.settings");
    expect(source).toContain("path: ROUTE_PATHS.adminShell");
    expect(source).toContain("path: ROUTE_PATHS.adminLiteShell");
    expect(source).toContain("path: ROUTE_PATHS.authorizationReporting");
    expect(source).toContain("path: ROUTE_PATHS.securityPolicy");
    expect(source).toContain("path: ROUTE_PATHS.workspaceAdmin");
    expect(source).toContain("path: ROUTE_PATHS.nodeEnrollmentReview");
    expect(source).toContain("path: ROUTE_PATHS.workspaceThinMembership");
    expect(source).toContain("path: ROUTE_PATHS.workspaceInvitationAccept");
    expect(source).toContain("path: ROUTE_PATHS.identityAdmin");
    expect(source).toContain("path: ROUTE_PATHS.secretsAdmin");
    expect(source).toContain("path: ROUTE_PATHS.mcp");
    expect(source).toContain("path: ROUTE_PATHS.services");
    expect(source).toContain("path: ROUTE_PATHS.agentStudio");
    expect(source).toContain("path: ROUTE_PATHS.studioShell");
    expect(source).toContain("path: ROUTE_PATHS.registry");
    expect(source).toContain("path: ROUTE_PATHS.registryAssetDetail");
    expect(source).toContain("path: ROUTE_PATHS.workflowStudio");
    expect(source).toContain("path: ROUTE_PATHS.workflowStudioMode");
    expect(source).toContain("path: ROUTE_PATHS.contextBundleStudio");
    expect(source).toContain("path: ROUTE_PATHS.datasetPipelineStudio");
    expect(source).toContain("path: ROUTE_PATHS.trainingRecipeStudio");
    expect(source).toContain("path: ROUTE_PATHS.toolChainStudio");
    expect(source).toContain("path: ROUTE_PATHS.systemStudio");
    expect(source).toContain("path: ROUTE_PATHS.modelStudio");
    expect(source).toContain("path: ROUTE_PATHS.datasetStudio");
    expect(source).toContain("path: ROUTE_PATHS.toolStudio");
    expect(source).toContain("path: ROUTE_PATHS.promptTemplateStudio");
    expect(source).toContain("path: ROUTE_PATHS.embeddingIndexStudio");
    expect(source).toContain("path: ROUTE_PATHS.configProfileStudio");
    expect(source).toContain("path: ROUTE_PATHS.context");
    expect(source).toContain("path: ROUTE_PATHS.workflowContextWorkbench");
    expect(source).toContain("LegacyWorkflowEditorRedirectPage");
    expect(source).not.toContain("WorkflowEditorPage");
  });
});
