import { parseApiEnvelope } from '../../../security/apiErrorEnvelope';
import { secureFetch } from '../../../security/secureFetch';
import type { AssetAuthoringEffectiveSourceSummary, AssetOverrideRecord, AuthoredAssetDraftRecord, AuthoredAssetRecord } from '../../../../../modules/contracts/asset-authoring';

type Result<T> = { ok: true; value: T } | { ok: false; error: { code: string; message: string } };
const e = (m: string, c = 'internal'): Result<never> => ({ ok: false, error: { code: c, message: m } });
const u = <T,>(x: any): Result<T> => x?.status === 'success' ? { ok: true, value: x.payload as T } : e(x?.error?.message ?? 'Unable to complete request.', x?.error?.code ?? 'internal');
const get = async (url: string) => parseApiEnvelope(await (await secureFetch(url, { method: 'GET' })).json());
const post = async (url: string, body: unknown, method: 'POST'|'PATCH'='POST') => parseApiEnvelope(await (await secureFetch(url, { method, headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) })).json());
export function createThinClientAssetAuthoringClient(base = '/api') { const b = base.replace(/\/+$/, ''); return {
  async listAuthoredAssets(workspaceId: string): Promise<Result<{ items: readonly AuthoredAssetRecord[] }>> { try { const r = u<{ assets: readonly AuthoredAssetRecord[] }>(await get(`${b}/asset-authoring/workspaces/${encodeURIComponent(workspaceId)}/authored-assets`)); return r.ok ? { ok: true, value: { items: r.value.assets ?? [] } } : r; } catch { return e('Unable to load custom assets.'); } },
  async listDrafts(workspaceId: string): Promise<Result<{ items: readonly AuthoredAssetDraftRecord[] }>> { try { const r = u<{ drafts: readonly AuthoredAssetDraftRecord[] }>(await get(`${b}/asset-authoring/workspaces/${encodeURIComponent(workspaceId)}/drafts`)); return r.ok ? { ok: true, value: { items: r.value.drafts ?? [] } } : r; } catch { return e('Unable to load drafts.'); } },
  async createDraft(i: { workspaceId: string; displayName: string; summary?: string; description?: string }) { try { return u(await post(`${b}/asset-authoring/workspaces/${encodeURIComponent(i.workspaceId)}/drafts`, { editableFields: { displayName: i.displayName, summary: i.summary, description: i.description } })); } catch { return e('Unable to create draft.'); } },
  async updateDraft(i: { workspaceId: string; draftId: string; summary?: string }) { try { return u(await post(`${b}/asset-authoring/workspaces/${encodeURIComponent(i.workspaceId)}/drafts/${encodeURIComponent(i.draftId)}`, { editableFieldsPatch: { summary: i.summary } }, 'PATCH')); } catch { return e('Unable to update draft.'); } },
  async publishDraft(workspaceId: string, draftId: string) { try { return u(await post(`${b}/asset-authoring/workspaces/${encodeURIComponent(workspaceId)}/drafts/${encodeURIComponent(draftId)}/publish`, {})); } catch { return e('Unable to publish draft.'); } },
  async listOverrides(workspaceId: string): Promise<Result<{ items: readonly AssetOverrideRecord[] }>> { try { const r = u<{ overrides: readonly AssetOverrideRecord[] }>(await get(`${b}/asset-authoring/workspaces/${encodeURIComponent(workspaceId)}/overrides`)); return r.ok ? { ok: true, value: { items: r.value.overrides ?? [] } } : r; } catch { return e('Unable to load customizations.'); } },
  async disableOverride(workspaceId: string, overrideId: string) { try { return u(await post(`${b}/asset-authoring/workspaces/${encodeURIComponent(workspaceId)}/overrides/${encodeURIComponent(overrideId)}/disable`, {})); } catch { return e('Unable to disable customization.'); } },
  async listEffectiveSummaries(workspaceId: string): Promise<Result<{ items: readonly AssetAuthoringEffectiveSourceSummary[] }>> { try { return u(await get(`${b}/asset-authoring/workspaces/${encodeURIComponent(workspaceId)}/effective-summaries`)); } catch { return e('Unable to load workspace usage summary.'); } },
}; }
