import { useCallback, useMemo, useRef, useState } from "react";
import type { RuntimeTaskStatus } from "../../../../../../modules/contracts/runtime";
import { createApiImageGenerationClient, type FinalizedImageAsset, type ImageGenerationApiClient } from "../api/apiImageGenerationClient";
const POLL_INTERVAL_MS = 1200;
type UiStatus = "idle"|"starting"|"queued"|"running"|"succeeded"|"finalizing"|"finalized"|"failed"|"cancelled";
export interface ImageGenerationFormState { prompt:string; negativePrompt:string; seed:string; width:string; height:string; steps:string; sampler:string; scheduler:string; model:string; numImages:string }
const toUiStatus=(s:RuntimeTaskStatus):UiStatus=> (s==="queued"||s==="running"||s==="succeeded"||s==="failed"||s==="cancelled")?s:"failed";
export function useImageGenerationFeature(client:ImageGenerationApiClient=createApiImageGenerationClient()) {
const [form,setForm]=useState<ImageGenerationFormState>({prompt:"",negativePrompt:"",seed:"",width:"512",height:"512",steps:"20",sampler:"euler",scheduler:"normal",model:"",numImages:"1"});
const [status,setStatus]=useState<UiStatus>("idle"); const [requestId,setRequestId]=useState<string>(); const [error,setError]=useState<string>(); const [results,setResults]=useState<FinalizedImageAsset[]>([]); const finalizedByRequestRef=useRef(new Set<string>());
const start=useCallback(async()=>{try{setError(undefined);setResults([]);setStatus("starting"); const started=await client.startImageGeneration({prompt:form.prompt,negativePrompt:form.negativePrompt||undefined,seed:form.seed?Number(form.seed):undefined,width:Number(form.width),height:Number(form.height),steps:Number(form.steps),sampler:form.sampler,scheduler:form.scheduler,model:form.model||undefined,numImages:Number(form.numImages)}); setRequestId(started.requestId); let current=started; setStatus(toUiStatus(started.status)); while(!["succeeded","failed","cancelled"].includes(current.status)){await new Promise(r=>setTimeout(r,POLL_INTERVAL_MS)); current=await client.readImageGeneration({requestId:started.requestId}); setStatus(toUiStatus(current.status));} if(current.status==="succeeded"){ setStatus("finalizing"); if(finalizedByRequestRef.current.has(started.requestId)){setStatus("finalized"); return;} let finalized=await client.finalizeImageGenerationIfCompleted({requestId:started.requestId}); if(!finalized.finalized && finalized.reason==="task not completed"){await client.readImageGeneration({requestId:started.requestId}); finalized=await client.finalizeImageGenerationIfCompleted({requestId:started.requestId});} if(finalized.finalized){finalizedByRequestRef.current.add(started.requestId); setResults(finalized.assets??[]); setStatus("finalized");} else {setStatus("failed"); setError(finalized.reason??"Finalization did not complete.");}}}catch(cause){setStatus("failed"); setError(cause instanceof Error?cause.message:"Image generation failed.");}},[client,form]);
const cancel=useCallback(async()=>{if(!requestId)return; await client.cancelImageGeneration({requestId}); setStatus("cancelled");},[client,requestId]);
const qualityNote=useMemo(()=> Number(form.width)<=256||Number(form.height)<=256||Number(form.steps)<15?"Low quality settings selected. Small dimensions or low step counts can produce blurry results.":undefined,[form.width,form.height,form.steps]);
return {form,setForm,status,error,requestId,results,start,cancel,qualityNote,createPreviewUrl:client.createArtifactMediaViewUrl};
}
