import { normalizeExecutionPlanRecord, type ExecutionPlanRecord } from "../../../contracts/execution-plans";
import type { ExecutionPlanListQuery, ExecutionPlanRepositoryPort } from "../../../application/ports/execution-plans";
import { LocalExecutionPlanRecordStore, type LocalExecutionPlanRecordStoreOptions, cloneJson } from "./local-execution-plan-record-store";

const MAX_LIMIT = 200;
export function createLocalExecutionPlanRepositoryAdapter(options: LocalExecutionPlanRecordStoreOptions): ExecutionPlanRepositoryPort {
  const store = new LocalExecutionPlanRecordStore(options);
  return {
    async saveExecutionPlan(plan) { const normalized = normalizeExecutionPlanRecord(plan); const plans = await store.readPlans(); await store.writePlans(upsert(plans, normalized)); return cloneJson(normalized); },
    async updateExecutionPlan(plan) { const normalized = normalizeExecutionPlanRecord(plan); const plans = await store.readPlans(); await store.writePlans(upsert(plans, normalized)); return cloneJson(normalized); },
    async getExecutionPlanById(workspaceId, executionPlanId) { requireWorkspace(workspaceId); const record = (await store.readPlans()).find((p) => p.workspaceId === workspaceId && p.id === executionPlanId); return record ? cloneJson(record) : undefined; },
    async listExecutionPlans(query) { requireWorkspace(query.workspaceId); const ordered = (await store.readPlans()).filter((p) => matches(p, query)).sort((a,b)=> b.updatedAt.localeCompare(a.updatedAt)||b.createdAt.localeCompare(a.createdAt)||a.id.localeCompare(b.id)); const start = query.cursor ? Number(query.cursor) || 0 : 0; const limit = Math.min(Math.max(query.limit ?? 50, 1), MAX_LIMIT); const page = ordered.slice(start, start + limit); const nextCursor = start + limit < ordered.length ? String(start + limit) : undefined; return { plans: cloneJson(page), nextCursor }; },
    async archiveExecutionPlan(workspaceId, executionPlanId, archivedAt) { requireWorkspace(workspaceId); const plans = await store.readPlans(); const i = plans.findIndex((p)=>p.workspaceId===workspaceId&&p.id===executionPlanId); if(i<0) return undefined; const next: ExecutionPlanRecord = normalizeExecutionPlanRecord({ ...plans[i], status: "archived", archivedAt, updatedAt: archivedAt }); const copy = [...plans]; copy[i]=next; await store.writePlans(copy); return cloneJson(next); },
  };
}
const upsert=(plans:readonly ExecutionPlanRecord[],plan:ExecutionPlanRecord)=>{const i=plans.findIndex((p)=>p.workspaceId===plan.workspaceId&&p.id===plan.id); if(i<0) return [...plans,plan]; const c=[...plans]; c[i]=plan; return c;};
const requireWorkspace=(w:string)=>{if(!w?.trim()) throw new Error("Execution plan repository requires explicit workspaceId.");};
function matches(p: ExecutionPlanRecord, q: ExecutionPlanListQuery): boolean { if(p.workspaceId!==q.workspaceId) return false; if(q.status&&p.status!==q.status) return false; if(q.sourceRuntimeReadinessBindingId&&p.sourceRuntimeReadinessBindingId!==q.sourceRuntimeReadinessBindingId) return false; if(q.sourceCompositionPlanId&&p.sourceCompositionPlanId!==q.sourceCompositionPlanId) return false; if(q.stepKind&&!p.steps.some((s)=>s.kind===q.stepKind)) return false; if(q.stepStatus&&!p.steps.some((s)=>s.status===q.stepStatus)) return false; if(q.adapterReferenceKind&&!p.adapterReferences.some((a)=>a.kind===q.adapterReferenceKind)) return false; if(q.safetyGateStatus&&!p.safetyGates.some((g)=>g.status===q.safetyGateStatus)) return false; if(q.archived!==undefined && (q.archived ? p.status!=="archived" : p.status==="archived")) return false; if(q.blocked!==undefined && (q.blocked ? p.status!=="blocked" : p.status==="blocked")) return false; if(q.missingInputs!==undefined && (q.missingInputs ? p.status!=="missing-inputs" : p.status==="missing-inputs")) return false; if(q.missingOutputs!==undefined && (q.missingOutputs ? p.status!=="missing-outputs" : p.status==="missing-outputs")) return false; if(q.providerSetupRequired!==undefined && (q.providerSetupRequired ? p.status!=="provider-setup-required" : p.status==="provider-setup-required")) return false; if(q.safetyReviewRequired!==undefined && (q.safetyReviewRequired ? p.status!=="safety-review-required" : p.status==="safety-review-required")) return false; if(q.stale!==undefined && (q.stale ? p.status!=="stale" : p.status==="stale")) return false; if(q.text){const t=q.text.toLowerCase(); const hay=[p.id,...p.steps.map(s=>s.label??""),...p.steps.map(s=>s.summary??"")].join(" ").toLowerCase(); if(!hay.includes(t)) return false;} return true; }
