import { normalizeAssetId, normalizeAssetReferenceKind } from "../../../../contracts/asset";
import { createWorkspaceId } from "../../../../contracts/workspace";
import type { WorkspaceAssetCompositionReadModelService } from "../../../../application/services/asset/workspace-asset-composition-read-model.service";
import type { AddProjectionToCompositionPlanUseCase, ArchiveAssetCompositionPlanUseCase, ConnectCompositionNodesUseCase, CreateAssetCompositionPlanUseCase, DisconnectCompositionNodesUseCase, ListAssetCompositionPlansUseCase, ReadAssetCompositionPlanUseCase, RemoveProjectionFromCompositionPlanUseCase, UpdateAssetCompositionPlanUseCase, ValidateAssetCompositionPlanUseCase } from "../../../../application/use-cases/asset-composition";
import type { IpcMainHandlePort } from "../ipcMainHandlePort";
const C={create:'asset-composition:create-plan',update:'asset-composition:update-plan',read:'asset-composition:read-plan',list:'asset-composition:list-plans',archive:'asset-composition:archive-plan',add:'asset-composition:add-projection',remove:'asset-composition:remove-projection',connect:'asset-composition:connect-nodes',disconnect:'asset-composition:disconnect-nodes',validate:'asset-composition:validate-plan',summaries:'asset-composition:list-plan-summaries',detail:'asset-composition:read-plan-detail',forProjection:'asset-composition:list-plans-for-projection',forEffective:'asset-composition:list-plans-for-effective-asset',attention:'asset-composition:list-plans-needing-attention'} as const;
const S=(v:unknown)=>typeof v==='string'?v.trim():''; const txt=(v:unknown)=>S(v).length>0; const fail=(op:string,code:string,m:string)=>({ok:false,error:{operation:op,code,message:m}}); const ok=(op:string,v:unknown)=>({ok:true,operation:op,value:v});
type Envelope={payload?:Record<string,unknown>};
export interface RegisterAssetCompositionIpcDependencies{ipcMain:IpcMainHandlePort;createPlan?:CreateAssetCompositionPlanUseCase;updatePlan?:UpdateAssetCompositionPlanUseCase;readPlan?:ReadAssetCompositionPlanUseCase;listPlans?:ListAssetCompositionPlansUseCase;archivePlan?:ArchiveAssetCompositionPlanUseCase;addProjection?:AddProjectionToCompositionPlanUseCase;removeProjection?:RemoveProjectionFromCompositionPlanUseCase;connectNodes?:ConnectCompositionNodesUseCase;disconnectNodes?:DisconnectCompositionNodesUseCase;validatePlan?:ValidateAssetCompositionPlanUseCase;readModel?:WorkspaceAssetCompositionReadModelService;}
export function registerAssetCompositionIpc(d:RegisterAssetCompositionIpcDependencies):void{
const cmd=(channel:string,uc:any,build:(e:Envelope,w:string)=>Record<string,unknown>)=>d.ipcMain.handle(channel,async(_e,req:Envelope)=>{const w=S(req?.payload?.targetWorkspaceId); if(!txt(w)) return fail(channel,'validation','targetWorkspaceId is required.'); if(!uc) return fail(channel,'unavailable','Operation unavailable.'); try{const r=await uc.execute(build(req,w)); return r.status==='failure'?fail(channel,r.failure.kind,'Operation failed.'):ok(channel,r.value);}catch{return fail(channel,'validation','Invalid request.');}});
cmd(C.create,d.createPlan,(r,w)=>({...(r.payload??{}),targetWorkspaceId:createWorkspaceId(w)})); cmd(C.update,d.updatePlan,(r,w)=>({...(r.payload??{}),targetWorkspaceId:createWorkspaceId(w)})); cmd(C.read,d.readPlan,(r,w)=>({...(r.payload??{}),targetWorkspaceId:createWorkspaceId(w)})); cmd(C.list,d.listPlans,(r,w)=>({...(r.payload??{}),targetWorkspaceId:createWorkspaceId(w)})); cmd(C.archive,d.archivePlan,(r,w)=>({...(r.payload??{}),targetWorkspaceId:createWorkspaceId(w)})); cmd(C.add,d.addProjection,(r,w)=>({...(r.payload??{}),targetWorkspaceId:createWorkspaceId(w)})); cmd(C.remove,d.removeProjection,(r,w)=>({...(r.payload??{}),targetWorkspaceId:createWorkspaceId(w)})); cmd(C.connect,d.connectNodes,(r,w)=>({...(r.payload??{}),targetWorkspaceId:createWorkspaceId(w)})); cmd(C.disconnect,d.disconnectNodes,(r,w)=>({...(r.payload??{}),targetWorkspaceId:createWorkspaceId(w)})); cmd(C.validate,d.validatePlan,(r,w)=>({...(r.payload??{}),targetWorkspaceId:createWorkspaceId(w)}));
 d.ipcMain.handle(C.summaries,async(_e,r:Envelope)=>!d.readModel?fail(C.summaries,'unavailable','Read unavailable.'):ok(C.summaries,await d.readModel.listCompositionPlanSummaries({targetWorkspaceId:createWorkspaceId(S(r?.payload?.targetWorkspaceId))} as never)));
 d.ipcMain.handle(C.detail,async(_e,r:Envelope)=>!d.readModel?fail(C.detail,'unavailable','Read unavailable.'):ok(C.detail,await d.readModel.readCompositionPlanDetail({targetWorkspaceId:createWorkspaceId(S(r?.payload?.targetWorkspaceId)),planId:S(r?.payload?.planId)})));
 d.ipcMain.handle(C.forProjection,async(_e,r:Envelope)=>!d.readModel?fail(C.forProjection,'unavailable','Read unavailable.'):ok(C.forProjection,await d.readModel.listPlansForProjection({targetWorkspaceId:createWorkspaceId(S(r?.payload?.targetWorkspaceId)),projectionId:S(r?.payload?.projectionId)})));
 d.ipcMain.handle(C.forEffective,async(_e,r:Envelope)=>{if(!d.readModel) return fail(C.forEffective,'unavailable','Read unavailable.'); const ref=r.payload?.effectiveAssetReference as Record<string,unknown>; return ok(C.forEffective,await d.readModel.listPlansForEffectiveAssetReference({targetWorkspaceId:createWorkspaceId(S(r?.payload?.targetWorkspaceId)),effectiveAssetReference:{kind:normalizeAssetReferenceKind(S(ref?.kind)),id:normalizeAssetId(S(ref?.id)),version:txt(ref?.version)?S(ref?.version):undefined}}));});
 d.ipcMain.handle(C.attention,async(_e,r:Envelope)=>!d.readModel?fail(C.attention,'unavailable','Read unavailable.'):ok(C.attention,await d.readModel.listPlansNeedingAttention({targetWorkspaceId:createWorkspaceId(S(r?.payload?.targetWorkspaceId))})));
}
