import { normalizeAssetId, normalizeAssetReferenceKind } from "../../../../contracts/asset";
import { createWorkspaceId } from "../../../../contracts/workspace";
import type { WorkspaceAssetCompositionReadModelService } from "../../../../application/services/asset/workspace-asset-composition-read-model.service";
import type { AddProjectionToCompositionPlanUseCase, ArchiveAssetCompositionPlanUseCase, ConnectCompositionNodesUseCase, CreateAssetCompositionPlanUseCase, DisconnectCompositionNodesUseCase, ListAssetCompositionPlansUseCase, ReadAssetCompositionPlanUseCase, RemoveProjectionFromCompositionPlanUseCase, UpdateAssetCompositionPlanUseCase, ValidateAssetCompositionPlanUseCase } from "../../../../application/use-cases/asset-composition";
import type { IpcMainHandlePort } from "../ipcMainHandlePort";
const C={create:'asset-composition:create-plan',update:'asset-composition:update-plan',read:'asset-composition:read-plan',list:'asset-composition:list-plans',archive:'asset-composition:archive-plan',add:'asset-composition:add-projection',remove:'asset-composition:remove-projection',connect:'asset-composition:connect-nodes',disconnect:'asset-composition:disconnect-nodes',validate:'asset-composition:validate-plan',summaries:'asset-composition:list-plan-summaries',detail:'asset-composition:read-plan-detail',forProjection:'asset-composition:list-plans-for-projection',forEffective:'asset-composition:list-plans-for-effective-asset',attention:'asset-composition:list-plans-needing-attention'} as const;
const S=(v:unknown)=>typeof v==='string'?v.trim():''; const txt=(v:unknown)=>S(v).length>0; const fail=(op:string,code:string,m:string)=>({ok:false,error:{operation:op,code,message:m}}); const ok=(op:string,v:unknown)=>({ok:true,operation:op,value:v});
type Envelope={payload?:Record<string,unknown>};
export interface RegisterAssetCompositionIpcDependencies{ipcMain:IpcMainHandlePort;createPlan?:CreateAssetCompositionPlanUseCase;updatePlan?:UpdateAssetCompositionPlanUseCase;readPlan?:ReadAssetCompositionPlanUseCase;listPlans?:ListAssetCompositionPlansUseCase;archivePlan?:ArchiveAssetCompositionPlanUseCase;addProjection?:AddProjectionToCompositionPlanUseCase;removeProjection?:RemoveProjectionFromCompositionPlanUseCase;connectNodes?:ConnectCompositionNodesUseCase;disconnectNodes?:DisconnectCompositionNodesUseCase;validatePlan?:ValidateAssetCompositionPlanUseCase;readModel?:WorkspaceAssetCompositionReadModelService;}
export function registerAssetCompositionIpc(d:RegisterAssetCompositionIpcDependencies):void{
const cmd=(channel:string,uc:any)=>d.ipcMain.handle(channel,async(_e,req:Envelope)=>{try{const w=S(req?.payload?.targetWorkspaceId); if(!txt(w)) return fail(channel,'validation','targetWorkspaceId is required.'); if(!uc) return fail(channel,'unavailable','Operation unavailable.'); const r=await uc.execute({...(req.payload??{}),targetWorkspaceId:createWorkspaceId(w)}); return r.status==='failure'?fail(channel,r.failure.kind,'Operation failed.'):ok(channel,r.value);}catch{return fail(channel,'validation','Invalid request.');}});
Object.values(C).slice(0,10).forEach((k)=>cmd(k,(d as any)[({[C.create]:'createPlan',[C.update]:'updatePlan',[C.read]:'readPlan',[C.list]:'listPlans',[C.archive]:'archivePlan',[C.add]:'addProjection',[C.remove]:'removeProjection',[C.connect]:'connectNodes',[C.disconnect]:'disconnectNodes',[C.validate]:'validatePlan'} as any)[k]]));
const read = (channel:string, handler:(payload:Record<string,unknown>)=>Promise<unknown>) => d.ipcMain.handle(channel, async(_e,req:Envelope)=>{ try { if (!d.readModel) return fail(channel,'unavailable','Read unavailable.'); const payload = req.payload ?? {}; const w = S(payload.targetWorkspaceId); if (!txt(w)) return fail(channel,'validation','targetWorkspaceId is required.'); return ok(channel, await handler({ ...payload, targetWorkspaceId: createWorkspaceId(w) })); } catch { return fail(channel,'validation','Invalid request.'); } });
read(C.summaries, async (p)=>d.readModel!.listCompositionPlanSummaries({ targetWorkspaceId: p.targetWorkspaceId as never }));
read(C.detail, async (p)=>{ const planId=S(p.planId); if(!txt(planId)) throw new Error(); const v = await d.readModel!.readCompositionPlanDetail({ targetWorkspaceId: p.targetWorkspaceId as never, planId }); return v ?? { notFound: true }; });
read(C.forProjection, async (p)=>{ const projectionId=S(p.projectionId); if(!txt(projectionId)) throw new Error(); return d.readModel!.listPlansForProjection({ targetWorkspaceId:p.targetWorkspaceId as never, projectionId }); });
read(C.forEffective, async (p)=>{ const ref=(p.effectiveAssetReference??{}) as Record<string,unknown>; return d.readModel!.listPlansForEffectiveAssetReference({ targetWorkspaceId:p.targetWorkspaceId as never, effectiveAssetReference:{kind:normalizeAssetReferenceKind(S(ref.kind)),id:normalizeAssetId(S(ref.id)),version:txt(ref.version)?S(ref.version):undefined} }); });
read(C.attention, async (p)=>d.readModel!.listPlansNeedingAttention({ targetWorkspaceId:p.targetWorkspaceId as never }));
}
