import type { AssetAuthoringEffectiveSourceSummary, AssetOverrideRecord, AuthoredAssetDraftRecord, AuthoredAssetRecord } from '../../../../../../../modules/contracts/asset-authoring';

type Result<T> = { ok: true; value: T } | { ok: false; error: { code: string; message: string } };
interface Api { listAuthoredAssets?: (i:{workspaceId:string})=>Promise<unknown>; listAssetDrafts?: (i:{targetWorkspaceId:string})=>Promise<unknown>; createAssetDraft?: (i:any)=>Promise<unknown>; updateAssetDraft?: (i:any)=>Promise<unknown>; publishAssetDraft?: (i:any)=>Promise<unknown>; listAssetOverrides?: (i:{targetWorkspaceId:string})=>Promise<unknown>; disableAssetOverride?: (i:any)=>Promise<unknown>; listAssetAuthoringEffectiveSummaries?: (i:{targetWorkspaceId:string})=>Promise<unknown>; }
const err=(message:string,code='internal'):Result<never>=>({ok:false,error:{code,message}});
const unwrap=<T,>(response:unknown):Result<T>=>{ const e=response as any; return e?.ok===true?{ok:true,value:e.value as T}:err(e?.error?.message??'Unable to complete request.',e?.error?.code??'internal'); };
const getApi=():Api=>((globalThis as any).window?.desktopApi??{}) as Api;

export function createDesktopAssetAuthoringClient(){ const api=getApi(); return {
async listAuthoredAssets(workspaceId:string):Promise<Result<{items:readonly AuthoredAssetRecord[]}>>{ if(typeof api.listAuthoredAssets!=='function') return err('Custom assets are not available yet.','unavailable'); const r=unwrap<{assets:readonly AuthoredAssetRecord[]}>(await api.listAuthoredAssets({workspaceId})); return r.ok?{ok:true,value:{items:r.value.assets??[]}}:r;},
async listDrafts(workspaceId:string):Promise<Result<{items:readonly AuthoredAssetDraftRecord[]}>>{ if(typeof api.listAssetDrafts!=='function') return err('Drafts are not available yet.','unavailable'); const r=unwrap<{drafts:readonly AuthoredAssetDraftRecord[]}>(await api.listAssetDrafts({targetWorkspaceId:workspaceId})); return r.ok?{ok:true,value:{items:r.value.drafts??[]}}:r;},
async createDraft(input:{workspaceId:string;displayName:string;summary?:string;description?:string}):Promise<Result<unknown>>{ if(typeof api.createAssetDraft!=='function') return err('Create draft is not available yet.','unavailable'); return unwrap(await api.createAssetDraft({targetWorkspaceId:input.workspaceId,editableFields:{displayName:input.displayName,summary:input.summary,description:input.description}}));},
async updateDraft(input:{workspaceId:string;draftId:string;displayName?:string;summary?:string;description?:string}):Promise<Result<unknown>>{ if(typeof api.updateAssetDraft!=='function') return err('Update draft is not available yet.','unavailable'); return unwrap(await api.updateAssetDraft({targetWorkspaceId:input.workspaceId,draftId:input.draftId,editableFieldsPatch:{displayName:input.displayName,summary:input.summary,description:input.description}}));},
async publishDraft(workspaceId:string,draftId:string):Promise<Result<unknown>>{ if(typeof api.publishAssetDraft!=='function') return err('Publish draft is not available yet.','unavailable'); return unwrap(await api.publishAssetDraft({targetWorkspaceId:workspaceId,draftId}));},
async listOverrides(workspaceId:string):Promise<Result<{items:readonly AssetOverrideRecord[]}>>{ if(typeof api.listAssetOverrides!=='function') return err('Workspace customizations are not available yet.','unavailable'); const r=unwrap<{overrides:readonly AssetOverrideRecord[]}>(await api.listAssetOverrides({targetWorkspaceId:workspaceId})); return r.ok?{ok:true,value:{items:r.value.overrides??[]}}:r;},
async disableOverride(workspaceId:string,overrideId:string):Promise<Result<unknown>>{ if(typeof api.disableAssetOverride!=='function') return err('Disable customization is not available yet.','unavailable'); return unwrap(await api.disableAssetOverride({targetWorkspaceId:workspaceId,overrideId}));},
async listEffectiveSummaries(workspaceId:string):Promise<Result<{items:readonly AssetAuthoringEffectiveSourceSummary[]}>>{ if(typeof api.listAssetAuthoringEffectiveSummaries!=='function') return err('Effective summary is not available yet.','unavailable'); return unwrap(await api.listAssetAuthoringEffectiveSummaries({targetWorkspaceId:workspaceId}));},
};}
