import { NodePort, NodePortCompatibilityProfile } from "../../../domain/nodes/NodePort";
import { NodeProperty } from "../../../domain/nodes/NodeProperty";
import type { ILangChainNodeCatalogDefinition } from "./VectorStoreUpsertNodeDefinition";

const projection = Object.freeze({
  group: "Tier 2 LLM",
  tags: Object.freeze(["context", "documents", "prompting"]),
  keywords: Object.freeze(["prepare context", "format documents", "rag context"]),
  supportsAuthoringView: true,
  supportsToolView: true,
});

export const CONTEXT_FORMATTER_NODE_DEFINITION: ILangChainNodeCatalogDefinition = Object.freeze({
  technicalName: "langchain.context_formatter",
  nonTechnicalName: "Prepare Context",
  technicalDescription:
    "Formats retrieved documents into a prompt-ready context string using a reusable template.",
  description:
    "Turn retrieved documents into a clean context block that another AI step can use.",
  inputPorts: Object.freeze([
    new NodePort({
      id: "documents",
      name: "Documents",
      description: "Documents that should be rendered into a single context string.",
      direction: "input",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["document"] }),
    }),
  ]),
  outputPorts: Object.freeze([
    new NodePort({
      id: "context",
      name: "Context",
      description: "The formatted context string.",
      direction: "output",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["text"] }),
    }),
  ]),
  properties: Object.freeze([
    new NodeProperty({
      id: "template",
      name: "Template",
      description: "Template used for each document. Supports {index}, {content}, and {metadata}.",
      type: "multiline-text",
      value: "[{index}] {content}",
      defaultValue: "[{index}] {content}",
      constraints: { required: true },
      projection: {
        label: "Template",
        description: "Template used for each document. Supports {index}, {content}, and {metadata}.",
        group: "Formatting",
        order: 0,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "textarea",
      },
      order: 0,
    }),
    new NodeProperty({
      id: "maxLength",
      name: "Max Length",
      description: "Maximum number of characters to keep in the final context output.",
      type: "integer",
      value: 2000,
      defaultValue: 2000,
      constraints: {
        required: true,
        min: 1,
        max: 20000,
        range: { min: 1, max: 20000, step: 1, defaultValue: 2000, clamp: true },
      },
      projection: {
        label: "Max length",
        description: "Maximum number of characters to keep in the final context output.",
        group: "Formatting",
        order: 1,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "integer",
      },
      order: 1,
    }),
    new NodeProperty({
      id: "maxTokens",
      name: "Max Tokens",
      description: "Optional approximate token cap applied after fragments are filtered and trimmed.",
      type: "integer",
      value: 0,
      defaultValue: 0,
      constraints: {
        min: 0,
        max: 100000,
        range: { min: 0, max: 100000, step: 1, defaultValue: 0, clamp: true },
      },
      projection: {
        label: "Token budget",
        description: "Optional approximate token cap applied after fragments are filtered and trimmed. Set 0 to ignore.",
        group: "Quality Controls",
        order: 2,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "integer",
      },
      isAdvanced: true,
      order: 2,
    }),
    new NodeProperty({
      id: "visibilityMode",
      name: "Visibility Mode",
      description: "Choose whether only basic fragments or both basic and advanced fragments are eligible.",
      type: "select",
      value: "advanced",
      defaultValue: "advanced",
      options: [
        { label: "Basic only", value: "basic", description: "Exclude fragments marked as advanced." },
        { label: "Basic + advanced", value: "advanced", description: "Allow all fragments that pass other filters." },
      ],
      constraints: { allowedValues: ["basic", "advanced"] },
      projection: {
        label: "Visibility",
        description: "Choose whether only basic fragments or both basic and advanced fragments are eligible.",
        group: "Quality Controls",
        order: 3,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "select",
      },
      isAdvanced: true,
      order: 3,
    }),
    new NodeProperty({
      id: "includeFragmentKinds",
      name: "Include Fragment Kinds",
      description: "Optional fragment kinds to allow. Leave empty to allow every kind.",
      type: "multi-select",
      value: [],
      defaultValue: [],
      options: [
        { label: "Instructions", value: "instructions" },
        { label: "Persona", value: "persona" },
        { label: "Domain Notes", value: "domain-notes" },
        { label: "Retrieved Context", value: "retrieved-context" },
        { label: "Examples", value: "examples" },
        { label: "Memory", value: "memory-snippets" },
        { label: "Formatting", value: "formatting-constraints" },
      ],
      projection: {
        label: "Allow kinds",
        description: "Optional fragment kinds to allow. Leave empty to allow every kind.",
        group: "Quality Controls",
        order: 4,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "multi-select",
      },
      isAdvanced: true,
      order: 4,
    }),
    new NodeProperty({
      id: "excludeFragmentKinds",
      name: "Exclude Fragment Kinds",
      description: "Optional fragment kinds to remove before budgeting.",
      type: "multi-select",
      value: [],
      defaultValue: [],
      options: [
        { label: "Instructions", value: "instructions" },
        { label: "Persona", value: "persona" },
        { label: "Domain Notes", value: "domain-notes" },
        { label: "Retrieved Context", value: "retrieved-context" },
        { label: "Examples", value: "examples" },
        { label: "Memory", value: "memory-snippets" },
        { label: "Formatting", value: "formatting-constraints" },
      ],
      projection: {
        label: "Block kinds",
        description: "Optional fragment kinds to remove before budgeting.",
        group: "Quality Controls",
        order: 5,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "multi-select",
      },
      isAdvanced: true,
      order: 5,
    }),
    new NodeProperty({
      id: "includeSources",
      name: "Include Sources",
      description: "Optional source labels or package aliases to allow.",
      type: "generic",
      value: [],
      defaultValue: [],
      projection: {
        label: "Allow sources",
        description: "Optional source labels or package aliases to allow.",
        group: "Quality Controls",
        order: 6,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "tags",
      },
      isAdvanced: true,
      order: 6,
    }),
    new NodeProperty({
      id: "excludeSources",
      name: "Exclude Sources",
      description: "Optional source labels or package aliases to remove before budgeting.",
      type: "generic",
      value: [],
      defaultValue: [],
      projection: {
        label: "Block sources",
        description: "Optional source labels or package aliases to remove before budgeting.",
        group: "Quality Controls",
        order: 7,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "tags",
      },
      isAdvanced: true,
      order: 7,
    }),
    new NodeProperty({
      id: "trimPartialFragments",
      name: "Trim Partial Fragments",
      description: "Allow the last retained fragment to be shortened to fit the active budget.",
      type: "boolean",
      value: true,
      defaultValue: true,
      projection: {
        label: "Allow partial trim",
        description: "Allow the last retained fragment to be shortened to fit the active budget.",
        group: "Quality Controls",
        order: 8,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "boolean",
      },
      isAdvanced: true,
      order: 8,
    }),
    new NodeProperty({
      id: "approximateCharactersPerToken",
      name: "Approximate Characters Per Token",
      description: "Fallback heuristic used when true tokenizer support is unavailable.",
      type: "integer",
      value: 4,
      defaultValue: 4,
      constraints: {
        min: 1,
        max: 16,
        range: { min: 1, max: 16, step: 1, defaultValue: 4, clamp: true },
      },
      projection: {
        label: "Chars per token",
        description: "Fallback heuristic used when true tokenizer support is unavailable.",
        group: "Quality Controls",
        order: 9,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "integer",
      },
      isAdvanced: true,
      order: 9,
    }),
  ]),
  projection,
});
