import { NodePort, NodePortCompatibilityProfile } from "@domain/nodes/NodePort";
import { NodeProperty } from "@domain/nodes/NodeProperty";
import type { ILangChainNodeCatalogDefinition } from "./VectorStoreUpsertNodeDefinition";

const projection = Object.freeze({
  group: "Tier 2 LLM",
  tags: Object.freeze(["rag", "question answering", "knowledge base"]),
  keywords: Object.freeze(["retrieval qa", "answer from documents", "knowledge", "sources"]),
  supportsAuthoringView: true,
  supportsToolView: true,
});

export const RETRIEVAL_QA_NODE_DEFINITION: ILangChainNodeCatalogDefinition = Object.freeze({
  technicalName: "langchain.retrieval_qa",
  nonTechnicalName: "Answer from Knowledge Base",
  technicalDescription:
    "Retrieves relevant documents and uses an LLM to answer a question grounded in those documents.",
  description:
    "Ask a question and get an answer based on your saved knowledge.",
  inputPorts: Object.freeze([
    new NodePort({
      id: "query",
      name: "Query",
      description: "The question that should be answered from retrieved knowledge.",
      direction: "input",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["text"] }),
    }),
    new NodePort({
      id: "knowledgeBase",
      name: "Knowledge Base",
      description: "A serializable knowledge base handle or semantic store for retrieval.",
      direction: "input",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["dataset", "json", "generic"] }),
    }),
    new NodePort({
      id: "model",
      name: "Model",
      description: "Optional model handle or model descriptor used to synthesize the answer.",
      direction: "input",
      compatibility: new NodePortCompatibilityProfile({
        valueTypes: ["model", "model-reference", "json"],
        isOptional: true,
      }),
    }),
  ]),
  outputPorts: Object.freeze([
    new NodePort({
      id: "answer",
      name: "Answer",
      description: "Grounded answer synthesized from the retrieved documents.",
      direction: "output",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["text"] }),
    }),
    new NodePort({
      id: "sources",
      name: "Sources",
      description: "Retrieved source documents used to answer the question.",
      direction: "output",
      cardinality: "many",
      compatibility: new NodePortCompatibilityProfile({ valueTypes: ["document", "json"] }),
    }),
  ]),
  properties: Object.freeze([
    new NodeProperty({
      id: "strategy",
      name: "Strategy",
      description: "How to combine retrieved documents before producing the final answer.",
      type: "select",
      value: "stuff",
      defaultValue: "stuff",
      options: [
        { label: "Stuff", value: "stuff", description: "Use all retrieved context in one pass." },
        { label: "Map Reduce", value: "map_reduce", description: "Summarize or answer in parts, then combine." },
        { label: "Refine", value: "refine", description: "Iteratively improve the answer with each document." },
      ],
      constraints: { required: true, allowedValues: ["stuff", "map_reduce", "refine"] },
      projection: {
        label: "Answering strategy",
        description: "Choose how the retrieved evidence should be combined for answering.",
        group: "Retrieval QA",
        order: 0,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "select",
      },
      order: 0,
    }),
    new NodeProperty({
      id: "topK",
      name: "Top K",
      description: "How many retrieved documents to use when answering the question.",
      type: "integer",
      value: 4,
      defaultValue: 4,
      constraints: {
        required: true,
        min: 1,
        max: 50,
        range: { min: 1, max: 50, step: 1, defaultValue: 4, clamp: true },
      },
      projection: {
        label: "Documents to use",
        description: "How many retrieved documents to use when answering the question.",
        group: "Retrieval QA",
        order: 1,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "integer",
      },
      order: 1,
    }),
    new NodeProperty({
      id: "includeSources",
      name: "Include Sources",
      description: "Return the retrieved source documents alongside the answer.",
      type: "boolean",
      value: true,
      defaultValue: true,
      projection: {
        label: "Return sources",
        description: "Include the supporting documents in the node output for inspection or downstream use.",
        group: "Outputs",
        order: 2,
        authorVisibility: "basic",
        toolVisibility: "basic",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "boolean",
      },
      order: 2,
    }),
    new NodeProperty({
      id: "systemPrompt",
      name: "System Prompt",
      description: "Optional system instructions that guide how answers should be generated from retrieved context.",
      type: "multiline-text",
      value: "",
      defaultValue: "",
      projection: {
        label: "Answering instructions",
        description: "Optional instructions for tone, constraints, or citation behavior when generating the answer.",
        group: "Prompting",
        order: 3,
        authorVisibility: "advanced",
        toolVisibility: "advanced",
        exposeInAuthorForm: true,
        exposeInTool: true,
        fieldTypeHint: "textarea",
      },
      isAdvanced: true,
      order: 3,
    }),
  ]),
  projection,
});

