import { useEffect, useMemo, useState } from 'react';
import { createDesktopEffectiveAssetProjectionsClient } from '../api/desktopEffectiveAssetProjectionsClient';
type Summary={projectionId:string;status:string;projectedFields?:Record<string,string>;diagnostics?:readonly {code:string}[];blockers?:readonly {code:string}[];readinessLabel?:string};
const statusLabel = (s: string) => ({'ready':'Ready for planning','draft-only':'Draft preview','blocked':'Blocked','conflicted':'Needs attention','invalid':'Invalid','source-missing':'Missing source','unsupported':'Not supported','stale':'Refresh needed','disabled':'Disabled'}[s] ?? 'Needs attention');
export function EffectiveAssetProjectionsFeature({ workspaceId }: { workspaceId: string }) {
  const client = useMemo(() => createDesktopEffectiveAssetProjectionsClient(), []);
  const [items, setItems] = useState<Summary[]>([]); const [message, setMessage] = useState('Loading...'); const [selectedId,setSelectedId]=useState<string|undefined>();
  useEffect(() => { void client.listProjections(workspaceId).then((r:any)=>{ if(!r.ok){setMessage(r.error.message);return;} setItems(r.value.summaries ?? []); setSelectedId((r.value.summaries?.[0]?.projectionId)); setMessage('');}); }, [client, workspaceId]);
  const selected=items.find((x)=>x.projectionId===selectedId); const counts={total:items.length,ready:items.filter((x)=>x.status==='ready').length,draft:items.filter((x)=>x.status==='draft-only').length,blocked:items.filter((x)=>['blocked','conflicted','disabled','stale','source-missing'].includes(x.status)).length};
  return <section><h2>Projection Readiness</h2>{message ? <p>{message}</p> : null}<p>Total: {counts.total} | Ready: {counts.ready} | Draft preview: {counts.draft} | Needs attention: {counts.blocked}</p><ul>{items.map((item)=> <li key={item.projectionId}><button onClick={()=>setSelectedId(item.projectionId)}><strong>{item.projectedFields?.['display-name'] ?? item.projectedFields?.summary ?? 'Effective asset'}</strong> — {statusLabel(item.status)}</button></li>)}</ul>{selected?<article><h3>Details</h3><p>Status: {statusLabel(selected.status)}</p><p>Readiness: {selected.readinessLabel ?? 'unknown'}</p><p>Diagnostics: {(selected.diagnostics??[]).map((d)=>d.code).join(', ')||'none'}</p><p>Blockers: {(selected.blockers??[]).map((b)=>b.code).join(', ')||'none'}</p></article>:null}</section>;
}
