import type { ImageGenerationRequest, ImageGenerationResult } from "../../../../../../modules/contracts/image-generation";
interface ApiResponseEnvelope { ok: boolean; value?: unknown; error?: { message?: string } }
export interface FinalizedImageAsset { assetId: string; artifactId: string; storageKey: string; mediaType: string; source?: string; metadata?: Record<string, unknown> }
export interface FinalizeImageGenerationResult { finalized: boolean; reason?: string; assets?: FinalizedImageAsset[] }
export interface ImageGenerationApiClient { startImageGeneration: (input: ImageGenerationRequest, context?: { source?: string }) => Promise<ImageGenerationResult>; readImageGeneration: (input: { requestId: string }, context?: { source?: string }) => Promise<ImageGenerationResult>; cancelImageGeneration: (input: { requestId: string }, context?: { source?: string }) => Promise<ImageGenerationResult>; finalizeImageGenerationIfCompleted: (input: { requestId: string }, context?: { source?: string }) => Promise<FinalizeImageGenerationResult>; createArtifactMediaViewUrl: (storageKey: string) => string }
const createApiUrl=(b:string,s:string)=>`${b.trim().replace(/\/+$/,"")||"/api"}${s}`;
const ensureEnvelope=(v:unknown)=>{if(typeof v==="object"&&v!==null&&"ok" in v)return v as ApiResponseEnvelope; throw new Error("Image generation response is not a valid API envelope.")};
const ensureSuccess=<T,>(r:ApiResponseEnvelope,p:(v:unknown)=>T)=>{if(!r.ok) throw new Error(r.error?.message??"Image generation request failed."); return p(r.value)};
async function postJson(base:string,path:string,body:Record<string,unknown>){const r=await fetch(createApiUrl(base,path),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});return ensureEnvelope(await r.json() as unknown)}
export function createApiImageGenerationClient(options:{apiBaseUrl?:string;source?:string}={}){const apiBaseUrl=options.apiBaseUrl??"/api"; const source=options.source??"thin-client.image-generation"; return {async startImageGeneration(input,context){return ensureSuccess(await postJson(apiBaseUrl,"/image-generation/start",{...input,source:context?.source??source}),v=>v as ImageGenerationResult)}, async readImageGeneration(input,context){return ensureSuccess(await postJson(apiBaseUrl,"/image-generation/read",{...input,source:context?.source??source}),v=>v as ImageGenerationResult)}, async cancelImageGeneration(input,context){return ensureSuccess(await postJson(apiBaseUrl,"/image-generation/cancel",{...input,source:context?.source??source}),v=>v as ImageGenerationResult)}, async finalizeImageGenerationIfCompleted(input,context){return ensureSuccess(await postJson(apiBaseUrl,"/image-generation/finalize",{...input,source:context?.source??source}),v=>v as FinalizeImageGenerationResult)}, createArtifactMediaViewUrl(storageKey){return `${createApiUrl(apiBaseUrl,"/artifact/media/view")}?storageKey=${encodeURIComponent(storageKey)}`}} as ImageGenerationApiClient}
