import { normalizeAssetId, normalizeAssetReferenceKind, type AssetMetadata, type AssetReference } from "../asset";
import { normalizeEffectiveAssetProjectionId, normalizeEffectiveAssetProjectionSourceKind, normalizeEffectiveAssetProjectionStatus } from "../effective-asset-projections";
import { createWorkspaceId } from "../workspace";
import { normalizeAssetCompositionCapabilityList, tryNormalizeAssetCompositionCapability as tryNormalizeCapability } from "./asset-composition-capability";
import { normalizeAssetCompositionBlocker, normalizeAssetCompositionDiagnostic, tryNormalizeAssetCompositionBlocker as tryNormalizeBlocker, tryNormalizeAssetCompositionDiagnostic as tryNormalizeDiagnostic, type AssetCompositionNormalizationResult } from "./asset-composition-diagnostics";
import { normalizeAssetCompositionNodeId, normalizeAssetCompositionPlanId, normalizeAssetCompositionRelationshipId } from "./asset-composition-identity";
import type { AddProjectionToCompositionPlanCommand, ArchiveAssetCompositionPlanCommand, ConnectCompositionNodesCommand, CreateAssetCompositionPlanCommand, DisconnectCompositionNodesCommand, ListAssetCompositionPlansCommand, ReadAssetCompositionPlanCommand, RefreshAssetCompositionPlanFromProjectionsCommand, RemoveProjectionFromCompositionPlanCommand, UpdateAssetCompositionPlanCommand, UpdateCompositionNodeRoleCommand, ValidateAssetCompositionPlanCommand } from "./asset-composition-commands";
import type { AssetCompositionNode, AssetCompositionPlan, AssetCompositionRelationship, SelectedAssetProjectionReference } from "./asset-composition-plan";
import { normalizeAssetCompositionProvenanceEvent, tryNormalizeAssetCompositionProvenanceEvent as tryNormalizeProvenance } from "./asset-composition-provenance";
import { normalizeAssetCompositionRelationshipKind } from "./asset-composition-relationship";
import { normalizeAssetCompositionNodeRole } from "./asset-composition-role";
import { normalizeAssetCompositionCompatibilityStatus, normalizeAssetCompositionNodeStatus, normalizeAssetCompositionPlanStatus } from "./asset-composition-status";

const UNSAFE = /(?:workflow|prompt|token|secret|path|base64|http|provider|runtime|command|env)/i;
const safeLabel = (v: string, f: string) => { const t = v.trim(); if (!t || t !== v || UNSAFE.test(t)) throw new Error(`${f} is invalid.`); return t; };
const isSafeIso = (v: string) => /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v);
const safeTimestamp = (v: string, f: string) => { const t = v.trim(); if (!isSafeIso(t)) throw new Error(`${f} is invalid.`); return t; };

const normalizeAssetReference = (r: AssetReference): AssetReference => ({ ...r, kind: normalizeAssetReferenceKind(r.kind), id: normalizeAssetId(r.id), ...(r.version ? { version: safeLabel(r.version, "version") } : {}) });
const safeMeta = (v?: AssetMetadata) => { if (!v) return undefined; const out: Record<string, unknown> = {}; for (const [k, x] of Object.entries(v)) { if (UNSAFE.test(k)) throw new Error("safe metadata is invalid."); if (typeof x === "string" && UNSAFE.test(x)) throw new Error("safe metadata is invalid."); if (x && typeof x === "object") out[k] = safeMeta(x as AssetMetadata); else out[k] = x; } return out as AssetMetadata; };

export const normalizeSelectedAssetProjectionReference = (v: SelectedAssetProjectionReference): SelectedAssetProjectionReference => ({ targetWorkspaceId: createWorkspaceId(v.targetWorkspaceId), projectionId: normalizeEffectiveAssetProjectionId(v.projectionId), ...(v.effectiveAssetReference ? { effectiveAssetReference: normalizeAssetReference(v.effectiveAssetReference) } : {}), ...(v.projectionStatusAtSelection ? { projectionStatusAtSelection: normalizeEffectiveAssetProjectionStatus(v.projectionStatusAtSelection) } : {}), ...(v.projectionSourceKind ? { projectionSourceKind: normalizeEffectiveAssetProjectionSourceKind(v.projectionSourceKind) } : {}), ...(v.displayLabel ? { displayLabel: safeLabel(v.displayLabel, "displayLabel") } : {}), ...(v.selectedAt ? { selectedAt: safeTimestamp(v.selectedAt, "selectedAt") } : {}) });
export const normalizeAssetCompositionRelationship = (v: AssetCompositionRelationship): AssetCompositionRelationship => ({ ...v, relationshipId: normalizeAssetCompositionRelationshipId(v.relationshipId), targetWorkspaceId: createWorkspaceId(v.targetWorkspaceId), sourceNodeId: normalizeAssetCompositionNodeId(v.sourceNodeId), targetNodeId: normalizeAssetCompositionNodeId(v.targetNodeId), kind: normalizeAssetCompositionRelationshipKind(v.kind), compatibilityStatus: normalizeAssetCompositionCompatibilityStatus(v.compatibilityStatus), diagnostics: v.diagnostics.map(normalizeAssetCompositionDiagnostic), blockers: v.blockers.map(normalizeAssetCompositionBlocker), ...(v.label ? { label: safeLabel(v.label, "label") } : {}), ...(v.summary ? { summary: safeLabel(v.summary, "summary") } : {}), createdAt: safeTimestamp(v.createdAt, "createdAt"), updatedAt: safeTimestamp(v.updatedAt, "updatedAt") });
export const normalizeAssetCompositionNode = (v: AssetCompositionNode): AssetCompositionNode => ({ ...v, nodeId: normalizeAssetCompositionNodeId(v.nodeId), targetWorkspaceId: createWorkspaceId(v.targetWorkspaceId), selectedProjection: normalizeSelectedAssetProjectionReference(v.selectedProjection), ...(v.effectiveAssetReference ? { effectiveAssetReference: normalizeAssetReference(v.effectiveAssetReference) } : {}), role: normalizeAssetCompositionNodeRole(v.role), status: normalizeAssetCompositionNodeStatus(v.status), requiredCapabilities: normalizeAssetCompositionCapabilityList(v.requiredCapabilities), providedCapabilities: normalizeAssetCompositionCapabilityList(v.providedCapabilities), diagnostics: v.diagnostics.map(normalizeAssetCompositionDiagnostic), blockers: v.blockers.map(normalizeAssetCompositionBlocker), ...(v.label ? { label: safeLabel(v.label, "label") } : {}), ...(v.summary ? { summary: safeLabel(v.summary, "summary") } : {}), createdAt: safeTimestamp(v.createdAt, "createdAt"), updatedAt: safeTimestamp(v.updatedAt, "updatedAt") });
export const normalizeAssetCompositionPlan = (v: AssetCompositionPlan): AssetCompositionPlan => ({ ...v, planId: normalizeAssetCompositionPlanId(v.planId), targetWorkspaceId: createWorkspaceId(v.targetWorkspaceId), name: safeLabel(v.name, "name"), ...(v.description ? { description: safeLabel(v.description, "description") } : {}), status: normalizeAssetCompositionPlanStatus(v.status), selectedProjections: v.selectedProjections.map(normalizeSelectedAssetProjectionReference), nodes: v.nodes.map(normalizeAssetCompositionNode), relationships: v.relationships.map(normalizeAssetCompositionRelationship), compatibilityDiagnostics: v.compatibilityDiagnostics.map(normalizeAssetCompositionDiagnostic), blockers: v.blockers.map(normalizeAssetCompositionBlocker), planningSummary: { ...v.planningSummary, planningReadiness: safeLabel(v.planningSummary.planningReadiness, "planningReadiness"), ...(v.planningSummary.diagnosticSummary ? { diagnosticSummary: safeLabel(v.planningSummary.diagnosticSummary, "diagnosticSummary") } : {}), ...(v.planningSummary.safeMetadata ? { safeMetadata: safeMeta(v.planningSummary.safeMetadata) } : {}) }, provenance: v.provenance.map(normalizeAssetCompositionProvenanceEvent), createdAt: safeTimestamp(v.createdAt, "createdAt"), updatedAt: safeTimestamp(v.updatedAt, "updatedAt"), ...(v.archivedAt ? { archivedAt: safeTimestamp(v.archivedAt, "archivedAt") } : {}) });

const t = <T>(fn: () => T): AssetCompositionNormalizationResult<T> => { try { return { status: "success", value: fn() }; } catch { return { status: "failure", diagnostics: [{ code: "asset-composition-workspace-invalid", severity: "error", message: "Sanitized normalization failure." }] }; } };
export const tryNormalizeSelectedAssetProjectionReference = (v: SelectedAssetProjectionReference) => t(() => normalizeSelectedAssetProjectionReference(v));
export const tryNormalizeAssetCompositionRelationship = (v: AssetCompositionRelationship) => t(() => normalizeAssetCompositionRelationship(v));
export const tryNormalizeAssetCompositionNode = (v: AssetCompositionNode) => t(() => normalizeAssetCompositionNode(v));
export const tryNormalizeAssetCompositionPlan = (v: AssetCompositionPlan) => t(() => normalizeAssetCompositionPlan(v));

export const normalizeCreateAssetCompositionPlanCommand=(v:CreateAssetCompositionPlanCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),name:safeLabel(v.name,"name")});
export const normalizeUpdateAssetCompositionPlanCommand=(v:UpdateAssetCompositionPlanCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),planId:normalizeAssetCompositionPlanId(v.planId),...(v.name?{name:safeLabel(v.name,"name")}:{}),...(v.status?{status:normalizeAssetCompositionPlanStatus(v.status)}:{})});
export const normalizeReadAssetCompositionPlanCommand=(v:ReadAssetCompositionPlanCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),planId:normalizeAssetCompositionPlanId(v.planId)});
export const normalizeListAssetCompositionPlansCommand=(v:ListAssetCompositionPlansCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),...(v.status?{status:normalizeAssetCompositionPlanStatus(v.status)}:{}),...(v.selectedProjectionId?{selectedProjectionId:normalizeEffectiveAssetProjectionId(v.selectedProjectionId)}:{}),...(v.effectiveAssetReference?{effectiveAssetReference:normalizeAssetReference(v.effectiveAssetReference)}:{}),...(v.nodeRole?{nodeRole:normalizeAssetCompositionNodeRole(v.nodeRole)}:{}),...(v.relationshipKind?{relationshipKind:normalizeAssetCompositionRelationshipKind(v.relationshipKind)}:{}),...(v.compatibilityStatus?{compatibilityStatus:normalizeAssetCompositionCompatibilityStatus(v.compatibilityStatus)}:{}),...(v.text?{text:safeLabel(v.text,"text")}:{})});
export const normalizeArchiveAssetCompositionPlanCommand=(v:ArchiveAssetCompositionPlanCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),planId:normalizeAssetCompositionPlanId(v.planId)});
export const normalizeAddProjectionToCompositionPlanCommand=(v:AddProjectionToCompositionPlanCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),planId:normalizeAssetCompositionPlanId(v.planId),projectionId:normalizeEffectiveAssetProjectionId(v.projectionId)});
export const normalizeRemoveProjectionFromCompositionPlanCommand=(v:RemoveProjectionFromCompositionPlanCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),planId:normalizeAssetCompositionPlanId(v.planId),projectionId:normalizeEffectiveAssetProjectionId(v.projectionId)});
export const normalizeUpdateCompositionNodeRoleCommand=(v:UpdateCompositionNodeRoleCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),planId:normalizeAssetCompositionPlanId(v.planId),nodeId:normalizeAssetCompositionNodeId(v.nodeId),role:normalizeAssetCompositionNodeRole(v.role)});
export const normalizeConnectCompositionNodesCommand=(v:ConnectCompositionNodesCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),planId:normalizeAssetCompositionPlanId(v.planId),sourceNodeId:normalizeAssetCompositionNodeId(v.sourceNodeId),targetNodeId:normalizeAssetCompositionNodeId(v.targetNodeId),relationshipKind:normalizeAssetCompositionRelationshipKind(v.relationshipKind),...(v.relationshipId?{relationshipId:normalizeAssetCompositionRelationshipId(v.relationshipId)}:{})});
export const normalizeDisconnectCompositionNodesCommand=(v:DisconnectCompositionNodesCommand)=>({...v,targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId),planId:normalizeAssetCompositionPlanId(v.planId),relationshipId:normalizeAssetCompositionRelationshipId(v.relationshipId)});
export const normalizeValidateAssetCompositionPlanCommand=(v:ValidateAssetCompositionPlanCommand)=>normalizeReadAssetCompositionPlanCommand(v);
export const normalizeRefreshAssetCompositionPlanFromProjectionsCommand=(v:RefreshAssetCompositionPlanFromProjectionsCommand)=>normalizeReadAssetCompositionPlanCommand(v);

