import type { AssetReference } from "../asset";
import { normalizeAssetId, normalizeAssetReferenceKind } from "../asset";
import { normalizeEffectiveAssetProjectionId } from "../effective-asset-projections";
import { createWorkspaceId, type WorkspaceActorRef, type WorkspaceId } from "../workspace";
import type { AssetCompositionNodeId, AssetCompositionPlanId, AssetCompositionRelationshipId } from "./asset-composition-identity";
import { normalizeAssetCompositionNodeId, normalizeAssetCompositionPlanId, normalizeAssetCompositionRelationshipId } from "./asset-composition-identity";
import type { AssetCompositionDiagnostic } from "./asset-composition-diagnostics";
export type AssetCompositionProvenanceKind="plan-created"|"projection-selected"|"projection-removed"|"node-role-assigned"|"relationship-added"|"relationship-removed"|"compatibility-checked"|"plan-validated"|"plan-archived"|"plan-refreshed-from-projections";
export interface AssetCompositionProvenanceEvent{readonly kind:AssetCompositionProvenanceKind;readonly targetWorkspaceId:WorkspaceId;readonly operationAt:string;readonly planId?:AssetCompositionPlanId;readonly nodeId?:AssetCompositionNodeId;readonly relationshipId?:AssetCompositionRelationshipId;readonly projectionId?:string;readonly effectiveAssetReference?:AssetReference;readonly actor?:WorkspaceActorRef;}
const KINDS: readonly AssetCompositionProvenanceKind[]=["plan-created","projection-selected","projection-removed","node-role-assigned","relationship-added","relationship-removed","compatibility-checked","plan-validated","plan-archived","plan-refreshed-from-projections"];
const isSafeIso=(v:string)=>/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v);
export const normalizeAssetCompositionProvenanceEvent=(v:AssetCompositionProvenanceEvent):AssetCompositionProvenanceEvent=>{ if(!KINDS.includes(v.kind)) throw new Error("Asset composition provenance kind is invalid."); if(!isSafeIso(v.operationAt.trim())) throw new Error("Asset composition provenance timestamp is invalid."); if(v.actor) throw new Error("Asset composition provenance actor is not supported."); return { ...v, kind:v.kind, targetWorkspaceId:createWorkspaceId(v.targetWorkspaceId), operationAt:v.operationAt.trim(), ...(v.planId?{planId:normalizeAssetCompositionPlanId(v.planId)}:{}), ...(v.nodeId?{nodeId:normalizeAssetCompositionNodeId(v.nodeId)}:{}), ...(v.relationshipId?{relationshipId:normalizeAssetCompositionRelationshipId(v.relationshipId)}:{}), ...(v.projectionId?{projectionId:normalizeEffectiveAssetProjectionId(v.projectionId)}:{}), ...(v.effectiveAssetReference?{effectiveAssetReference:{kind:normalizeAssetReferenceKind(v.effectiveAssetReference.kind),id:normalizeAssetId(v.effectiveAssetReference.id),...(v.effectiveAssetReference.version?{version:v.effectiveAssetReference.version.trim()}:{})}}:{})}; };
export const tryNormalizeAssetCompositionProvenanceEvent=(v:AssetCompositionProvenanceEvent):{status:"success";value:AssetCompositionProvenanceEvent}|{status:"failure";diagnostics:readonly AssetCompositionDiagnostic[]}=>{try{return{status:"success",value:normalizeAssetCompositionProvenanceEvent(v)};}catch{return{status:"failure",diagnostics:[{code:"asset-composition-workspace-invalid",severity:"error",message:"Sanitized normalization failure."}]};}};
