import type { AssetMetadata } from "../asset";
import { normalizeAssetCompositionBlockerId, normalizeAssetCompositionDiagnosticId, type AssetCompositionBlockerId, type AssetCompositionDiagnosticId } from "./asset-composition-identity";
export const ASSET_COMPOSITION_DIAGNOSTIC_CODES=["asset-composition-workspace-required","asset-composition-workspace-invalid","asset-composition-plan-name-required","asset-composition-plan-not-found","asset-composition-projection-required","asset-composition-projection-missing","asset-composition-projection-not-ready-for-planning","asset-composition-projection-blocked","asset-composition-projection-conflicted","asset-composition-projection-stale","asset-composition-projection-disabled","asset-composition-node-role-unsupported","asset-composition-relationship-kind-unsupported","asset-composition-relationship-node-missing","asset-composition-missing-dependency","asset-composition-capability-unsupported","asset-composition-plan-runtime-binding-deferred","asset-composition-execution-deferred","asset-composition-source-mutation-forbidden"] as const;
export type AssetCompositionDiagnosticCode=(typeof ASSET_COMPOSITION_DIAGNOSTIC_CODES)[number];
export type AssetCompositionDiagnosticSeverity="info"|"warning"|"error";
export interface AssetCompositionDiagnostic{readonly diagnosticId?:AssetCompositionDiagnosticId;readonly code:AssetCompositionDiagnosticCode;readonly severity:AssetCompositionDiagnosticSeverity;readonly message:string;readonly safeDetails?:AssetMetadata;}
export interface AssetCompositionBlocker{readonly blockerId?:AssetCompositionBlockerId;readonly code:AssetCompositionDiagnosticCode;readonly message:string;readonly safeDetails?:AssetMetadata;}
const UNSAFE=/(?:\bhttps?:\/\/|\b[a-zA-Z]:\\|\.\.|\/[\w.-]+|token|secret|api[_-]?key|command|env)/i;
const sanitize=(v:string)=>{const m=v.trim().replace(/[\u0000-\u001f\u007f]/g,""); return UNSAFE.test(m)?"Sanitized diagnostic detail.":m.slice(0,240)||"Sanitized diagnostic detail.";};
export const normalizeAssetCompositionDiagnostic=(d:AssetCompositionDiagnostic):AssetCompositionDiagnostic=>({...d, ...(d.diagnosticId?{diagnosticId:normalizeAssetCompositionDiagnosticId(d.diagnosticId)}:{}), message:sanitize(d.message)});
export const normalizeAssetCompositionBlocker=(b:AssetCompositionBlocker):AssetCompositionBlocker=>({...b, ...(b.blockerId?{blockerId:normalizeAssetCompositionBlockerId(b.blockerId)}:{}), message:sanitize(b.message)});
