import type { AssetReference, AssetMetadata } from "../asset";
import type { EffectiveAssetProjectionId, EffectiveAssetProjectionSourceKind, EffectiveAssetProjectionStatus } from "../effective-asset-projections";
import type { WorkspaceId } from "../workspace";
import type { AssetCompositionCapability } from "./asset-composition-capability";
import type { AssetCompositionBlocker, AssetCompositionDiagnostic } from "./asset-composition-diagnostics";
import type { AssetCompositionNodeId, AssetCompositionPlanId, AssetCompositionRelationshipId } from "./asset-composition-identity";
import type { AssetCompositionProvenanceEvent } from "./asset-composition-provenance";
import type { AssetCompositionRelationshipKind } from "./asset-composition-relationship";
import type { AssetCompositionNodeRole } from "./asset-composition-role";
import type { AssetCompositionCompatibilityStatus, AssetCompositionNodeStatus, AssetCompositionPlanStatus } from "./asset-composition-status";
export interface SelectedAssetProjectionReference{readonly targetWorkspaceId:WorkspaceId;readonly projectionId:EffectiveAssetProjectionId;readonly effectiveAssetReference?:AssetReference;readonly projectionStatusAtSelection?:EffectiveAssetProjectionStatus;readonly projectionSourceKind?:EffectiveAssetProjectionSourceKind;readonly displayLabel?:string;readonly selectedAt?:string;}
export interface AssetCompositionNode{readonly nodeId:AssetCompositionNodeId;readonly targetWorkspaceId:WorkspaceId;readonly selectedProjection:SelectedAssetProjectionReference;readonly effectiveAssetReference?:AssetReference;readonly role:AssetCompositionNodeRole;readonly status:AssetCompositionNodeStatus;readonly requiredCapabilities:readonly AssetCompositionCapability[];readonly providedCapabilities:readonly AssetCompositionCapability[];readonly diagnostics:readonly AssetCompositionDiagnostic[];readonly blockers:readonly AssetCompositionBlocker[];readonly label?:string;readonly summary?:string;readonly createdAt:string;readonly updatedAt:string;}
export interface AssetCompositionRelationship{readonly relationshipId:AssetCompositionRelationshipId;readonly targetWorkspaceId:WorkspaceId;readonly sourceNodeId:AssetCompositionNodeId;readonly targetNodeId:AssetCompositionNodeId;readonly kind:AssetCompositionRelationshipKind;readonly compatibilityStatus:AssetCompositionCompatibilityStatus;readonly diagnostics:readonly AssetCompositionDiagnostic[];readonly blockers:readonly AssetCompositionBlocker[];readonly label?:string;readonly summary?:string;readonly createdAt:string;readonly updatedAt:string;}
export interface AssetCompositionPlanningSummary{readonly totalNodes:number;readonly compatibleNodeCount:number;readonly blockedNodeCount:number;readonly conflictedNodeCount:number;readonly missingDependencyCount:number;readonly staleProjectionCount:number;readonly unsupportedCount:number;readonly totalRelationships:number;readonly compatibleRelationshipCount:number;readonly blockedRelationshipCount:number;readonly planningReadiness:string;readonly diagnosticSummary?:string;readonly safeMetadata?:AssetMetadata;}
export interface AssetCompositionPlan{readonly planId:AssetCompositionPlanId;readonly targetWorkspaceId:WorkspaceId;readonly name:string;readonly description?:string;readonly status:AssetCompositionPlanStatus;readonly selectedProjections:readonly SelectedAssetProjectionReference[];readonly nodes:readonly AssetCompositionNode[];readonly relationships:readonly AssetCompositionRelationship[];readonly compatibilityDiagnostics:readonly AssetCompositionDiagnostic[];readonly blockers:readonly AssetCompositionBlocker[];readonly planningSummary:AssetCompositionPlanningSummary;readonly provenance:readonly AssetCompositionProvenanceEvent[];readonly createdAt:string;readonly updatedAt:string;readonly archivedAt?:string;}
