import { useEffect, useMemo, useState } from 'react';
import { createDesktopAssetAuthoringClient } from '../api/desktopAssetAuthoringClient';

export function AssetAuthoringFeature({ workspaceId }: { workspaceId: string }) {
  const client = useMemo(() => createDesktopAssetAuthoringClient(), []);
  const [authored, setAuthored] = useState<any[]>([]); const [drafts,setDrafts]=useState<any[]>([]); const [overrides,setOverrides]=useState<any[]>([]); const [summaries,setSummaries]=useState<any[]>([]); const [message,setMessage]=useState('');
  const [name,setName]=useState(''); const [summary,setSummary]=useState('');
  const refresh = async()=>{ const [a,d,o,s]=await Promise.all([client.listAuthoredAssets(workspaceId),client.listDrafts(workspaceId),client.listOverrides(workspaceId),client.listEffectiveSummaries(workspaceId)]); if(a.ok)setAuthored(a.value.items); if(d.ok)setDrafts(d.value.items); if(o.ok)setOverrides(o.value.items); if(s.ok)setSummaries(s.value.items); if(!a.ok||!d.ok||!o.ok||!s.ok)setMessage('Some data is not available yet.'); };
  useEffect(()=>{void refresh();},[workspaceId]);
  return <section><h2>Asset Authoring</h2><h3>Custom Assets</h3><ul>{authored.length?authored.map((a:any)=><li key={a.authoredAssetId}><strong>{a.editableFields?.displayName||'Custom asset'}</strong> — Created in this workspace</li>):<li>No custom assets yet.</li>}</ul><h3>Drafts</h3><ul>{drafts.length?drafts.map((d:any)=><li key={d.draftId}><strong>{d.editableFields?.displayName||'Draft'}</strong> <button onClick={async()=>{await client.publishDraft(workspaceId,d.draftId);setMessage('Publish requested.');await refresh();}}>Publish draft</button> <button onClick={async()=>{await client.updateDraft({workspaceId,draftId:d.draftId,summary:'Updated in workspace'});setMessage('Draft updated.');await refresh();}}>Save safe edit</button></li>):<li>No drafts yet.</li>}</ul><h3>Create draft</h3><form onSubmit={async(e)=>{e.preventDefault(); if(!name.trim()){setMessage('Display name is required.'); return;} await client.createDraft({workspaceId,displayName:name,summary}); setName(''); setSummary(''); setMessage('Draft created.'); await refresh();}}><input aria-label='Display name' value={name} onChange={(e)=>setName(e.target.value)} /><input aria-label='Summary' value={summary} onChange={(e)=>setSummary(e.target.value)} /><button type='submit'>Create draft</button></form><h3>Workspace customizations</h3><p><small>Creating new customizations from this page is not available yet. Existing customizations can be reviewed here.</small></p><ul>{overrides.length?overrides.map((o:any)=><li key={o.overrideId}>{o.displayLabel||'Customization'} <button onClick={async()=>{await client.disableOverride(workspaceId,o.overrideId);setMessage('Customization disabled.');await refresh();}}>Disable customization</button></li>):<li>No workspace customizations yet.</li>}</ul><h3>What this workspace is using</h3><ul>{summaries.length?summaries.map((s:any,i:number)=><li key={i}>{s.effectiveSourceKind==='customization-conflicted'?'Needs attention':s.effectiveSourceKind==='customization-disabled'?'Disabled customization':'Customized in this workspace'}</li>):<li>No summary records yet.</li>}</ul>{message?<p>{message}</p>:null}</section>;
}
