import { useEffect, useMemo, useState } from 'react';
import { createDesktopAssetAuthoringClient } from '../api/desktopAssetAuthoringClient';

export function AssetAuthoringFeature({ workspaceId }: { workspaceId: string }) {
  const client = useMemo(() => createDesktopAssetAuthoringClient(), []);
  const [authored, setAuthored] = useState<Array<{ id: string; label: string }>>([]); const [drafts, setDrafts] = useState<Array<{ id: string; label: string }>>([]); const [overrides, setOverrides] = useState<Array<{ id: string; label: string }>>([]); const [summaries, setSummaries] = useState<Array<{ id: string; label: string }>>([]); const [message, setMessage] = useState('');
  const [name, setName] = useState(''); const [summary, setSummary] = useState('');
  const refresh = async () => { const [a, d, o, s] = await Promise.all([client.listAuthoredAssets(workspaceId), client.listDrafts(workspaceId), client.listOverrides(workspaceId), client.listEffectiveSummaries(workspaceId)]); if (a.ok) setAuthored(a.value.items.map((x:any)=>({id:x.authoredAssetId,label:x.editableFields?.displayName||'Authored asset'}))); if (d.ok) setDrafts(d.value.items.map((x:any)=>({id:x.draftId,label:x.editableFields?.displayName||'Draft'}))); if (o.ok) setOverrides(o.value.items.map((x:any)=>({id:x.overrideId,label:x.displayLabel||'Customization'}))); if (s.ok) setSummaries((s.value.items??[]).map((x:any,i:number)=>({id:String(i),label:x.effectiveSourceKind||'Summary'}))); if (!a.ok || !d.ok || !o.ok || !s.ok) setMessage('Some data is not available yet.'); };
  useEffect(() => { void refresh(); }, [workspaceId]);
  return <section><h2>Asset Authoring</h2><h3>Custom Assets</h3><ul>{authored.length ? authored.map((a) => <li key={a.id}><strong>{a.label}</strong></li>) : <li>No custom assets yet.</li>}</ul><h3>Drafts</h3><ul>{drafts.length ? drafts.map((d) => <li key={d.id}><strong>{d.label}</strong> <button onClick={async () => { const r=await client.publishDraft(workspaceId, d.id); setMessage(r.ok?'Publish requested.':'Publish unavailable.'); await refresh(); }}>Publish draft</button> <button onClick={async () => { const r=await client.updateDraft({ workspaceId, draftId: d.id, summary: 'Updated in workspace' }); setMessage(r.ok?'Draft updated.':'Draft update unavailable.'); await refresh(); }}>Save safe edit</button></li>) : <li>No drafts yet.</li>}</ul><h3>Create draft</h3><form onSubmit={async (e) => { e.preventDefault(); if (!name.trim()) { setMessage('Display name is required.'); return; } const r=await client.createDraft({ workspaceId, displayName: name, summary }); setName(''); setSummary(''); setMessage(r.ok?'Draft created.':'Draft creation unavailable.'); await refresh(); }}><input aria-label='Display name' value={name} onChange={(e) => setName(e.target.value)} /><input aria-label='Summary' value={summary} onChange={(e) => setSummary(e.target.value)} /><button type='submit'>Create draft</button></form><h3>Workspace customizations</h3><p><small>Creating new customizations is deferred until safe target selection/validation is available.</small></p><ul>{overrides.length ? overrides.map((o) => <li key={o.id}>{o.label} <button onClick={async () => { const r=await client.disableOverride(workspaceId, o.id); setMessage(r.ok?'Customization disabled.':'Disable unavailable.'); await refresh(); }}>Disable customization</button></li>) : <li>No workspace customizations yet.</li>}</ul><h3>What this workspace is using</h3><ul>{summaries.length ? summaries.map((s) => <li key={s.id}>{s.label}</li>) : <li>No summary records yet.</li>}</ul>{message ? <p>{message}</p> : null}</section>;
}
