import { parseApiEnvelope } from '../../../security/apiErrorEnvelope';
import { secureFetch } from '../../../security/secureFetch';
type Result<T> = { ok: true; value: T } | { ok: false; error: { code: string; message: string } };
const fail = (message: string, code = 'internal'): Result<never> => ({ ok: false, error: { code, message } });
type EnvelopeResult<T> = { ok?: boolean; value?: T; error?: { code?: string; message?: string } };
const unwrap = <T,>(v: unknown): Result<T> => { const r=v as EnvelopeResult<T>; return r?.ok===true?{ok:true,value:r.value as T}:fail(r?.error?.message ?? 'Unable to complete request.', r?.error?.code ?? 'internal'); };
const get = async (url: string) => parseApiEnvelope(await (await secureFetch(url, { method: 'GET' })).json());
const post = async (url: string, body: unknown) => parseApiEnvelope(await (await secureFetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) })).json());

export function createThinClientExecutionPlansClient(base='/api/execution-plans'){const b=base.replace(/\/+$/,'');return {
 async createExecutionPlan(input:{workspaceId:string;runtimeReadinessBindingId:string}){ if(!input.workspaceId||!input.runtimeReadinessBindingId) return fail('Workspace id and runtime readiness binding id are required.','validation'); try{return unwrap(await post(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/plans`, input));}catch{return fail('Plan preview preparation is not available yet.','unavailable');}},
 async validateExecutionPlan(input:{workspaceId:string;executionPlanId:string}){ if(!input.workspaceId||!input.executionPlanId) return fail('Workspace id and execution plan id are required.','validation'); try{return unwrap(await post(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/plans/${encodeURIComponent(input.executionPlanId)}/validate`, input));}catch{return fail('Preview checking is not available yet.','unavailable');}},
 async archiveExecutionPlan(input:{workspaceId:string;executionPlanId:string}){ if(!input.workspaceId||!input.executionPlanId) return fail('Workspace id and execution plan id are required.','validation'); try{return unwrap(await post(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/plans/${encodeURIComponent(input.executionPlanId)}/archive`, input));}catch{return fail('Execution plan archive is not available yet.','unavailable');}},
 async listExecutionPlanSummaries(input:{workspaceId:string; includeArchived?: boolean; limit?: number; cursor?: string; status?: string}){ if(!input.workspaceId) return fail('Workspace id is required.','validation'); const q=new URLSearchParams(); if(input.includeArchived!==undefined) q.set('archived', String(input.includeArchived)); if(input.limit!==undefined) q.set('limit', String(input.limit)); if(input.cursor) q.set('cursor', input.cursor); if(input.status) q.set('status', input.status); try{return unwrap(await get(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/plans${q.size?`?${q.toString()}`:''}`));}catch{return fail('Execution plan summaries are unavailable.','unavailable');}},
 async readExecutionPlanDetail(input:{workspaceId:string;executionPlanId:string}){ if(!input.workspaceId||!input.executionPlanId) return fail('Workspace id and execution plan id are required.','validation'); try{return unwrap(await get(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/plans/${encodeURIComponent(input.executionPlanId)}`));}catch{return fail('Plan preview details are not available yet.','unavailable');}},
 async listExecutionPlansForCompositionPlan(input:{workspaceId:string;compositionPlanId:string; includeArchived?: boolean}){ if(!input.workspaceId||!input.compositionPlanId) return fail('Workspace id and composition plan id are required.','validation'); const q=input.includeArchived!==undefined?`?archived=${String(input.includeArchived)}`:''; try{return unwrap(await get(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/composition-plans/${encodeURIComponent(input.compositionPlanId)}/plans${q}`));}catch{return fail('Plan preview details are not available yet.','unavailable');}},
 async readLatestExecutionPlanForCompositionPlan(input:{workspaceId:string;compositionPlanId:string; includeArchived?: boolean}){ if(!input.workspaceId||!input.compositionPlanId) return fail('Workspace id and composition plan id are required.','validation'); const q=input.includeArchived!==undefined?`?archived=${String(input.includeArchived)}`:''; try{return unwrap(await get(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/composition-plans/${encodeURIComponent(input.compositionPlanId)}/latest${q}`));}catch{return fail('Plan preview details are not available yet.','unavailable');}},
 async listExecutionPlansForRuntimeReadinessBinding(input:{workspaceId:string;runtimeReadinessBindingId:string; includeArchived?: boolean}){ if(!input.workspaceId||!input.runtimeReadinessBindingId) return fail('Workspace id and runtime readiness binding id are required.','validation'); const q=input.includeArchived!==undefined?`?archived=${String(input.includeArchived)}`:''; try{return unwrap(await get(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/runtime-readiness-bindings/${encodeURIComponent(input.runtimeReadinessBindingId)}/plans${q}`));}catch{return fail('Plan preview details are not available yet.','unavailable');}},
 async readLatestExecutionPlanForRuntimeReadinessBinding(input:{workspaceId:string;runtimeReadinessBindingId:string; includeArchived?: boolean}){ if(!input.workspaceId||!input.runtimeReadinessBindingId) return fail('Workspace id and runtime readiness binding id are required.','validation'); const q=input.includeArchived!==undefined?`?archived=${String(input.includeArchived)}`:''; try{return unwrap(await get(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/runtime-readiness-bindings/${encodeURIComponent(input.runtimeReadinessBindingId)}/latest${q}`));}catch{return fail('Plan preview details are not available yet.','unavailable');}},
 async listExecutionPlansNeedingAttention(input:{workspaceId:string}){ if(!input.workspaceId) return fail('Workspace id is required.','validation'); try{return unwrap(await get(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/needing-attention`));}catch{return fail('Execution plan summaries are unavailable.','unavailable');}},
 async summarizeWorkspaceExecutionPlans(input:{workspaceId:string}){ if(!input.workspaceId) return fail('Workspace id is required.','validation'); try{return unwrap(await get(`${b}/workspaces/${encodeURIComponent(input.workspaceId)}/summary`));}catch{return fail('Execution plan summaries are unavailable.','unavailable');}},
};}
