import type { ExecutionPlanRepositoryPort } from '../../ports/execution-plans';
import { createWorkspaceId, type WorkspaceId } from '../../../contracts/workspace';
import { normalizeExecutionPlanId } from '../../../contracts/execution-plans/execution-plan-identity';
import type { ExecutionAdapterReferenceStatus, ExecutionDependencyStatus, ExecutionPlanRecord, ExecutionPlanStatus, ExecutionSafetyGateStatus, ExecutionStepKind, ExecutionStepStatus } from '../../../contracts/execution-plans';

const STATUS_LABELS: Record<ExecutionPlanStatus, string> = {draft:'Draft',preparing:'Preparing','ready-for-review':'Ready for review','needs-setup':'Needs setup','missing-inputs':'Missing input','missing-outputs':'Missing output','provider-setup-required':'Provider setup required','safety-review-required':'Safety review required',blocked:'Blocked',stale:'Refresh needed',invalid:'Invalid',archived:'Archived'};
const STEP_STATUS_LABELS: Record<ExecutionStepStatus,string>={planned:'Planned','needs-input':'Needs input','needs-output':'Needs output','needs-provider-setup':'Needs provider setup','needs-review':'Needs review',blocked:'Blocked',stale:'Refresh needed',invalid:'Invalid',deferred:'Deferred'};
const STEP_KIND_LABELS: Record<ExecutionStepKind,string>={'prepare-input':'Prepare input','transform-data':'Transform data','generate-image':'Generate image','generate-text':'Generate text','embed-content':'Embed content','store-artifact':'Store artifact','read-artifact':'Read artifact','call-api':'Call API','compose-output':'Compose output','validate-output':'Validate output','manual-review':'Manual review','safety-check':'Safety check','provider-setup-check':'Provider setup check','runtime-setup-check':'Runtime setup check'};
const safe=(x?:string)=>x?.replace(/(?:https?:\/\/|\/[\w./-]+|token|secret|password|api[_-]?key|private[_-]?key|stack\s*trace|command\s*output|workflow\s*json|prompt\s*text|base64|signed\s*url)/gi,'[redacted]').trim();

export class ExecutionPlanReadModelService {
  constructor(private readonly repo: ExecutionPlanRepositoryPort) {}
  private ws(v:string|undefined):WorkspaceId{ if(!v?.trim()) throw new Error('validation:workspaceId'); return createWorkspaceId(v); }
  private async list(workspaceId: WorkspaceId, query: any={}) { return (await this.repo.listExecutionPlans({ workspaceId, ...query })).plans; }
  private summary(p: ExecutionPlanRecord){ const reqIn=p.inputs.filter(i=>i.required); const reqOut=p.outputs.filter(o=>o.required); const attention=this.needsAttention(p);
    return { executionPlanId:p.id, workspaceId:p.workspaceId, sourceCompositionPlanId:p.sourceCompositionPlanId, sourceRuntimeReadinessBindingId:p.sourceRuntimeReadinessBindingId, sourceReadinessStatus:safe(p.sourceReadinessStatus), executionPlanStatus:p.status, statusLabel:STATUS_LABELS[p.status], needsAttention:attention, attentionLabel:attention?'Needs attention':'Ready for review', stepCount:p.steps.length,inputCount:p.inputs.length,outputCount:p.outputs.length,dependencyCount:p.dependencies.length,adapterReferenceCount:p.adapterReferences.length,safetyGateCount:p.safetyGates.length,blockerCount:p.blockers.length,diagnosticCount:p.diagnostics.length,missingInputCount:reqIn.filter(i=>['missing','blocked','stale','invalid'].includes(i.status)).length,missingOutputCount:reqOut.filter(i=>['missing','blocked','stale','invalid'].includes(i.status)).length,providerSetupRequiredCount:p.adapterReferences.filter(a=>['needs-setup','missing','blocked','unsupported','stale','invalid'].includes(a.status)).length,safetyReviewRequiredCount:p.safetyGates.filter(g=>['needs-review','blocked','failed'].includes(g.status)).length,manualDeferredStepCount:p.steps.filter(s=>s.kind==='manual-review'||s.status==='deferred').length,stale:p.status==='stale',invalid:p.status==='invalid',resourceEstimateSummary:{compute:p.resourceEstimates[0]?.compute??'unknown',storage:p.resourceEstimates[0]?.storage??'unknown',duration:p.resourceEstimates[0]?.duration??'unknown',providerCategoryCount:new Set(p.adapterReferences.map((a)=>a.providerKind).filter(Boolean)).size},createdAt:p.createdAt,updatedAt:p.updatedAt,archivedAt:p.archivedAt };
  }
  private needsAttention(p:ExecutionPlanRecord){ if(['needs-setup','missing-inputs','missing-outputs','provider-setup-required','safety-review-required','blocked','stale','invalid'].includes(p.status)) return true; if(p.blockers.length) return true; if(p.steps.some(s=>['blocked','stale','invalid','needs-input','needs-output','needs-provider-setup','needs-review'].includes(s.status))) return true; if(p.inputs.some(i=>i.required&&['missing','blocked','stale','invalid'].includes(i.status))) return true; if(p.outputs.some(i=>i.required&&['missing','blocked','stale','invalid'].includes(i.status))) return true; if(p.adapterReferences.some(a=>['missing','needs-setup','blocked','unsupported','stale','invalid'].includes(a.status))) return true; if(p.safetyGates.some(g=>['blocked','failed','needs-review'].includes(g.status))) return true; return false; }

  async listExecutionPlanSummaries(request:{workspaceId:string; includeArchived?:boolean; limit?:number; cursor?:string; status?:ExecutionPlanStatus}){ const ws=this.ws(request.workspaceId); const plans=await this.list(ws,{archived:request.includeArchived?undefined:false,limit:request.limit,cursor:request.cursor,status:request.status}); return {summaries:plans.map((p)=>this.summary(p))}; }
  async readExecutionPlanDetail(request:{workspaceId:string; executionPlanId:string}){ const ws=this.ws(request.workspaceId); const id=normalizeExecutionPlanId(request.executionPlanId); const p=await this.repo.getExecutionPlanById(ws,id); if(!p||p.workspaceId!==ws) return undefined; const summary=this.summary(p); return {summary, stepSummaries:p.steps.map((s)=>({stepId:s.id,sourceNodeId:s.sourceNodeId,sourceRelationshipId:s.sourceRelationshipId,stepKind:s.kind,stepKindLabel:STEP_KIND_LABELS[s.kind],stepStatus:s.status,stepStatusLabel:STEP_STATUS_LABELS[s.status],label:safe(s.label),summary:safe(s.summary),inputCount:s.inputIds.length,outputCount:s.outputIds.length,dependencyCount:s.dependencyIds.length,adapterReferenceCount:s.requiredAdapterReferenceIds.length,safetyGateCount:s.safetyGateIds.length,blockerCount:s.blockers.length,diagnosticCount:s.diagnostics.length,needsAttention:['blocked','stale','invalid','needs-input','needs-output','needs-provider-setup','needs-review'].includes(s.status),attentionLabel:['blocked','stale','invalid','needs-input','needs-output','needs-provider-setup','needs-review'].includes(s.status)?'Needs attention':'Ready for review'})),
inputSummaries:p.inputs.map((i)=>({inputId:i.id,stepId:i.stepId,inputKind:i.kind,inputKindLabel:i.kind.replace(/-/g,' '),inputStatus:i.status,inputStatusLabel:i.status.replace(/-/g,' '),label:safe(i.label),summary:safe(i.summary),required:i.required,blockerCount:i.blockers.length,diagnosticCount:i.diagnostics.length,needsAttention:i.required&&['missing','blocked','stale','invalid'].includes(i.status)})),
outputSummaries:p.outputs.map((o)=>({outputId:o.id,stepId:o.stepId,outputKind:o.kind,outputKindLabel:o.kind.replace(/-/g,' '),outputStatus:o.status,outputStatusLabel:o.status.replace(/-/g,' '),label:safe(o.label),summary:safe(o.summary),required:o.required,blockerCount:o.blockers.length,diagnosticCount:o.diagnostics.length,needsAttention:o.required&&['missing','blocked','stale','invalid'].includes(o.status)})),
dependencySummaries:p.dependencies.map((d)=>({dependencyId:d.id,dependencyKind:d.kind,dependencyKindLabel:d.kind.replace(/-/g,' '),dependencyStatus:(d.status as ExecutionDependencyStatus),dependencyStatusLabel:d.status.replace(/-/g,' '),sourceStepId:d.sourceStepId,targetStepId:d.targetStepId,inputId:d.inputId,outputId:d.outputId,adapterReferenceId:d.adapterReferenceId,safetyGateId:d.safetyGateId,label:safe(d.label),summary:safe(d.summary),blockerCount:d.blockers.length,diagnosticCount:d.diagnostics.length,needsAttention:['missing','blocked','stale','invalid'].includes(d.status)})),
adapterReferenceSummaries:p.adapterReferences.map((a)=>({adapterReferenceId:a.id,adapterReferenceKind:a.kind,adapterReferenceKindLabel:a.kind.replace(/-/g,' '),adapterReferenceStatus:(a.status as ExecutionAdapterReferenceStatus),adapterReferenceStatusLabel:a.status==='available-by-readiness'?'Available from setup':a.status.replace(/-/g,' '),providerKind:safe(a.providerKind),capabilityKind:safe(a.capabilityKind),sourceRuntimeReadinessBindingId:a.sourceRuntimeReadinessBindingId,selectedSetupReferenceLabel:a.sourceRuntimeBindingId?'Selected setup reference':undefined,label:safe(a.label),summary:safe(a.summary),blockerCount:a.blockers.length,diagnosticCount:a.diagnostics.length,needsAttention:['missing','needs-setup','blocked','unsupported','stale','invalid'].includes(a.status)})),
safetyGateSummaries:p.safetyGates.map((g)=>({safetyGateId:g.id,safetyGateKind:g.kind,safetyGateKindLabel:g.kind.replace(/-/g,' '),safetyGateStatus:(g.status as ExecutionSafetyGateStatus),safetyGateStatusLabel:g.status==='passed-by-plan'?'Passed by plan':g.status.replace(/-/g,' '),targetStepId:g.stepId,targetInputId:g.inputId,targetOutputId:g.outputId,targetAdapterReferenceId:g.adapterReferenceId,label:safe(g.label),summary:safe(g.summary),blockerCount:g.blockers.length,diagnosticCount:g.diagnostics.length,needsAttention:['needs-review','blocked','failed'].includes(g.status)})),
resourceEstimateSummaries:p.resourceEstimates.map((r)=>({estimateId:r.id,category:'execution-plan',estimate:{compute:r.compute,storage:r.storage,duration:r.duration},label:'Resource estimate',summary:safe(r.summary)})),
blockers:p.blockers.map((b)=>({code:b.code,severity:'error',message:safe(b.message),category:'execution-plan',targetReferenceKind:safe(b.targetReferenceKind),targetReferenceId:safe(b.targetReferenceId)})), diagnostics:p.diagnostics.map((d)=>({code:d.code,severity:d.severity,message:safe(d.message),category:'execution-plan',targetReferenceKind:safe(d.targetReferenceKind),targetReferenceId:safe(d.targetReferenceId)})), provenanceSummary:{createdAt:p.createdAt,lastStatusUpdateAt:p.updatedAt,lastValidationAt:p.provenance.find((x)=>x.kind==='blockers-detected')?.at,lastProviderPlanningAt:p.provenance.find((x)=>x.kind==='adapter-references-planned')?.at,lastSafetyGateEvaluationAt:p.provenance.find((x)=>x.kind==='safety-gates-planned')?.at,planningEventCount:p.provenance.filter((x)=>x.kind.includes('planned')).length,validationEventCount:p.provenance.filter((x)=>x.kind==='blockers-detected').length}}; }
  async listExecutionPlansForCompositionPlan(r:{workspaceId:string; compositionPlanId:string; includeArchived?:boolean}){ const ws=this.ws(r.workspaceId); const plans=await this.list(ws,{sourceCompositionPlanId:r.compositionPlanId,archived:r.includeArchived?undefined:false}); return plans.map((p)=>this.summary(p)); }
  async readLatestExecutionPlanForCompositionPlan(r:{workspaceId:string; compositionPlanId:string; includeArchived?:boolean}){ const x=await this.listExecutionPlansForCompositionPlan(r); return x.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)||b.executionPlanId.localeCompare(a.executionPlanId))[0]; }
  async listExecutionPlansForRuntimeReadinessBinding(r:{workspaceId:string; runtimeReadinessBindingId:string; includeArchived?:boolean}){ const ws=this.ws(r.workspaceId); const plans=await this.list(ws,{sourceRuntimeReadinessBindingId:r.runtimeReadinessBindingId,archived:r.includeArchived?undefined:false}); return plans.map((p)=>this.summary(p)); }
  async readLatestExecutionPlanForRuntimeReadinessBinding(r:{workspaceId:string; runtimeReadinessBindingId:string; includeArchived?:boolean}){ const x=await this.listExecutionPlansForRuntimeReadinessBinding(r); return x.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)||b.executionPlanId.localeCompare(a.executionPlanId))[0]; }
  async listExecutionPlansNeedingAttention(r:{workspaceId:string}){ const {summaries}=await this.listExecutionPlanSummaries({workspaceId:r.workspaceId}); return summaries.filter((s)=>s.needsAttention); }
  async summarizeWorkspaceExecutionPlans(r:{workspaceId:string}){ const {summaries}=await this.listExecutionPlanSummaries({workspaceId:r.workspaceId,includeArchived:true}); const byStatus=summaries.reduce<Record<string,number>>((a,s)=>((a[s.executionPlanStatus]=(a[s.executionPlanStatus]??0)+1),a),{}); return {total:summaries.length,byStatus,needingAttention:summaries.filter((x)=>x.needsAttention).length,readyForReviewCount:byStatus['ready-for-review']??0,missingInputCount:byStatus['missing-inputs']??0,missingOutputCount:byStatus['missing-outputs']??0,providerSetupRequiredCount:byStatus['provider-setup-required']??0,safetyReviewRequiredCount:byStatus['safety-review-required']??0,blockedCount:byStatus.blocked??0,staleCount:byStatus.stale??0,invalidCount:byStatus.invalid??0,stepTotal:summaries.reduce((a,s)=>a+s.stepCount,0),inputTotal:summaries.reduce((a,s)=>a+s.inputCount,0),outputTotal:summaries.reduce((a,s)=>a+s.outputCount,0),dependencyTotal:summaries.reduce((a,s)=>a+s.dependencyCount,0),adapterReferenceTotal:summaries.reduce((a,s)=>a+s.adapterReferenceCount,0),safetyGateTotal:summaries.reduce((a,s)=>a+s.safetyGateCount,0)}; }
}
