import type { ExecutionPlanRepositoryPort } from '../../ports/execution-plans';
import { createWorkspaceId, type WorkspaceId } from '../../../contracts/workspace';
import { normalizeExecutionPlanId } from '../../../contracts/execution-plans/execution-plan-identity';
import type { ExecutionAdapterReferenceKind, ExecutionAdapterReferenceStatus, ExecutionDependencyKind, ExecutionDependencyStatus, ExecutionInputKind, ExecutionInputOutputStatus, ExecutionOutputKind, ExecutionPlanRecord, ExecutionPlanStatus, ExecutionSafetyGateKind, ExecutionSafetyGateStatus, ExecutionStepKind, ExecutionStepStatus } from '../../../contracts/execution-plans';

const STATUS_LABELS: Record<ExecutionPlanStatus, string> = {draft:'Draft',preparing:'Preparing','ready-for-review':'Ready for review','needs-setup':'Needs setup','missing-inputs':'Missing input','missing-outputs':'Missing output','provider-setup-required':'Provider setup required','safety-review-required':'Safety review required',blocked:'Blocked',stale:'Refresh needed',invalid:'Invalid',archived:'Archived'};
const STEP_STATUS_LABELS: Record<ExecutionStepStatus,string>={planned:'Planned','needs-input':'Needs input','needs-output':'Needs output','needs-provider-setup':'Needs provider setup','needs-review':'Needs review',blocked:'Blocked',stale:'Refresh needed',invalid:'Invalid',deferred:'Deferred'};
const STEP_KIND_LABELS: Record<ExecutionStepKind,string>={'prepare-input':'Prepare input','transform-data':'Transform data','generate-image':'Generate image','generate-text':'Generate text','embed-content':'Embed content','store-artifact':'Store artifact','read-artifact':'Read artifact','call-api':'Call API','compose-output':'Compose output','validate-output':'Validate output','manual-review':'Manual review','safety-check':'Safety check','provider-setup-check':'Provider setup check','runtime-setup-check':'Runtime setup check'};
const INPUT_KIND_LABELS: Record<ExecutionInputKind, string> = {'user-provided':'User provided','asset-reference':'Asset reference','artifact-reference':'Artifact reference','workspace-data':'Workspace data','readiness-selection':'Setup selection','policy-context':'Policy context'};
const IO_STATUS_LABELS: Record<ExecutionInputOutputStatus, string> = {planned:'Planned',available:'Available',missing:'Missing',blocked:'Blocked',stale:'Refresh needed',invalid:'Invalid','needs-review':'Needs review'};
const OUTPUT_KIND_LABELS: Record<ExecutionOutputKind, string> = {artifact:'Artifact',report:'Report',preview:'Preview','workspace-record':'Workspace record'};
const DEP_KIND_LABELS: Record<ExecutionDependencyKind, string> = {'step-after-step':'Step order','input-required':'Input required','output-required':'Output required','provider-required':'Provider required','safety-gate-required':'Safety check required','manual-review-required':'Manual review required','artifact-required':'Artifact required'};
const DEP_STATUS_LABELS: Record<ExecutionDependencyStatus, string> = {planned:'Planned','satisfied-by-plan':'Satisfied by plan',missing:'Missing',blocked:'Blocked',stale:'Refresh needed',invalid:'Invalid'};
const ADAPTER_KIND_LABELS: Record<ExecutionAdapterReferenceKind, string> = {'provider-adapter':'Provider setup','model-adapter':'Model setup','storage-adapter':'Storage setup','artifact-adapter':'Artifact setup','api-adapter':'API setup'};
const ADAPTER_STATUS_LABELS: Record<ExecutionAdapterReferenceStatus, string> = {planned:'Planned','available-by-readiness':'Available from setup','needs-setup':'Needs setup',missing:'Missing',blocked:'Blocked',unsupported:'Unsupported',stale:'Refresh needed',invalid:'Invalid'};
const GATE_KIND_LABELS: Record<ExecutionSafetyGateKind, string> = {'required-input-available':'Required input available','output-destination-planned':'Output destination planned','provider-setup-selected':'Provider setup selected','storage-destination-safe':'Storage destination safe','no-unresolved-blockers':'No unresolved blockers','user-review-required':'User review required','policy-review-required':'Policy review required','resource-estimate-review':'Estimate review','execution-preview-reviewed':'Preview reviewed','credentials-not-embedded':'Credentials not embedded','unsafe-details-redacted':'Unsafe details redacted','executable-payload-deferred':'Executable payload deferred'};
const GATE_STATUS_LABELS: Record<ExecutionSafetyGateStatus, string> = {planned:'Planned','passed-by-plan':'Passed by plan','needs-review':'Needs review',blocked:'Blocked',failed:'Failed',deferred:'Deferred','not-applicable':'Not applicable'};
const safe=(x?:string)=>x?.replace(/(?:https?:\/\/|\/[\w./-]+|token|secret|password|api[_-]?key|private[_-]?key|stack\s*trace|command\s*output|workflow\s*json|prompt\s*text|base64|signed\s*url)/gi,'[redacted]').trim();

export class ExecutionPlanReadModelService {
  constructor(private readonly repo: ExecutionPlanRepositoryPort) {}
  private ws(v:string|undefined):WorkspaceId{ if(!v?.trim()) throw new Error('validation:workspaceId'); return createWorkspaceId(v); }
  private async list(workspaceId: WorkspaceId, query: Record<string, unknown>={}) { return (await this.repo.listExecutionPlans({ workspaceId, ...query })).plans; }
  private summary(p: ExecutionPlanRecord){ const reqIn=p.inputs.filter(i=>i.required); const reqOut=p.outputs.filter(o=>o.required); const attention=this.needsAttention(p);
    return { executionPlanId:p.id, workspaceId:p.workspaceId, sourceCompositionPlanId:p.sourceCompositionPlanId, sourceRuntimeReadinessBindingId:p.sourceRuntimeReadinessBindingId, sourceReadinessStatus:safe(p.sourceReadinessStatus), executionPlanStatus:p.status, statusLabel:STATUS_LABELS[p.status], needsAttention:attention, attentionLabel:attention?'Needs attention':'Ready for review', stepCount:p.steps.length,inputCount:p.inputs.length,outputCount:p.outputs.length,dependencyCount:p.dependencies.length,adapterReferenceCount:p.adapterReferences.length,safetyGateCount:p.safetyGates.length,blockerCount:p.blockers.length,diagnosticCount:p.diagnostics.length,missingInputCount:reqIn.filter(i=>['missing','blocked','stale','invalid'].includes(i.status)).length,missingOutputCount:reqOut.filter(i=>['missing','blocked','stale','invalid'].includes(i.status)).length,providerSetupRequiredCount:p.adapterReferences.filter(a=>['needs-setup','missing','blocked','unsupported','stale','invalid'].includes(a.status)).length,safetyReviewRequiredCount:p.safetyGates.filter(g=>['needs-review','blocked','failed'].includes(g.status)).length,manualDeferredStepCount:p.steps.filter(s=>s.kind==='manual-review'||s.status==='deferred').length,stale:p.status==='stale',invalid:p.status==='invalid',resourceEstimateSummary:{compute:p.resourceEstimates[0]?.compute??'unknown',storage:p.resourceEstimates[0]?.storage??'unknown',duration:p.resourceEstimates[0]?.duration??'unknown',providerCategoryCount:new Set(p.adapterReferences.map((a)=>a.providerKind).filter(Boolean)).size},createdAt:p.createdAt,updatedAt:p.updatedAt,archivedAt:p.archivedAt };
  }
  private needsAttention(p:ExecutionPlanRecord){ if(['needs-setup','missing-inputs','missing-outputs','provider-setup-required','safety-review-required','blocked','stale','invalid'].includes(p.status)) return true; return p.blockers.length>0; }
  async listExecutionPlanSummaries(request:{workspaceId:string; includeArchived?:boolean; limit?:number; cursor?:string; status?:ExecutionPlanStatus}){ const ws=this.ws(request.workspaceId); const plans=await this.list(ws,{archived:request.includeArchived?undefined:false,limit:request.limit,cursor:request.cursor,status:request.status}); return {summaries:plans.map((p)=>this.summary(p))}; }
  async readExecutionPlanDetail(request:{workspaceId:string; executionPlanId:string}){ const ws=this.ws(request.workspaceId); const id=normalizeExecutionPlanId(request.executionPlanId); const p=await this.repo.getExecutionPlanById(ws,id); if(!p||p.workspaceId!==ws) return undefined; const summary=this.summary(p); return {summary, stepSummaries:p.steps.map((s)=>({stepId:s.id,sourceNodeId:s.sourceNodeId,sourceRelationshipId:s.sourceRelationshipId,stepKind:s.kind,stepKindLabel:STEP_KIND_LABELS[s.kind],stepStatus:s.status,stepStatusLabel:STEP_STATUS_LABELS[s.status],label:safe(s.label),summary:safe(s.summary)})),inputSummaries:p.inputs.map((i)=>({inputId:i.id,stepId:i.stepId,inputKind:i.kind,inputKindLabel:INPUT_KIND_LABELS[i.kind],inputStatus:i.status,inputStatusLabel:IO_STATUS_LABELS[i.status],label:safe(i.label)})),outputSummaries:p.outputs.map((o)=>({outputId:o.id,stepId:o.stepId,outputKind:o.kind,outputKindLabel:OUTPUT_KIND_LABELS[o.kind],outputStatus:o.status,outputStatusLabel:IO_STATUS_LABELS[o.status],label:safe(o.label)})),dependencySummaries:p.dependencies.map((d)=>({dependencyId:d.id,dependencyKind:d.kind,dependencyKindLabel:DEP_KIND_LABELS[d.kind],dependencyStatus:d.status,dependencyStatusLabel:DEP_STATUS_LABELS[d.status],label:safe(d.label)})),adapterReferenceSummaries:p.adapterReferences.map((a)=>({adapterReferenceId:a.id,adapterReferenceKind:a.kind,adapterReferenceKindLabel:ADAPTER_KIND_LABELS[a.kind],adapterReferenceStatus:a.status,adapterReferenceStatusLabel:ADAPTER_STATUS_LABELS[a.status],label:safe(a.label)})),safetyGateSummaries:p.safetyGates.map((g)=>({safetyGateId:g.id,safetyGateKind:g.kind,safetyGateKindLabel:GATE_KIND_LABELS[g.kind],safetyGateStatus:g.status,safetyGateStatusLabel:GATE_STATUS_LABELS[g.status],label:safe(g.label)})),resourceEstimateSummaries:p.resourceEstimates.map((r)=>({estimateId:r.id,category:'execution-plan',estimate:{compute:r.compute,storage:r.storage,duration:r.duration},label:'Resource estimate',summary:safe(r.summary)})),blockers:p.blockers.map((b)=>({code:b.code,severity:'error',message:safe(b.message)})), diagnostics:p.diagnostics.map((d)=>({code:d.code,severity:d.severity,message:safe(d.message)})), provenanceSummary:{createdAt:p.createdAt,lastStatusUpdateAt:p.updatedAt}}; }
  async listExecutionPlansForCompositionPlan(r:{workspaceId:string; compositionPlanId:string; includeArchived?:boolean}){ const ws=this.ws(r.workspaceId); const plans=await this.list(ws,{sourceCompositionPlanId:r.compositionPlanId,archived:r.includeArchived?undefined:false}); return plans.map((p)=>this.summary(p)); }
  async readLatestExecutionPlanForCompositionPlan(r:{workspaceId:string; compositionPlanId:string; includeArchived?:boolean}){ const x=await this.listExecutionPlansForCompositionPlan(r); return x.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)||b.executionPlanId.localeCompare(a.executionPlanId))[0]; }
  async listExecutionPlansForRuntimeReadinessBinding(r:{workspaceId:string; runtimeReadinessBindingId:string; includeArchived?:boolean}){ const ws=this.ws(r.workspaceId); const plans=await this.list(ws,{sourceRuntimeReadinessBindingId:r.runtimeReadinessBindingId,archived:r.includeArchived?undefined:false}); return plans.map((p)=>this.summary(p)); }
  async readLatestExecutionPlanForRuntimeReadinessBinding(r:{workspaceId:string; runtimeReadinessBindingId:string; includeArchived?:boolean}){ const x=await this.listExecutionPlansForRuntimeReadinessBinding(r); return x.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)||b.executionPlanId.localeCompare(a.executionPlanId))[0]; }
  async listExecutionPlansNeedingAttention(r:{workspaceId:string}){ const {summaries}=await this.listExecutionPlanSummaries({workspaceId:r.workspaceId}); return summaries.filter((s)=>s.needsAttention); }
  async summarizeWorkspaceExecutionPlans(r:{workspaceId:string}){ const {summaries}=await this.listExecutionPlanSummaries({workspaceId:r.workspaceId,includeArchived:true}); const byStatus=summaries.reduce<Record<string,number>>((a,s)=>((a[s.executionPlanStatus]=(a[s.executionPlanStatus]??0)+1),a),{}); return {total:summaries.length,byStatus}; }
}
