export const mapReadinessStatusLabel = (s?: string) => ({draft:'Draft',checking:'Checking','ready-for-setup':'Ready for setup',blocked:'Needs setup','missing-requirements':'Missing requirement','provider-unavailable':'Provider unavailable','provider-unsupported':'Not supported','configuration-required':'Needs configuration','permission-required':'Permission needed',stale:'Refresh needed',invalid:'Invalid',archived:'Archived'} as Record<string,string>)[s ?? ''] ?? 'Unknown';
export const mapAvailabilityLabel = (s?: string) => ({available:'Available',unavailable:'Unavailable','not-installed':'Not installed','not-configured':'Needs configuration','permission-required':'Permission needed',unsupported:'Not supported',stale:'Refresh needed',unknown:'Unknown',error:'Needs attention'} as Record<string,string>)[s ?? ''] ?? 'Unknown';
export const mapBindingStatusLabel = (s?: string) => ({candidate:'Option',selected:'Selected',bound:'Selected',blocked:'Blocked','missing-requirement':'Missing requirement','provider-unavailable':'Provider unavailable','configuration-required':'Needs configuration','permission-required':'Permission needed',unsupported:'Not supported',stale:'Refresh needed',invalid:'Invalid'} as Record<string,string>)[s ?? ''] ?? 'Unknown';
export const mapCapabilityLabel = (k?: string) => ({model:'Model','image-generation':'Image generation','text-generation':'Text generation',storage:'Storage','file-access':'File access','network-access':'Network access','api-service':'API service',python:'Python',node:'Node',comfyui:'ComfyUI',gpu:'GPU',memory:'Memory','credential-reference':'Credential reference'} as Record<string,string>)[k ?? ''] ?? 'Capability';
const safe=(v:unknown)=>typeof v==='string'&&v.length<180&&!/token|secret|path|stack|base64|command|shell|api[-_ ]?key/i.test(v);

type Detail = { summary?: { readinessStatus?: string; missingRequirementCount?: number; providerUnavailableCount?: number; configurationRequiredCount?: number; permissionRequiredCount?: number; staleCount?: number; needsAttention?: boolean; updatedAt?: string }; requirements?: Array<{label?: string; capabilityKind?: string; isRequired?: boolean; statusLabel?: string; candidateCount?: number}>; providerCandidates?: Array<{displayLabel?: string; providerKind?: string; availabilityStatus?: string; capabilityCount?: number}>; selectedBindings?: Array<{bindingStatus?: string}>; blockers?: Array<{message?: string}>; diagnostics?: Array<{message?: string}> };

export function mapRuntimeSetup(detail: Detail | undefined, inventorySummary: any){const b=detail;const diag=[...(b?.blockers??[]),...(b?.diagnostics??[])].map((x)=>x?.message).filter(safe) as string[];const summary=b?.summary;return {statusLabel: mapReadinessStatusLabel(summary?.readinessStatus),needsAttention:summary?.needsAttention===true,counts:{missing:summary?.missingRequirementCount??0,unavailable:summary?.providerUnavailableCount??0,configuration:summary?.configurationRequiredCount??0,permission:summary?.permissionRequiredCount??0,stale:summary?.staleCount??0},requirements:(b?.requirements??[]).map((r)=>({label:r.label||mapCapabilityLabel(r.capabilityKind),capability:mapCapabilityLabel(r.capabilityKind),required:r.isRequired?'Required':'Optional',status:r.statusLabel??'Unknown',candidates:r.candidateCount??0})),options:(b?.providerCandidates??[]).map((p)=>({label:p.displayLabel||'Provider',kind:p.providerKind||'Provider',availability:mapAvailabilityLabel(p.availabilityStatus),capabilityCount:p.capabilityCount??0})),selected:(b?.selectedBindings??[]).map((x)=>({requirement:'Requirement',choice:'Setup reference available',status:mapBindingStatusLabel(x.bindingStatus)})),issues:diag,inventory:inventorySummary?{knownProviders:inventorySummary.providerCandidateCount??0,knownCapabilities:inventorySummary.capabilityCount??0,availableProviders:0,unavailableProviders:inventorySummary.staleBlockedUnavailableCount??0,needsConfiguration:inventorySummary.configurationRequiredCount??0,permissionNeeded:inventorySummary.permissionRequiredCount??0,refreshNeeded:0,lastChecked:undefined}:undefined,lastChecked:summary?.updatedAt};}
