export type PlanSummaryViewModel={id:string;name:string;statusLabel:string;nodes:number;relationships:number;missing:number};
export type PlanNodeViewModel={id:string;projectionId?:string;label:string;statusLabel:string};
export type PlanRelationshipViewModel={id:string;sourceNodeId:string;targetNodeId:string;kindLabel:string;statusLabel:string};
export type PlanDetailViewModel={id:string;name:string;statusLabel:string;nodes:PlanNodeViewModel[];relationships:PlanRelationshipViewModel[];messages:string[]};
export type AssetOptionViewModel={id:string;label:string};
const planStatus:Record<string,string>={draft:'Draft',valid:'Ready for planning',blocked:'Blocked',conflicted:'Needs attention',stale:'Refresh needed',unsupported:'Not supported',invalid:'Invalid',archived:'Archived'};
const nodeStatus:Record<string,string>={'ready-for-planning':'Ready for planning',ready:'Ready for planning',planned:'Planned',blocked:'Blocked',conflicted:'Needs attention','missing-projection':'Missing requirement','stale-projection':'Refresh needed',unsupported:'Not supported',invalid:'Needs attention',disabled:'Not supported'};
const relStatus:Record<string,string>={compatible:'Looks compatible',unknown:'Not checked',blocked:'Blocked',conflicted:'Needs attention','missing-dependency':'Missing requirement',unsupported:'Not supported',stale:'Refresh needed',invalid:'Needs attention'};
const relKind:Record<string,string>={'depends-on':'Depends on','feeds-into':'Feeds into',configures:'Configures','uses-model':'Uses model','uses-data':'Uses data','produces-output':'Produces output','requires-capability':'Requires capability',supports:'Supports'};
const blockedAssetStatuses = new Set(['blocked','conflicted','stale','disabled','unsupported','invalid','source-missing','draft-only']);
const safe=(value:unknown,fallback:string)=>typeof value==='string'&&value.trim()?value.trim():fallback;
const mapStatus=(table:Record<string,string>,value:unknown)=>table[String(value??'').trim()]??'Needs attention';
export const sanitizeMessage=(value:unknown)=>safe(value,'Needs attention.').replace(/(token|secret|path|base64|workflow|prompt|payload|provider|command|env|ipc|repository)/ig,'[hidden]').slice(0,180);
export function mapPlanSummary(value:any):PlanSummaryViewModel{const s=value?.summary??value; return {id:safe(s?.planId,'plan'),name:safe(s?.name,'Untitled plan'),statusLabel:mapStatus(planStatus,s?.status),nodes:Number(s?.nodesCount??s?.planningSummary?.totalNodes??0),relationships:Number(s?.relationshipsCount??s?.planningSummary?.totalRelationships??0),missing:Number(s?.missingDependencyCount??s?.planningSummary?.missingDependencyCount??0)};}
export function mapPlanDetail(value:any):PlanDetailViewModel{const d=value?.detail??value; const nodes=(d?.nodes??[]).map((n:any)=>({id:safe(n?.nodeId,'node'),projectionId:typeof n?.selectedProjection?.projectionId==='string'?n.selectedProjection.projectionId:undefined,label:safe(n?.label,n?.selectedProjection?.displayLabel??'Asset'),statusLabel:mapStatus(nodeStatus,n?.status)})); const relationships=(d?.relationships??[]).map((r:any)=>({id:safe(r?.relationshipId,'relationship'),sourceNodeId:safe(r?.sourceNodeId,''),targetNodeId:safe(r?.targetNodeId,''),kindLabel:relKind[String(r?.kind??'').trim()]??'Connects to',statusLabel:mapStatus(relStatus,r?.compatibilityStatus)})); const messages=[...(d?.blockers??[]),...(d?.diagnostics??[])].map((x:any)=>sanitizeMessage(x?.message)).filter(Boolean).slice(0,8); return {id:safe(d?.planId,'plan'),name:safe(d?.name,'Untitled plan'),statusLabel:mapStatus(planStatus,d?.status),nodes,relationships,messages};}
export function mapAvailableAssets(items:any[]):AssetOptionViewModel[]{return items.filter((x)=>!blockedAssetStatuses.has(String(x?.status??''))&&(String(x?.status??'')==='ready'||x?.planningConsumable===true||String(x?.readinessLabel??'').toLowerCase().includes('ready'))).map((x)=>({id:String(x?.projectionId??''),label:`${safe(x?.projectedFields?.['display-name']??x?.displayName,'Asset')} (${safe(x?.sourceKind,'Workspace')})`})).filter((x)=>x.id);}
