import { useEffect, useMemo, useState } from "react";
import { mapAvailableAssets, mapPlanDetail, mapPlanSummary } from "./assetPlansViewModel";

const REL_KINDS = [
  ["depends-on", "Depends on"],["feeds-into", "Feeds into"],["configures", "Configures"],["uses-model", "Uses model"],["uses-data", "Uses data"],["produces-output", "Produces output"],["requires-capability", "Requires capability"],["supports", "Supports"],
] as const;

export function AssetPlansTab({ workspaceId, client, projectionClient }: { workspaceId: string; client: any; projectionClient: any; }) {
 const [plans,setPlans]=useState<any[]>([]); const [selectedPlanId,setSelectedPlanId]=useState(''); const [detail,setDetail]=useState<any>(); const [available,setAvailable]=useState<any[]>([]);
 const [state,setState]=useState<"idle"|"loading"|"error">('idle'); const [message,setMessage]=useState(''); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [projectionId,setProjectionId]=useState('');
 const [sourceNodeId,setSourceNodeId]=useState(''); const [relationshipKind,setRelationshipKind]=useState('depends-on'); const [targetNodeId,setTargetNodeId]=useState('');
 const refreshPlans=async(selectId?:string)=>{setState('loading'); const r=await client.listPlanSummaries({targetWorkspaceId:workspaceId}); if(!r.ok){setState('error');setMessage(r.error.message); return;} const items=(r.value.summaries??[]).map(mapPlanSummary); setPlans(items); const next=selectId??selectedPlanId??items[0]?.id??''; setSelectedPlanId(next); setState('idle');};
 const refreshDetail=async(planId:string)=>{ if(!planId)return; const r=await client.readPlanDetail({targetWorkspaceId:workspaceId,planId}); if(!r.ok){setMessage(r.error.message); return;} setDetail(mapPlanDetail(r.value.summary??r.value)); };
 useEffect(()=>{void refreshPlans();},[workspaceId]); useEffect(()=>{void refreshDetail(selectedPlanId);},[selectedPlanId]);
 useEffect(()=>{(async()=>{const r=await projectionClient?.listProjections?.(workspaceId); if(!r?.ok) return; setAvailable(mapAvailableAssets(r.value.summaries??r.value.projections??r.value.items??[]));})();},[workspaceId,projectionClient]);
 const nodeLabel=useMemo(()=>new Map((detail?.nodes??[]).map((n:any)=>[n.id,n.label])),[detail]);
 return <section className="ui-stack ui-stack--sm"><h2>Plans</h2>
 <form onSubmit={async(e)=>{e.preventDefault(); const r=await client.createPlan({targetWorkspaceId:workspaceId,name:name.trim(),description:description.trim()||undefined}); if(!r.ok){setMessage(r.error.message);return;} const id=r.value.plan?.planId??r.value.planId; setMessage('Plan created.'); setName(''); setDescription(''); await refreshPlans(id); if(id) await refreshDetail(id);}} className="ui-panel ui-stack ui-stack--xs"><h3>Create plan</h3><p><small>A plan organizes assets before you build a system. Nothing runs from this screen.</small></p><label>Name <input aria-label="Name" value={name} onChange={(e)=>setName(e.target.value)} /></label><label>Description <input aria-label="Description" value={description} onChange={(e)=>setDescription(e.target.value)} /></label><button>Create plan</button></form>
 {state==='loading'?<p role="status">Loading plans...</p>:null}{state==='error'?<p role="alert">Unable to load plans right now.</p>:null}
 {!plans.length&&state==='idle'?<p>No plans yet. Create a plan to organize assets before building a system.</p>:null}
 <ul>{plans.map((p:any)=><li key={p.id}><button onClick={()=>setSelectedPlanId(p.id)}>{p.name}</button> — {p.statusLabel} — Nodes {p.nodes} · Connections {p.relationships} · Missing requirements {p.missing}</li>)}</ul>
 {detail?<section className="ui-panel ui-stack ui-stack--xs"><h3>Plan details</h3><p><strong>{detail.name}</strong> — {detail.statusLabel}</p><h4>Assets in this plan</h4>
 {client.addProjectionToPlan?<div><select aria-label="Asset to add" value={projectionId} onChange={(e)=>setProjectionId(e.target.value)}><option value="">Select an asset</option>{available.map((a:any)=><option key={a.id} value={a.id}>{a.label}</option>)}</select><button onClick={async()=>{const r=await client.addProjectionToPlan({targetWorkspaceId:workspaceId,planId:detail.id,projectionId}); setMessage(r.ok?'Added to plan.':r.error.message); if(r.ok){await refreshPlans(detail.id); await refreshDetail(detail.id);}}}>Add to plan</button></div>:<p>Adding assets to plans is not available yet.</p>}
 <ul>{(detail.nodes??[]).map((n:any)=><li key={n.id}>{n.label} — {n.statusLabel} {client.removeProjectionFromPlan?<button onClick={async()=>{if(!n.projectionId){setMessage('Adding assets to plans is not available yet.'); return;} const r=await client.removeProjectionFromPlan({targetWorkspaceId:workspaceId,planId:detail.id,projectionId:n.projectionId}); setMessage(r.ok?'Removed.':r.error.message); if(r.ok){await refreshPlans(detail.id); await refreshDetail(detail.id);}}}>Remove</button>:null}</li>)}</ul>
 <h4>Connections</h4>{client.connectNodes?<div><select aria-label="Source asset" value={sourceNodeId} onChange={(e)=>setSourceNodeId(e.target.value)}><option value="">Source</option>{detail.nodes.map((n:any)=><option key={n.id} value={n.id}>{n.label}</option>)}</select><select aria-label="Relationship kind" value={relationshipKind} onChange={(e)=>setRelationshipKind(e.target.value)}>{REL_KINDS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Target asset" value={targetNodeId} onChange={(e)=>setTargetNodeId(e.target.value)}><option value="">Target</option>{detail.nodes.map((n:any)=><option key={n.id} value={n.id}>{n.label}</option>)}</select><button onClick={async()=>{const r=await client.connectNodes({targetWorkspaceId:workspaceId,planId:detail.id,sourceNodeId,kind:relationshipKind,targetNodeId}); setMessage(r.ok?'Connection added.':r.error.message); if(r.ok){await refreshPlans(detail.id); await refreshDetail(detail.id);}}}>Add connection</button></div>:<p>Connections are not available yet.</p>}
 <ul>{(detail.relationships??[]).map((rel:any)=><li key={rel.id}>{nodeLabel.get(rel.sourceNodeId)??'Asset'} {rel.kindLabel} {nodeLabel.get(rel.targetNodeId)??'Asset'} — {rel.statusLabel} {client.disconnectNodes?<button onClick={async()=>{const r=await client.disconnectNodes({targetWorkspaceId:workspaceId,planId:detail.id,relationshipId:rel.id}); setMessage(r.ok?'Connection removed.':r.error.message); if(r.ok){await refreshPlans(detail.id); await refreshDetail(detail.id);}}}>Remove connection</button>:null}</li>)}</ul>
 {client.validatePlan?<button onClick={async()=>{const r=await client.validatePlan({targetWorkspaceId:workspaceId,planId:detail.id}); setMessage(r.ok?'Plan checked.':r.error.message); if(r.ok){await refreshPlans(detail.id); await refreshDetail(detail.id);}}}>Check plan</button>:<p>Plan checking is not available yet.</p>}
 <h4>Messages / Needs attention</h4><ul>{(detail.messages??[]).map((m:string,i:number)=><li key={i}>{m}</li>)}</ul></section>:null}
 {message?<p role="status">{message}</p>:null}</section>;
}
