import type { BrowseModelsRequest, BrowseModelsResult, DeleteModelRecordRequest, DeleteModelRecordResult, DownloadModelRequest, DownloadModelResult, GetModelDetailsRequest, GetModelDetailsResult, ListModelsRequest, ListModelsResult, SaveModelReferenceRequest, SaveModelReferenceResult, UpdateModelRecordRequest, UpdateModelRecordResult } from "../../../../../../modules/contracts/model";

type ApiEnvelope={ok:boolean;value?:unknown;error?:{message?:string;code?:string;details?:unknown}};
export class ModelManagementApiError extends Error { constructor(message:string, public readonly code?:string, public readonly details?:unknown){super(message);} }
export interface ModelManagementApiClient { browseModels:(input:BrowseModelsRequest)=>Promise<BrowseModelsResult>; getModelDetails:(input:GetModelDetailsRequest)=>Promise<GetModelDetailsResult>; listModels:(input?:ListModelsRequest)=>Promise<ListModelsResult>; saveModelReference:(input:SaveModelReferenceRequest)=>Promise<SaveModelReferenceResult>; downloadModel:(input:DownloadModelRequest)=>Promise<DownloadModelResult>; updateModelRecord:(input:UpdateModelRecordRequest)=>Promise<UpdateModelRecordResult>; deleteModelRecord:(input:DeleteModelRecordRequest)=>Promise<DeleteModelRecordResult>; }
const apiUrl=(b:string,s:string)=>`${b.trim().replace(/\/+$/,"")||"/api"}${s}`;
const ensureEnvelope=(v:unknown):ApiEnvelope=>{ if(typeof v==="object"&&v!==null&&"ok" in v) return v as ApiEnvelope; throw new Error("Model management response is not a valid API envelope.");};
const pickSuccess=<T>(e:ApiEnvelope,p:(v:unknown)=>T):T=>{ if(!e.ok) throw new ModelManagementApiError(e.error?.message??"Model management request failed.",e.error?.code,e.error?.details); return p(e.value);};
const post = async <T>(base:string,path:string,body:Record<string,unknown>,pick:(v:unknown)=>T)=>{ const r=await fetch(apiUrl(base,path),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}); const e=ensureEnvelope(await r.json() as unknown); return pickSuccess(e,pick); };
export function createApiModelManagementClient(options:{apiBaseUrl?:string;source?:string}={}):ModelManagementApiClient { const apiBaseUrl=options.apiBaseUrl??"/api"; const source=options.source??"thin-client.model-management"; return {
  browseModels: (input)=> post(apiBaseUrl,"/model/browse",{...input,source},(v)=>{const models=(v as BrowseModelsResult|undefined)?.models; return {models:Array.isArray(models)?models:[], nextCursor:(v as BrowseModelsResult|undefined)?.nextCursor};}),
  getModelDetails: (input)=> post(apiBaseUrl,"/model/details",{...input,source},(v)=>{const model=(v as GetModelDetailsResult|undefined)?.model; if(!model||typeof model!=="object") throw new Error("Model details response is missing model."); return {model};}),
  listModels: (input={})=> post(apiBaseUrl,"/model/list",{...input,source},(v)=>{const models=(v as ListModelsResult|undefined)?.models; return {models:Array.isArray(models)?models:[], nextCursor:(v as ListModelsResult|undefined)?.nextCursor};}),
  saveModelReference:(input)=> post(apiBaseUrl,"/model/reference/save",{...input,source},(v)=>{const model=(v as SaveModelReferenceResult|undefined)?.model; if(!model||typeof model!=="object") throw new Error("Save model response is missing model."); return {model};}),
  downloadModel:(input)=> post(apiBaseUrl,"/model/download",{...input,source},(v)=>{const result=v as DownloadModelResult|undefined; if(!result?.model||!result.download) throw new Error("Download model response is missing fields."); return result;}),
  updateModelRecord:(input)=> post(apiBaseUrl,"/model/record/update",{...input,source},(v)=>{const model=(v as UpdateModelRecordResult|undefined)?.model; if(!model||typeof model!=="object") throw new Error("Update model response is missing model."); return {model};}),
  deleteModelRecord:(input)=> post(apiBaseUrl,"/model/record/delete",{...input,source},(v)=>v as DeleteModelRecordResult),
 };}
