// user-library IPC registration
import type { UserLibraryAssetRepositoryPort, WorkspaceUserLibraryLinkRepositoryPort } from "../../../../application/ports/user-library";
import type { CopyUserLibraryAssetToWorkspaceUseCase, ImportWorkspaceAssetToWorkspaceUseCase, LinkUserLibraryAssetToWorkspaceUseCase, PromoteWorkspaceAssetToUserLibraryUseCase } from "../../../../application/use-cases/user-library";
import { createWorkspaceId } from "../../../../contracts/workspace";
import { DESKTOP_USER_LIBRARY_PROMOTE_REQUEST_CHANNEL, DESKTOP_USER_LIBRARY_PROMOTE_RESPONSE_CHANNEL, DESKTOP_USER_LIBRARY_LINK_REQUEST_CHANNEL, DESKTOP_USER_LIBRARY_LINK_RESPONSE_CHANNEL, DESKTOP_USER_LIBRARY_COPY_REQUEST_CHANNEL, DESKTOP_USER_LIBRARY_COPY_RESPONSE_CHANNEL, DESKTOP_USER_LIBRARY_IMPORT_REQUEST_CHANNEL, DESKTOP_USER_LIBRARY_IMPORT_RESPONSE_CHANNEL, DESKTOP_USER_LIBRARY_ASSET_LIST_REQUEST_CHANNEL, DESKTOP_USER_LIBRARY_ASSET_LIST_RESPONSE_CHANNEL, DESKTOP_USER_LIBRARY_ASSET_READ_REQUEST_CHANNEL, DESKTOP_USER_LIBRARY_ASSET_READ_RESPONSE_CHANNEL, DESKTOP_USER_LIBRARY_LINK_LIST_REQUEST_CHANNEL, DESKTOP_USER_LIBRARY_LINK_LIST_RESPONSE_CHANNEL, DESKTOP_USER_LIBRARY_LINK_READ_REQUEST_CHANNEL, DESKTOP_USER_LIBRARY_LINK_READ_RESPONSE_CHANNEL, createDesktopUserLibraryFailureResponse, createDesktopUserLibraryOperationSuccessResponse } from "../../../../contracts/ipc";
import type { IpcMainHandlePort } from "../ipcMainHandlePort";
export interface RegisterUserLibraryIpcDependencies { ipcMain:IpcMainHandlePort; promoteUseCase?:PromoteWorkspaceAssetToUserLibraryUseCase; linkUseCase?:LinkUserLibraryAssetToWorkspaceUseCase; copyUseCase?:CopyUserLibraryAssetToWorkspaceUseCase; importUseCase?:ImportWorkspaceAssetToWorkspaceUseCase; userLibraryAssetRepository?:UserLibraryAssetRepositoryPort; workspaceUserLibraryLinkRepository?:WorkspaceUserLibraryLinkRepositoryPort; }
const ctx=(r:any)=>({requestId:r?.requestId,correlationId:r?.correlationId});
export function registerUserLibraryIpc(d:RegisterUserLibraryIpcDependencies):void { /* trimmed */ d.ipcMain.handle(DESKTOP_USER_LIBRARY_PROMOTE_REQUEST_CHANNEL.value,async(_e,r:any)=>{const c=ctx(r); if(!d.promoteUseCase) return createDesktopUserLibraryFailureResponse(DESKTOP_USER_LIBRARY_PROMOTE_RESPONSE_CHANNEL,'user-library.promote-workspace-asset','unavailable','User-library promotion is unavailable.',c); try{ return createDesktopUserLibraryOperationSuccessResponse(DESKTOP_USER_LIBRARY_PROMOTE_RESPONSE_CHANNEL, await d.promoteUseCase.execute({...r.payload,sourceWorkspaceId:createWorkspaceId(r.payload?.sourceWorkspaceId)}), c);}catch{return createDesktopUserLibraryFailureResponse(DESKTOP_USER_LIBRARY_PROMOTE_RESPONSE_CHANNEL,'user-library.promote-workspace-asset','validation','Promotion request is invalid.',c);} }); }
